import { index, int, mysqlTable, text, timestamp, varchar } from "drizzle-orm/mysql-core";
import { user } from "./auth";
import { block } from "./blocks";
import { financialTransaction } from "./finance";
import { realizationRequest } from "./budgets";

export const blockHistory = mysqlTable("block_history", { id: varchar("id", { length: 36 }).primaryKey(), blockId: varchar("block_id", { length: 36 }).notNull().references(() => block.id, { onDelete: "cascade" }), action: varchar("action", { length: 32 }).notNull(), oldValues: text("old_values"), newValues: text("new_values"), changedBy: varchar("changed_by", { length: 36 }).notNull().references(() => user.id, { onDelete: "restrict" }), createdAt: timestamp("created_at").notNull() }, (table) => [index("block_history_block_created_idx").on(table.blockId, table.createdAt)]);
export const transactionEvidence = mysqlTable("transaction_evidence", { id: varchar("id", { length: 36 }).primaryKey(), transactionId: varchar("transaction_id", { length: 36 }).notNull().references(() => financialTransaction.id, { onDelete: "restrict" }), storageKey: varchar("storage_key", { length: 255 }).notNull(), contentType: varchar("content_type", { length: 100 }), sizeBytes: int("size_bytes"), createdBy: varchar("created_by", { length: 36 }).notNull().references(() => user.id, { onDelete: "restrict" }), createdAt: timestamp("created_at").notNull() }, (table) => [index("transaction_evidence_transaction_idx").on(table.transactionId)]);
export const realizationApproval = mysqlTable("realization_approval", { id: varchar("id", { length: 36 }).primaryKey(), realizationId: varchar("realization_id", { length: 36 }).notNull().references(() => realizationRequest.id, { onDelete: "restrict" }), action: varchar("action", { length: 16 }).notNull(), notes: text("notes"), actorUserId: varchar("actor_user_id", { length: 36 }).notNull().references(() => user.id, { onDelete: "restrict" }), createdAt: timestamp("created_at").notNull() }, (table) => [index("realization_approval_realization_idx").on(table.realizationId)]);
export const realizationEvidence = mysqlTable("realization_evidence", { id: varchar("id", { length: 36 }).primaryKey(), realizationId: varchar("realization_id", { length: 36 }).notNull().references(() => realizationRequest.id, { onDelete: "restrict" }), storageKey: varchar("storage_key", { length: 255 }).notNull(), contentType: varchar("content_type", { length: 100 }), sizeBytes: int("size_bytes"), createdBy: varchar("created_by", { length: 36 }).notNull().references(() => user.id, { onDelete: "restrict" }), createdAt: timestamp("created_at").notNull() }, (table) => [index("realization_evidence_realization_idx").on(table.realizationId)]);
