import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useRouter } from "expo-router";
import { useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { AppAlert as Alert } from "../src/lib/feedback";
import { useAuth } from "../src/auth";
import { BottomNav, EmptyState, ErrorState, Header, LoadingState, Screen } from "../src/components/Screen";
import { SelectField, SubmitButton, TextInputField } from "../src/components/NativeForm";
import { SearchField } from "../src/components/MobilePrimitives";
import { createAdminUser, getAdminUsers, getApiHealth, getAuditLogs, getSystemSettings, updateAdminUser, updateSystemSettings } from "../src/lib/api";
import { text } from "../src/lib/read";
import { colors, spacing } from "../src/theme";
import { adminCreateUserFormSchema, settingsFormSchema } from "../src/form-schemas";

type Tab = "settings" | "users" | "audit" | "masters";
export default function Admin() {
  const { role, session } = useAuth(); const router = useRouter(); const client = useQueryClient(); const [tab, setTab] = useState<Tab>("settings"); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [roleId, setRoleId] = useState("PETUGAS_LAPANGAN"); const [password, setPassword] = useState(""); const [query, setQuery] = useState(""); const [savingSettings, setSavingSettings] = useState(false); const [creating, setCreating] = useState(false); const [updatingUserId, setUpdatingUserId] = useState<string | null>(null); const [settingsErrors, setSettingsErrors] = useState<Record<string, string>>({}); const [createErrors, setCreateErrors] = useState<Record<string, string>>({});
  const settings = useQuery({ queryKey: ["system-settings"], queryFn: getSystemSettings, enabled: role === "PIMPINAN" });
  const health = useQuery({ queryKey: ["api-health"], queryFn: getApiHealth, enabled: role === "PIMPINAN" && tab === "settings", retry: false, staleTime: 0 });
  const users = useQuery({ queryKey: ["admin-users"], queryFn: () => getAdminUsers(), enabled: role === "PIMPINAN" });
  const audit = useQuery({ queryKey: ["audit", query], queryFn: () => getAuditLogs({ query, pageSize: "30" }), enabled: role === "PIMPINAN" && tab === "audit" });
  if (!role) return null;
  if (role !== "PIMPINAN" || !session?.permissions.includes("SETTINGS_MANAGE")) return <><Header role={role} title="Administration" subtitle="Restricted access" /><Screen><EmptyState message="Only Pimpinan can manage settings." /></Screen><BottomNav current="profile" role={role} /></>;
  const saveSettings = async () => { if (!settings.data?.settings) return; const validationErrors = validateSettings(settings.data.settings); setSettingsErrors(validationErrors); if (Object.keys(validationErrors).length) return Alert.alert("Periksa pengaturan", Object.values(validationErrors)[0]); setSavingSettings(true); try { await updateSystemSettings(settings.data.settings); await client.invalidateQueries({ queryKey: ["system-settings"] }); Alert.alert("Saved", "Settings are updated and audited."); } catch (error) { Alert.alert("Unable to save", error instanceof Error ? error.message : "Periksa data dan koneksi lalu coba lagi."); } finally { setSavingSettings(false); } };
  const createAccount = async () => { const parsed = adminCreateUserFormSchema.safeParse({ name, email, roleId, password }); const nextErrors: Record<string, string> = {}; if (!parsed.success) parsed.error.issues.forEach((issue) => { const key = String(issue.path[0] ?? "form"); if (!nextErrors[key]) nextErrors[key] = issue.message; }); setCreateErrors(nextErrors); if (!parsed.success) return Alert.alert("Periksa data akun", parsed.error.issues[0]?.message ?? "Lengkapi nama, email, role, dan password."); setCreating(true); try { const result = await createAdminUser(parsed.data); setName(""); setEmail(""); setPassword(""); setCreateErrors({}); await client.invalidateQueries({ queryKey: ["admin-users"] }); Alert.alert("Account created", result.message ?? "The account is ready to use."); } catch (error) { Alert.alert("Unable to create account", error instanceof Error ? error.message : "Periksa koneksi lalu coba lagi."); } finally { setCreating(false); } };
  const toggleUserStatus = async (item: Record<string, unknown>) => { const id = text(item, "id"); if (!id || updatingUserId) return; setUpdatingUserId(id); const nextStatus = text(item, "status") === "ACTIVE" ? "INACTIVE" : "ACTIVE"; try { await updateAdminUser(id, { status: nextStatus }); await client.invalidateQueries({ queryKey: ["admin-users"] }); Alert.alert("User updated", nextStatus === "ACTIVE" ? "User is active again." : "User has been deactivated."); } catch (error) { Alert.alert("Unable to update user", error instanceof Error ? error.message : "Periksa koneksi lalu coba lagi."); } finally { setUpdatingUserId(null); } };
  return <><Header role={role} title="Administration" subtitle="Settings, users, and audit history" /><Screen><SelectField label="SECTION" value={tab} onChange={(value) => setTab(value as Tab)} options={[{ label: "Settings", value: "settings" }, { label: "Users", value: "users" }, { label: "Audit", value: "audit" }, { label: "Master data", value: "masters" }]} />
    {tab === "settings" ? <>{settings.isLoading ? <LoadingState /> : settings.isError ? <ErrorState message="Settings could not be loaded." onRetry={() => settings.refetch()} /> : <SettingsForm value={settings.data?.settings ?? {}} errors={settingsErrors} onChange={(value) => { setSettingsErrors({}); client.setQueryData(["system-settings"], { settings: value }); }} onSave={() => void saveSettings()} saving={savingSettings} />}<ServerHealth health={health} /></> : null}
    {tab === "users" ? <><View style={styles.card}><Text style={styles.title}>Create account</Text><Text style={styles.meta}>Set the user’s full name, role, email, and initial password. The account can sign in immediately.</Text><TextInputField label="Full name" required error={createErrors.name} value={name} onChange={(value) => { setName(value); setCreateErrors((current) => ({ ...current, name: "" })); }} placeholder="Nama lengkap" /><TextInputField label="Email" required error={createErrors.email} value={email} onChange={(value) => { setEmail(value); setCreateErrors((current) => ({ ...current, email: "" })); }} placeholder="nama@contoh.id" keyboardType="email-address" /><SelectField label="Role" required error={createErrors.roleId} value={roleId} onChange={(value) => { setRoleId(value); setCreateErrors((current) => ({ ...current, roleId: "" })); }} options={(users.data?.roles ?? []).map((item) => ({ label: text(item, "name"), value: text(item, "id") }))} /><TextInputField label="Password" required error={createErrors.password} value={password} onChange={(value) => { setPassword(value); setCreateErrors((current) => ({ ...current, password: "" })); }} placeholder="Minimum 8 characters" helper="Use a unique password with at least 8 characters." secureTextEntry /><SubmitButton label="Create account" loading={creating} loadingLabel="Creating account…" onPress={() => void createAccount()} /></View>{users.isLoading ? <LoadingState /> : users.isError ? <ErrorState message="Users could not be loaded." onRetry={() => users.refetch()} /> : users.data?.users.map((item) => { const userId = text(item, "id"); const updating = updatingUserId === userId; return <View key={userId} style={styles.row}><View><Text style={styles.name}>{text(item, "name")}</Text><Text style={styles.meta}>{text(item, "email")} · {text(item, "roleName", "No role")}</Text></View><Pressable disabled={Boolean(updatingUserId)} onPress={() => void toggleUserStatus(item)} style={updating && { opacity: 0.55 }}><Text style={text(item, "status") === "ACTIVE" ? styles.danger : styles.success}>{updating ? "Updating…" : text(item, "status") === "ACTIVE" ? "Deactivate" : "Activate"}</Text></Pressable></View>; })}</> : null}
    {tab === "audit" ? <><SearchField value={query} onChangeText={setQuery} onClear={() => setQuery("")} placeholder="Search actor, record, or ID" />{audit.isLoading ? <LoadingState /> : audit.isError ? <ErrorState message="Audit history could not be loaded." onRetry={() => audit.refetch()} /> : audit.data?.rows.map((item) => <View key={text(item, "id")} style={styles.row}><View><Text style={styles.name}>{text(item, "action")} · {text(item, "entityType")}</Text><Text style={styles.meta}>{text(item, "actorName", "System")} · {String(item.createdAt ?? "")}</Text></View></View>)}</> : null}
    {tab === "masters" ? <View style={styles.card}><Text style={styles.title}>Master data</Text><Pressable onPress={() => router.push("/business-actors")} style={styles.link}><Text style={styles.linkText}>Business actors</Text></Pressable><Pressable onPress={() => router.push("/finance-categories")} style={styles.link}><Text style={styles.linkText}>Finance categories</Text></Pressable><Pressable onPress={() => router.push("/budget-categories")} style={styles.link}><Text style={styles.linkText}>Budget categories</Text></Pressable></View> : null}
  </Screen><BottomNav current="profile" role={role} /></>;
}
function ServerHealth({ health }: { health: ReturnType<typeof useQuery<Awaited<ReturnType<typeof getApiHealth>>>> }) { return <View style={styles.card}><Text style={styles.title}>Server connectivity</Text><Text style={styles.meta}>{health.isLoading ? "Checking API and database…" : health.isError ? "Unable to reach the project API. Check the domain routing and EXPO_PUBLIC_API_URL." : health.data?.status === "ok" ? "API and database are available." : "API is reachable but the database check is unavailable."}</Text><SubmitButton label="Test connection" loading={health.isFetching} onPress={() => void health.refetch()} /></View>; }
function validateSettings(value: Record<string, unknown>): Record<string, string> { const organization = (value.organization ?? {}) as Record<string, unknown>; const finance = (value.financeDefaults ?? {}) as Record<string, unknown>; const period = (value.activePeriod ?? {}) as Record<string, unknown>; const parsed = settingsFormSchema.safeParse({ organizationName: organization.name, organizationPhone: organization.phone ?? "", monthlyDueAmount: finance.monthlyDueAmount, roadEntryDueAmount: finance.roadEntryDueAmount, monthlyDueDay: finance.monthlyDueDay, periodKey: period.periodKey }); if (parsed.success) return {}; const errors: Record<string, string> = {}; parsed.error.issues.forEach((issue) => { const key = String(issue.path[0] ?? "form"); if (!errors[key]) errors[key] = issue.message; }); return errors; }
function SettingsForm({ value, errors, onChange, onSave, saving }: { value: Record<string, unknown>; errors: Record<string, string>; onChange: (value: Record<string, unknown>) => void; onSave: () => void; saving: boolean }) { const organization = (value.organization ?? {}) as Record<string, unknown>; const finance = (value.financeDefaults ?? {}) as Record<string, unknown>; const period = (value.activePeriod ?? {}) as Record<string, unknown>; const change = (group: string, key: string, next: string) => onChange({ ...value, [group]: { ...((value[group] ?? {}) as Record<string, unknown>), [key]: ["monthlyDueAmount", "roadEntryDueAmount", "monthlyDueDay"].includes(key) ? (next.trim() ? Number(next) : "") : next } }); return <View style={styles.card}><Text style={styles.title}>Organization and finance defaults</Text><TextInputField label="Organization name" required error={errors.organizationName} value={text(organization, "name")} onChange={(next) => change("organization", "name", next)} placeholder="Organization name" /><TextInputField label="Organization phone" error={errors.organizationPhone} value={text(organization, "phone")} onChange={(next) => change("organization", "phone", next)} placeholder="Phone (optional)" keyboardType="phone-pad" /><TextInputField label="Monthly due amount" required error={errors.monthlyDueAmount} value={text(finance, "monthlyDueAmount")} onChange={(next) => change("financeDefaults", "monthlyDueAmount", next)} keyboardType="numeric" placeholder="Monthly due" /><TextInputField label="Road-entry due amount" required error={errors.roadEntryDueAmount} value={text(finance, "roadEntryDueAmount")} onChange={(next) => change("financeDefaults", "roadEntryDueAmount", next)} keyboardType="numeric" placeholder="Road-entry due" /><TextInputField label="Monthly due day" required error={errors.monthlyDueDay} value={text(finance, "monthlyDueDay")} onChange={(next) => change("financeDefaults", "monthlyDueDay", next)} keyboardType="numeric" placeholder="Monthly due day, 1-31" /><TextInputField label="Active period" required error={errors.periodKey} value={text(period, "periodKey")} onChange={(next) => change("activePeriod", "periodKey", next)} placeholder="Active period YYYY-MM" /><SubmitButton label="Save settings" loading={saving} onPress={onSave} /></View>; }
const styles = StyleSheet.create({ card: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 13, borderWidth: 1, gap: spacing.sm, padding: spacing.md }, title: { color: colors.text, fontSize: 14, fontWeight: "900" }, row: { alignItems: "center", backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 12, borderWidth: 1, flexDirection: "row", justifyContent: "space-between", padding: spacing.md }, name: { color: colors.text, fontSize: 12, fontWeight: "900" }, meta: { color: colors.textMuted, fontSize: 10, marginTop: 3, maxWidth: 245 }, danger: { color: colors.danger, fontSize: 11, fontWeight: "900" }, success: { color: colors.success, fontSize: 11, fontWeight: "900" }, link: { borderColor: colors.border, borderRadius: 10, borderWidth: 1, padding: 13 }, linkText: { color: colors.primary, fontSize: 12, fontWeight: "900" } });
