import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useRouter } from "expo-router";
import { useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { AppAlert as Alert, errorMessage } from "../src/lib/feedback";
import { useAuth } from "../src/auth";
import { BottomNav, EmptyState, ErrorState, Header, LoadingState, Screen } from "../src/components/Screen";
import { SelectField, SubmitButton, TextInputField } from "../src/components/NativeForm";
import { SearchField } from "../src/components/MobilePrimitives";
import { createAdminUser, getAdminUsers, getApiHealth, getAuditLogs, getSystemSettings, updateAdminUser, updateSystemSettings } from "../src/lib/api";
import { displayStatus, text } from "../src/lib/read";
import { colors, spacing } from "../src/theme";
import { adminCreateUserFormSchema, settingsFormSchema } from "../src/form-schemas";
import { useDateRange } from "../src/date-range-provider";

type Tab = "settings" | "users" | "audit" | "masters";
export default function Admin() {
  const { role, session } = useAuth(); const router = useRouter(); const client = useQueryClient(); const { range } = useDateRange(); const [tab, setTab] = useState<Tab>("settings"); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [roleId, setRoleId] = useState("PETUGAS_LAPANGAN"); const [password, setPassword] = useState(""); const [query, setQuery] = useState(""); const [savingSettings, setSavingSettings] = useState(false); const [creating, setCreating] = useState(false); const [updatingUserId, setUpdatingUserId] = useState<string | null>(null); const [settingsErrors, setSettingsErrors] = useState<Record<string, string>>({}); const [createErrors, setCreateErrors] = useState<Record<string, string>>({});
  const settings = useQuery({ queryKey: ["system-settings"], queryFn: getSystemSettings, enabled: role === "PIMPINAN" });
  const health = useQuery({ queryKey: ["api-health"], queryFn: getApiHealth, enabled: role === "PIMPINAN" && tab === "settings", retry: false, staleTime: 0 });
  const users = useQuery({ queryKey: ["admin-users"], queryFn: () => getAdminUsers(), enabled: role === "PIMPINAN" });
  const audit = useQuery({ queryKey: ["audit", range.dateFrom, range.dateTo, query], queryFn: () => getAuditLogs({ query, pageSize: "30" }), enabled: role === "PIMPINAN" && tab === "audit" });
  if (!role) return null;
  if (role !== "PIMPINAN" || !session?.permissions.includes("SETTINGS_MANAGE")) return <><Header role={role} title="Administrasi" subtitle="Akses terbatas" /><Screen><EmptyState message="Hanya Pimpinan yang dapat mengelola pengaturan." /></Screen><BottomNav current="profile" role={role} /></>;
  const saveSettings = async () => { if (!settings.data?.settings) return; const validationErrors = validateSettings(settings.data.settings); setSettingsErrors(validationErrors); if (Object.keys(validationErrors).length) return Alert.alert("Periksa pengaturan", Object.values(validationErrors)[0]); setSavingSettings(true); try { await updateSystemSettings(settings.data.settings); await client.invalidateQueries({ queryKey: ["system-settings"] }); Alert.alert("Tersimpan", "Pengaturan telah diperbarui dan dicatat dalam audit."); } catch (error) { Alert.alert("Tidak dapat menyimpan", error instanceof Error ? error.message : "Periksa data dan koneksi lalu coba lagi."); } finally { setSavingSettings(false); } };
  const createAccount = async () => { const parsed = adminCreateUserFormSchema.safeParse({ name, email, roleId, password }); const nextErrors: Record<string, string> = {}; if (!parsed.success) parsed.error.issues.forEach((issue) => { const key = String(issue.path[0] ?? "form"); if (!nextErrors[key]) nextErrors[key] = issue.message; }); setCreateErrors(nextErrors); if (!parsed.success) return Alert.alert("Periksa data akun", parsed.error.issues[0]?.message ?? "Lengkapi nama, email, peran, dan kata sandi."); setCreating(true); try { const result = await createAdminUser(parsed.data); setName(""); setEmail(""); setPassword(""); setCreateErrors({}); await client.invalidateQueries({ queryKey: ["admin-users"] }); Alert.alert("Akun dibuat", result.message ?? "Akun siap digunakan."); } catch (error) { Alert.alert("Tidak dapat membuat akun", error instanceof Error ? error.message : "Periksa koneksi lalu coba lagi."); } finally { setCreating(false); } };
  const toggleUserStatus = async (item: Record<string, unknown>) => { const id = text(item, "id"); if (!id || updatingUserId) return; setUpdatingUserId(id); const nextStatus = text(item, "status") === "ACTIVE" ? "INACTIVE" : "ACTIVE"; try { await updateAdminUser(id, { status: nextStatus }); await client.invalidateQueries({ queryKey: ["admin-users"] }); Alert.alert("Pengguna diperbarui", nextStatus === "ACTIVE" ? "Pengguna aktif kembali." : "Pengguna telah dinonaktifkan."); } catch (error) { Alert.alert("Tidak dapat memperbarui pengguna", error instanceof Error ? error.message : "Periksa koneksi lalu coba lagi."); } finally { setUpdatingUserId(null); } };
  return <><Header role={role} title="Administrasi" subtitle="Pengaturan, pengguna, dan riwayat audit" /><Screen><SelectField label="Bagian" value={tab} onChange={(value) => setTab(value as Tab)} options={[{ label: "Pengaturan", value: "settings" }, { label: "Pengguna", value: "users" }, { label: "Audit", value: "audit" }, { label: "Data master", value: "masters" }]} />
    {tab === "settings" ? <>{settings.isLoading ? <LoadingState /> : settings.isError ? <ErrorState message="Pengaturan tidak dapat dimuat." onRetry={() => settings.refetch()} /> : <SettingsForm value={settings.data?.settings ?? {}} errors={settingsErrors} onChange={(value) => { setSettingsErrors({}); client.setQueryData(["system-settings"], { settings: value }); }} onSave={() => void saveSettings()} saving={savingSettings} />}<ServerHealth health={health} /></> : null}
    {tab === "users" ? <><View style={styles.card}><Text style={styles.title}>Buat akun</Text><Text style={styles.meta}>Isi nama lengkap, peran, email, dan kata sandi awal pengguna. Akun dapat langsung digunakan untuk masuk.</Text><TextInputField label="Nama lengkap" required error={createErrors.name} value={name} onChange={(value) => { setName(value); setCreateErrors((current) => ({ ...current, name: "" })); }} placeholder="Nama lengkap" /><TextInputField label="Email" required error={createErrors.email} value={email} onChange={(value) => { setEmail(value); setCreateErrors((current) => ({ ...current, email: "" })); }} placeholder="nama@contoh.id" keyboardType="email-address" /><SelectField label="Peran" required error={createErrors.roleId} value={roleId} onChange={(value) => { setRoleId(value); setCreateErrors((current) => ({ ...current, roleId: "" })); }} options={(users.data?.roles ?? []).map((item) => ({ label: text(item, "name"), value: text(item, "id") }))} /><TextInputField label="Kata sandi" required error={createErrors.password} value={password} onChange={(value) => { setPassword(value); setCreateErrors((current) => ({ ...current, password: "" })); }} placeholder="Minimal 8 karakter" helper="Gunakan kata sandi unik dengan minimal 8 karakter." secureTextEntry /><SubmitButton label="Buat akun" loading={creating} loadingLabel="Membuat akun…" onPress={() => void createAccount()} /></View>{users.isLoading ? <LoadingState /> : users.isError ? <ErrorState message="Data pengguna tidak dapat dimuat." onRetry={() => users.refetch()} /> : users.data?.users.map((item) => { const userId = text(item, "id"); const updating = updatingUserId === userId; return <View key={userId} style={styles.row}><View><Text style={styles.name}>{text(item, "name")}</Text><Text style={styles.meta}>{text(item, "email")} · {text(item, "roleName", "Tanpa peran")}</Text></View><Pressable disabled={Boolean(updatingUserId)} onPress={() => void toggleUserStatus(item)} style={updating && { opacity: 0.55 }}><Text style={text(item, "status") === "ACTIVE" ? styles.danger : styles.success}>{updating ? "Memperbarui…" : text(item, "status") === "ACTIVE" ? "Nonaktifkan" : "Aktifkan"}</Text></Pressable></View>; })}</> : null}
    {tab === "audit" ? <><SearchField value={query} onChangeText={setQuery} onClear={() => setQuery("")} placeholder="Cari pelaku, catatan, atau ID" />{audit.isLoading ? <LoadingState /> : audit.isError ? <ErrorState message="Riwayat audit tidak dapat dimuat." onRetry={() => audit.refetch()} /> : audit.data?.rows.map((item) => <View key={text(item, "id")} style={styles.row}><View><Text style={styles.name}>{displayStatus(text(item, "action"))} · {displayStatus(text(item, "entityType"))}</Text><Text style={styles.meta}>{text(item, "actorName", "Sistem")} · {String(item.createdAt ?? "")}</Text></View></View>)}</> : null}
    {tab === "masters" ? <View style={styles.card}><Text style={styles.title}>Data master</Text><Pressable onPress={() => router.push("/business-actors")} style={styles.link}><Text style={styles.linkText}>Pelaku usaha</Text></Pressable><Pressable onPress={() => router.push("/finance-categories")} style={styles.link}><Text style={styles.linkText}>Kategori keuangan</Text></Pressable><Pressable onPress={() => router.push("/budget-categories")} style={styles.link}><Text style={styles.linkText}>Kategori anggaran</Text></Pressable></View> : null}
  </Screen><BottomNav current="profile" role={role} /></>;
}
function ServerHealth({ health }: { health: ReturnType<typeof useQuery<Awaited<ReturnType<typeof getApiHealth>>>> }) { const deployment = health.data?.deployment; return <View style={styles.card}><Text style={styles.title}>Koneksi server</Text><Text style={styles.meta}>{health.isLoading ? "Memeriksa API dan basis data…" : health.isError ? errorMessage(health.error, "Tidak dapat menjangkau API proyek. Periksa URL API, DNS/HTTPS, dan status Coolify.") : health.data?.status === "ok" ? "API dan basis data tersedia." : "API dapat dijangkau, tetapi pemeriksaan basis data tidak tersedia."}</Text>{deployment ? <Text style={styles.meta}>Revisi server: {deployment.revision} · ID pemeriksaan: {deployment.requestId}</Text> : null}<SubmitButton label="Uji koneksi" loading={health.isFetching} onPress={() => void health.refetch()} /></View>; }
function validateSettings(value: Record<string, unknown>): Record<string, string> { const organization = (value.organization ?? {}) as Record<string, unknown>; const finance = (value.financeDefaults ?? {}) as Record<string, unknown>; const period = (value.activePeriod ?? {}) as Record<string, unknown>; const parsed = settingsFormSchema.safeParse({ organizationName: organization.name, organizationPhone: organization.phone ?? "", monthlyDueAmount: finance.monthlyDueAmount, roadEntryDueAmount: finance.roadEntryDueAmount, monthlyDueDay: finance.monthlyDueDay, periodKey: period.periodKey }); if (parsed.success) return {}; const errors: Record<string, string> = {}; parsed.error.issues.forEach((issue) => { const key = String(issue.path[0] ?? "form"); if (!errors[key]) errors[key] = issue.message; }); return errors; }
function SettingsForm({ value, errors, onChange, onSave, saving }: { value: Record<string, unknown>; errors: Record<string, string>; onChange: (value: Record<string, unknown>) => void; onSave: () => void; saving: boolean }) { const organization = (value.organization ?? {}) as Record<string, unknown>; const finance = (value.financeDefaults ?? {}) as Record<string, unknown>; const period = (value.activePeriod ?? {}) as Record<string, unknown>; const change = (group: string, key: string, next: string) => onChange({ ...value, [group]: { ...((value[group] ?? {}) as Record<string, unknown>), [key]: ["monthlyDueAmount", "roadEntryDueAmount", "monthlyDueDay"].includes(key) ? (next.trim() ? Number(next) : "") : next } }); return <View style={styles.card}><Text style={styles.title}>Bawaan organisasi dan keuangan</Text><TextInputField label="Nama organisasi" required error={errors.organizationName} value={text(organization, "name")} onChange={(next) => change("organization", "name", next)} placeholder="Nama organisasi" /><TextInputField label="Telepon organisasi" error={errors.organizationPhone} value={text(organization, "phone")} onChange={(next) => change("organization", "phone", next)} placeholder="Telepon (opsional)" keyboardType="phone-pad" /><TextInputField label="Jumlah iuran bulanan" required error={errors.monthlyDueAmount} value={text(finance, "monthlyDueAmount")} onChange={(next) => change("financeDefaults", "monthlyDueAmount", next)} keyboardType="numeric" placeholder="Iuran bulanan" /><TextInputField label="Jumlah iuran akses jalan" required error={errors.roadEntryDueAmount} value={text(finance, "roadEntryDueAmount")} onChange={(next) => change("financeDefaults", "roadEntryDueAmount", next)} keyboardType="numeric" placeholder="Iuran akses jalan" /><TextInputField label="Tanggal iuran bulanan" required error={errors.monthlyDueDay} value={text(finance, "monthlyDueDay")} onChange={(next) => change("financeDefaults", "monthlyDueDay", next)} keyboardType="numeric" placeholder="Tanggal iuran, 1-31" /><TextInputField label="Periode aktif" required error={errors.periodKey} value={text(period, "periodKey")} onChange={(next) => change("activePeriod", "periodKey", next)} placeholder="Periode aktif YYYY-MM" /><SubmitButton label="Simpan pengaturan" loading={saving} onPress={onSave} /></View>; }
const styles = StyleSheet.create({ card: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 13, borderWidth: 1, gap: spacing.sm, padding: spacing.md }, title: { color: colors.text, fontSize: 14, fontWeight: "900" }, row: { alignItems: "center", backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 12, borderWidth: 1, flexDirection: "row", justifyContent: "space-between", padding: spacing.md }, name: { color: colors.text, fontSize: 12, fontWeight: "900" }, meta: { color: colors.textMuted, fontSize: 10, marginTop: 3, maxWidth: 245 }, danger: { color: colors.danger, fontSize: 11, fontWeight: "900" }, success: { color: colors.success, fontSize: 11, fontWeight: "900" }, link: { borderColor: colors.border, borderRadius: 10, borderWidth: 1, padding: 13 }, linkText: { color: colors.primary, fontSize: 12, fontWeight: "900" } });
