import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { StyleSheet, Text, View } from "react-native";
import { AppAlert as Alert } from "../src/lib/feedback";

import { useAuth } from "../src/auth";
import { ErrorState, Header, LoadingState, Screen } from "../src/components/Screen";
import { Button, ButtonText } from "../src/components/ui/button";
import { DatePicker, ErrorText, SelectField, SubmitButton } from "../src/components/NativeForm";
import { createBlockFieldAssignment, endBlockFieldAssignment, getAssignedBlocks, getBlocks, getFieldOfficers } from "../src/lib/api";
import { text } from "../src/lib/read";
import { colors, spacing } from "../src/theme";
import { endAssignmentFormSchema, fieldAssignmentFormSchema } from "../src/form-schemas";
import { zodFieldErrors } from "../src/lib/form-validation";

export default function AssignmentsScreen() {
  const { role, session } = useAuth(); const client = useQueryClient(); const [saving, setSaving] = useState(false); const [blockId, setBlockId] = useState(""); const [officerId, setOfficerId] = useState(""); const [startedAt, setStartedAt] = useState(new Date().toISOString().slice(0, 10)); const [formErrors, setFormErrors] = useState<Record<string, string>>({});
  const assignments = useQuery({ queryKey: ["block-field-assignments"], queryFn: getAssignedBlocks, enabled: Boolean(role) }); const blocks = useQuery({ queryKey: ["blocks", "assignment-form"], queryFn: () => getBlocks(), enabled: Boolean(role) }); const officers = useQuery({ queryKey: ["field-officers"], queryFn: getFieldOfficers, enabled: Boolean(role) });
  if (!role) return null;
  const canManage = session?.permissions.includes("FIELD_ASSIGNMENT_MANAGE") ?? false;
  async function refresh() { await Promise.all([assignments.refetch(), client.invalidateQueries({ queryKey: ["blocks"] })]); }
  async function assign() { const parsed = fieldAssignmentFormSchema.safeParse({ blockId, fieldOfficerId: officerId, startedAt }); if (!parsed.success) { setFormErrors(zodFieldErrors(parsed.error)); return; } setFormErrors({}); setSaving(true); try { await createBlockFieldAssignment(parsed.data); setBlockId(""); setOfficerId(""); await refresh(); } catch (error) { Alert.alert("Tidak dapat menugaskan", error instanceof Error ? error.message : "Periksa koneksi lalu coba lagi."); } finally { setSaving(false); } }
  async function end(id: string) { if (saving) return; const parsed = endAssignmentFormSchema.safeParse({ id, endedAt: new Date().toISOString().slice(0, 10) }); if (!parsed.success) return Alert.alert("Tanggal penutupan tidak valid", parsed.error.issues[0]?.message ?? "Gunakan tanggal kalender yang valid."); setSaving(true); try { await endBlockFieldAssignment(parsed.data); await refresh(); } catch (error) { Alert.alert("Tidak dapat mengakhiri penugasan", error instanceof Error ? error.message : "Coba lagi."); } finally { setSaving(false); } }
  return <><Header role={role} title="Penugasan Blok" subtitle={canManage ? "Tetapkan petugas lapangan per blok" : "Blok yang ditugaskan kepada saya"} /><Screen>{assignments.isLoading ? <LoadingState /> : assignments.isError ? <ErrorState message="Penugasan tidak dapat dimuat." onRetry={() => assignments.refetch()} /> : <View style={styles.list}>{(assignments.data?.assignments ?? []).length ? assignments.data!.assignments.map((entry) => <View key={text(entry.assignment, "id")} style={styles.item}><Text style={styles.name}>{text(entry.block, "code")} · {text(entry.block, "name")}</Text><Text style={styles.copy}>{text(entry.officer, "name")} · mulai {text(entry.assignment, "startedAt")}</Text><Text style={styles.copy}>{text(entry.assignment, "endedAt", "Aktif")}</Text>{canManage && !text(entry.assignment, "endedAt") ? <Button accessibilityLabel="Akhiri penugasan" onPress={() => void end(text(entry.assignment, "id"))} variant="outline" className="mt-2 min-h-11 self-start rounded-xl border-[#F4B4B0] bg-white px-3"><ButtonText className="text-xs font-extrabold text-[#C03935]">Akhiri Penugasan</ButtonText></Button> : null}</View>) : <Text style={styles.empty}>Belum ada penugasan blok.</Text>}</View>}{canManage ? <View style={styles.form}><Text style={styles.formTitle}>Penugasan Baru</Text><SelectField label="Blok" required error={formErrors.blockId} value={blockId} onChange={(value) => { setBlockId(value); setFormErrors((current) => ({ ...current, blockId: "" })); }} options={(blocks.data?.blocks ?? []).map((block) => ({ label: `${block.code} · ${block.name}`, value: block.id }))} /><SelectField label="Petugas" required error={formErrors.fieldOfficerId} value={officerId} onChange={(value) => { setOfficerId(value); setFormErrors((current) => ({ ...current, fieldOfficerId: "" })); }} options={(officers.data?.officers ?? []).map((officer) => ({ label: officer.name, value: officer.id }))} /><DatePicker label="Tanggal mulai" value={startedAt} onChange={(value) => { setStartedAt(value); setFormErrors((current) => ({ ...current, startedAt: "" })); }} error={formErrors.startedAt} /><ErrorText value={formErrors.form} /><SubmitButton label="Simpan Penugasan" loading={saving} onPress={() => void assign()} /></View> : null}</Screen></>;
}

const styles = StyleSheet.create({ list: { gap: spacing.sm }, item: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 12, borderWidth: 1, gap: 5, padding: spacing.md }, name: { color: colors.text, fontSize: 13, fontWeight: "900" }, copy: { color: colors.textMuted, fontSize: 11 }, end: { color: colors.danger, fontSize: 11, fontWeight: "900", marginTop: 4 }, empty: { color: colors.textMuted, padding: spacing.lg, textAlign: "center" }, form: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 13, borderWidth: 1, gap: spacing.sm, padding: spacing.md }, formTitle: { color: colors.text, fontSize: 14, fontWeight: "900" } });
