import { useQuery } from "@tanstack/react-query";
import { Banknote } from "lucide-react-native";
import { useRouter } from "expo-router";
import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import { useAuth } from "../src/auth";
import { BottomNav, ErrorState, Header, LoadingState, Screen } from "../src/components/Screen";
import { ActionButton, InteractiveTabs, RowCard, SectionTitle } from "../src/components/PimpinanPrimitives";
import { getBudget, getBudgetsFiltered, getRealizationsFiltered } from "../src/lib/api";
import { money } from "../src/lib/format";
import { numberValue, text } from "../src/lib/read";
import { colors, spacing } from "../src/theme";

type Group = Record<string, unknown> & { items?: Array<Record<string, unknown>> };

export default function Budgets() {
  const { role, session } = useAuth(); const router = useRouter(); const [tab, setTab] = useState(0); const [periodKey, setPeriodKey] = useState(new Date().toISOString().slice(0, 7));
  const budgetQuery = useQuery({ queryKey: ["budgets", periodKey], queryFn: () => getBudgetsFiltered({ periodKey }), enabled: Boolean(role) }); const realizationQuery = useQuery({ queryKey: ["realizations", periodKey], queryFn: () => getRealizationsFiltered({ periodKey }), enabled: Boolean(role) });
  const activeBudgetId = text(budgetQuery.data?.budgets?.[0], "id"); const detailQuery = useQuery({ queryKey: ["budget", activeBudgetId], queryFn: () => getBudget(activeBudgetId), enabled: Boolean(role && activeBudgetId) });
  if (!role) return null;
  const budgets = budgetQuery.data?.budgets ?? []; const realizations = realizationQuery.data?.realizations ?? []; const data = detailQuery.data as { groups?: Group[]; summary?: Record<string, unknown> } | undefined; const summary = data?.summary ?? {}; const error = budgetQuery.isError || realizationQuery.isError || detailQuery.isError;
  const canCreate = session?.permissions.includes("BUDGET_CREATE"); const canManageCategories = session?.permissions.includes("BUDGET_CATEGORY_MANAGE"); const totalAllocation = numberValue(summary, "totalAllocation") || numberValue(budgets[0], "totalAllocation"); const availableFunds = numberValue(summary, "availableFunds") || numberValue(budgets[0], "availableFunds"); const unallocatedFunds = numberValue(summary, "unallocatedFunds") || numberValue(budgets[0], "unallocatedFunds"); const approvedRealization = numberValue(summary, "approvedRealization") || numberValue(budgets[0], "approvedRealization"); const absorption = numberValue(summary, "absorptionPercentage") || numberValue(budgets[0], "absorptionPercentage"); const allocated = availableFunds - unallocatedFunds;
  return <><Header role={role} title="Alokasi Anggaran" subtitle="Alokasi per kategori dan realisasi" /><Screen><View style={styles.period}><Text style={styles.eyebrow}>PERIODE</Text><TextInput value={periodKey} onChangeText={setPeriodKey} placeholder="YYYY-MM" style={styles.periodInput} /></View>{canManageCategories ? <Pressable onPress={() => router.push("/budget-categories")} style={styles.masterLink}><Text style={styles.masterLinkText}>Kelola kategori dan subkategori anggaran</Text></Pressable> : null}<InteractiveTabs active={tab} items={["Ringkasan", "Per Kategori", "Riwayat"]} onChange={setTab} />{error ? <ErrorState message="Data anggaran tidak dapat dimuat." onRetry={() => { void budgetQuery.refetch(); void realizationQuery.refetch(); void detailQuery.refetch(); }} /> : budgetQuery.isLoading || realizationQuery.isLoading || detailQuery.isLoading ? <LoadingState /> : tab === 2 ? <History realizations={realizations} onOpen={(id) => router.push(`/realization/${id}`)} /> : tab === 1 ? <CategoryBreakdown groups={data?.groups ?? []} onOpen={() => activeBudgetId && router.push(`/budget/${activeBudgetId}`)} /> : <><View style={styles.summary}><Text style={styles.eyebrow}>TOTAL ALOKASI</Text><Text style={styles.total}>{money(totalAllocation)}</Text><Metric label="Sudah dialokasikan" value={money(allocated)} color={colors.success} /><Metric label="Sisa belum dialokasikan" value={money(unallocatedFunds)} color={colors.warning} /><Metric label="Realisasi disahkan" value={money(approvedRealization)} color={colors.primary} /><Metric label="Serapan" value={`${absorption.toFixed(2)}%`} color={colors.finance} /></View><SectionTitle action={`${budgets.length} periode`}>Ringkasan Anggaran</SectionTitle><ScrollView contentContainerStyle={styles.list}>{budgets.map((item) => <RowCard key={text(item, "id")} onPress={() => router.push(`/budget/${text(item, "id")}`)} icon={<Banknote color={colors.finance} size={22} />} title={text(item, "periodKey")} subtitle={`Sisa alokasi ${money(numberValue(item, "unallocatedFunds"))}`} meta={money(numberValue(item, "totalAllocation"))} status={text(item, "status")} tone="green" />)}</ScrollView>{canCreate ? <ActionButton onPress={() => router.push("/budget/new")}>Buat Alokasi Anggaran</ActionButton> : null}</>}</Screen><BottomNav current="budgets" role={role} /></>;
}

function CategoryBreakdown({ groups, onOpen }: { groups: Group[]; onOpen: () => void }) { return <><SectionTitle action="Ubah rincian">Rincian per Kategori</SectionTitle><ScrollView contentContainerStyle={styles.list}>{groups.map((group) => { const items = group.items ?? []; const allocated = items.reduce((total, item) => total + numberValue(item, "allocatedAmount"), 0); const realized = items.reduce((total, item) => total + numberValue(item, "approvedRealization"), 0); const percent = allocated ? Math.min(100, Math.round((realized / allocated) * 100)) : 0; return <View key={text(group, "id")} style={styles.category}><Text style={styles.categoryTitle}>{text(group, "name")}</Text><Text style={styles.categoryValue}>{money(realized)} dari {money(allocated)}</Text><View style={styles.track}><View style={[styles.progress, { width: `${percent}%` }]} /></View><Text style={styles.categoryMeta}>{percent}% terserap · {items.length} item</Text>{items.map((item) => <RowCard key={text(item, "id")} onPress={onOpen} title={text(item, "name")} subtitle={`Sisa ${money(numberValue(item, "allocatedAmount") - numberValue(item, "approvedRealization"))}`} meta={money(numberValue(item, "allocatedAmount"))} status={numberValue(item, "approvedRealization") ? "Ada realisasi" : "Belum digunakan"} tone={numberValue(item, "approvedRealization") ? "green" : "gray"} />)}</View>; })}</ScrollView></>; }
function History({ realizations, onOpen }: { realizations: Array<Record<string, unknown>>; onOpen: (id: string) => void }) { return <><SectionTitle action={`${realizations.length} data`}>Riwayat Pengajuan</SectionTitle><ScrollView contentContainerStyle={styles.list}>{realizations.map((item) => <RowCard key={text(item, "id")} onPress={() => onOpen(text(item, "id"))} icon={<Banknote color={colors.primary} size={22} />} title={text(item, "description", "Penggunaan dana")} subtitle={money(numberValue(item, "requestedAmount"))} meta={text(item, "createdAt")} status={text(item, "status")} tone={text(item, "status") === "SAH" ? "green" : "orange"} />)}</ScrollView></>; }
function Metric({ label, value, color }: { label: string; value: string; color: string }) { return <View style={styles.metric}><Text style={styles.metricLabel}>{label}</Text><Text style={[styles.metricValue, { color }]}>{value}</Text></View>; }
const styles = StyleSheet.create({ period: { alignItems: "center", backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 10, borderWidth: 1, flexDirection: "row", justifyContent: "space-between", paddingHorizontal: spacing.md }, periodInput: { color: colors.text, fontSize: 12, fontWeight: "800", minWidth: 78, paddingVertical: 10, textAlign: "right" }, masterLink: { alignItems: "center", borderColor: colors.finance, borderRadius: 10, borderWidth: 1, padding: 11 }, masterLinkText: { color: colors.finance, fontSize: 11, fontWeight: "900" }, summary: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 14, borderWidth: 1, gap: 10, padding: spacing.lg }, eyebrow: { color: colors.textMuted, fontSize: 9, fontWeight: "800" }, total: { color: colors.primary, fontSize: 21, fontWeight: "900", marginTop: 2 }, metric: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, metricLabel: { color: colors.textMuted, fontSize: 11 }, metricValue: { fontSize: 12, fontWeight: "900" }, list: { gap: spacing.sm, paddingBottom: 8 }, category: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 13, borderWidth: 1, gap: spacing.sm, padding: spacing.md }, categoryTitle: { color: colors.text, fontSize: 13, fontWeight: "900" }, categoryValue: { color: colors.textMuted, fontSize: 11 }, categoryMeta: { color: colors.textMuted, fontSize: 10 }, track: { backgroundColor: "#E9EDF4", borderRadius: 5, height: 7, overflow: "hidden" }, progress: { backgroundColor: colors.primary, borderRadius: 5, height: 7 } });
