import { useQuery } from "@tanstack/react-query";
import { Banknote } from "lucide-react-native";
import { useRouter } from "expo-router";
import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { useAuth } from "../src/auth";
import { BottomNav, EmptyState, ErrorState, Header, LoadingState, Screen } from "../src/components/Screen";
import { useDateRange } from "../src/date-range-provider";
import { ActionButton, InteractiveTabs, RowCard, SectionTitle } from "../src/components/PimpinanPrimitives";
import { getBudget, getBudgetsFiltered, getRealizationsFiltered } from "../src/lib/api";
import { money } from "../src/lib/format";
import { numberValue, text } from "../src/lib/read";
import { colors, spacing } from "../src/theme";

type Group = Record<string, unknown> & { items?: Array<Record<string, unknown>> };

export default function Budgets() {
  const { role, session } = useAuth();
  const router = useRouter();
  const { range } = useDateRange();
  const periodKey = range.dateFrom.slice(0, 7);
  const [tab, setTab] = useState(0);
  const [selectedBudgetId, setSelectedBudgetId] = useState("");
  const canReadRealizations = session?.permissions.includes("REALIZATION_READ") ?? false;
  const budgetQuery = useQuery({ queryKey: ["budgets", periodKey], queryFn: () => getBudgetsFiltered({ periodKey }), enabled: Boolean(role) });
  const budgets = budgetQuery.data?.budgets ?? [];
  const firstBudgetId = text(budgets[0], "id");
  const activeBudgetId = budgets.some((item) => text(item, "id") === selectedBudgetId) ? selectedBudgetId : firstBudgetId;
  const detailQuery = useQuery({ queryKey: ["budget", activeBudgetId], queryFn: () => getBudget(activeBudgetId), enabled: Boolean(role && activeBudgetId) });
  const realizationQuery = useQuery({ queryKey: ["realizations", periodKey], queryFn: () => getRealizationsFiltered({ periodKey }), enabled: Boolean(role && canReadRealizations && tab === 2) });
  if (!role) return null;

  const realizations = realizationQuery.data?.realizations ?? [];
  const data = detailQuery.data as { groups?: Group[]; summary?: Record<string, unknown> } | undefined;
  const summary = data?.summary ?? {};
  const canCreate = session?.permissions.includes("BUDGET_CREATE") ?? false;
  const canManageCategories = session?.permissions.includes("BUDGET_CATEGORY_MANAGE") ?? false;
  const totalAllocation = numberValue(summary, "totalAllocation") || numberValue(budgets[0], "totalAllocation");
  const availableFunds = numberValue(summary, "availableFunds") || numberValue(budgets[0], "availableFunds");
  const unallocatedFunds = numberValue(summary, "unallocatedFunds") || numberValue(budgets[0], "unallocatedFunds");
  const approvedRealization = numberValue(summary, "approvedRealization") || numberValue(budgets[0], "approvedRealization");
  const absorption = numberValue(summary, "absorptionPercentage") || numberValue(budgets[0], "absorptionPercentage");
  const allocated = Math.max(0, availableFunds - unallocatedFunds);
  const summaryPanel = budgetQuery.isLoading ? <LoadingState /> : budgetQuery.isError ? <ErrorState message="Daftar alokasi anggaran tidak dapat dimuat." onRetry={() => budgetQuery.refetch()} /> : budgets.length ? <><View style={styles.summary}><View style={styles.summaryTop}><View><Text style={styles.eyebrow}>TOTAL ALOKASI</Text><Text style={styles.total}>{money(totalAllocation)}</Text></View><View style={styles.summaryBadge}><Banknote color={colors.finance} size={19} /><Text style={styles.summaryBadgeText}>{text(budgets.find((item) => text(item, "id") === activeBudgetId), "periodKey", periodKey)}</Text></View></View><View style={styles.metricGrid}><Metric label="Sudah dialokasikan" value={money(allocated)} color={colors.success} /><Metric label="Sisa belum dialokasikan" value={money(unallocatedFunds)} color={colors.warning} /><Metric label="Realisasi disahkan" value={money(approvedRealization)} color={colors.primary} /><Metric label="Serapan" value={`${absorption.toFixed(2)}%`} color={colors.finance} /></View></View><SectionTitle action={`${budgets.length} periode`}>Ringkasan Anggaran</SectionTitle><ScrollView contentContainerStyle={styles.list}>{budgets.map((item) => <RowCard key={text(item, "id")} onPress={() => setSelectedBudgetId(text(item, "id"))} icon={<Banknote color={text(item, "id") === activeBudgetId ? colors.primary : colors.finance} size={22} />} title={text(item, "periodKey")} subtitle={`Sisa alokasi ${money(numberValue(item, "unallocatedFunds"))}`} meta={money(numberValue(item, "totalAllocation"))} status={text(item, "status")} tone={text(item, "id") === activeBudgetId ? "blue" : "green"} />)}</ScrollView><Pressable accessibilityRole="button" onPress={() => activeBudgetId && router.push(`/budget/${activeBudgetId}`)} style={({ pressed }) => [styles.detailAction, pressed && styles.pressed]}><Text style={styles.detailActionTitle}>Buka detail periode {text(budgets.find((item) => text(item, "id") === activeBudgetId), "periodKey", periodKey)}</Text><Text style={styles.detailActionHint}>Lihat kategori, lampiran, revisi, dan persetujuan</Text></Pressable>{canCreate ? <ActionButton onPress={() => router.push("/budget/new")}>Buat Alokasi Anggaran</ActionButton> : null}</> : <EmptyState message="Belum ada alokasi anggaran pada rentang tanggal ini." />;
  const detailPanel = detailQuery.isLoading ? <LoadingState /> : detailQuery.isError ? <ErrorState message="Rincian periode tidak dapat dimuat. Daftar anggaran tetap tersedia." onRetry={() => detailQuery.refetch()} /> : <CategoryBreakdown groups={data?.groups ?? []} onOpen={() => activeBudgetId && router.push(`/budget/${activeBudgetId}`)} />;
  const historyPanel = !canReadRealizations ? <EmptyState message="Anda tidak memiliki akses ke riwayat realisasi." /> : realizationQuery.isLoading ? <LoadingState /> : realizationQuery.isError ? <ErrorState message="Riwayat realisasi tidak dapat dimuat." onRetry={() => realizationQuery.refetch()} /> : <History realizations={realizations} onOpen={(id) => router.push(`/realization/${id}`)} />;
  return <><Header role={role} title="Alokasi Anggaran" subtitle="Alokasi per kategori dan realisasi" /><Screen>{canManageCategories ? <Pressable onPress={() => router.push("/budget-categories")} style={styles.masterLink}><Text style={styles.masterLinkText}>Kelola kategori dan subkategori anggaran</Text></Pressable> : null}<InteractiveTabs active={tab} items={["Ringkasan", "Per Kategori", "Riwayat"]} onChange={setTab} panels={{ 0: summaryPanel, 1: detailPanel, 2: historyPanel }} /></Screen><BottomNav current="budgets" role={role} /></>;
}

function CategoryBreakdown({ groups, onOpen }: { groups: Group[]; onOpen: () => void }) { if (!groups.length) return <EmptyState message="Belum ada rincian kategori anggaran." />; return <><SectionTitle action="Buka periode">Rincian per Kategori</SectionTitle><ScrollView contentContainerStyle={styles.list}>{groups.map((group) => { const items = group.items ?? []; const allocated = items.reduce((total, item) => total + numberValue(item, "allocatedAmount"), 0); const realized = items.reduce((total, item) => total + numberValue(item, "approvedRealization"), 0); const percent = allocated ? Math.min(100, Math.round((realized / allocated) * 100)) : 0; return <View key={text(group, "id")} style={styles.category}><Text style={styles.categoryTitle}>{text(group, "name")}</Text><Text style={styles.categoryValue}>{money(realized)} dari {money(allocated)}</Text><View style={styles.track}><View style={[styles.progress, { width: `${percent}%` }]} /></View><Text style={styles.categoryMeta}>{percent}% terserap · {items.length} item</Text>{items.map((item) => <RowCard key={text(item, "id")} onPress={onOpen} title={text(item, "name")} subtitle={`Sisa ${money(numberValue(item, "allocatedAmount") - numberValue(item, "approvedRealization"))}`} meta={money(numberValue(item, "allocatedAmount"))} status={numberValue(item, "approvedRealization") ? "Ada realisasi" : "Belum digunakan"} tone={numberValue(item, "approvedRealization") ? "green" : "gray"} />)}</View>; })}</ScrollView></>; }
function History({ realizations, onOpen }: { realizations: Array<Record<string, unknown>>; onOpen: (id: string) => void }) { if (!realizations.length) return <EmptyState message="Belum ada riwayat realisasi pada rentang tanggal ini." />; return <><SectionTitle action={`${realizations.length} data`}>Riwayat Penggunaan Dana</SectionTitle><ScrollView contentContainerStyle={styles.list}>{realizations.map((item) => <RowCard key={text(item, "id")} onPress={() => onOpen(text(item, "id"))} icon={<Banknote color={colors.primary} size={22} />} title={text(item, "description", "Penggunaan dana")} subtitle={money(numberValue(item, "requestedAmount"))} meta={text(item, "createdAt")} status={text(item, "status")} tone={text(item, "status") === "SAH" ? "green" : "orange"} />)}</ScrollView></>; }
function Metric({ label, value, color }: { label: string; value: string; color: string }) { return <View style={styles.metric}><Text style={styles.metricLabel}>{label}</Text><Text style={[styles.metricValue, { color }]}>{value}</Text></View>; }
const styles = StyleSheet.create({ masterLink: { alignItems: "center", backgroundColor: colors.financeSoft, borderColor: colors.finance, borderRadius: 14, borderWidth: 1, minHeight: 48, justifyContent: "center", paddingHorizontal: spacing.md }, masterLinkText: { color: colors.finance, fontSize: 11, fontWeight: "900" }, summary: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 22, borderWidth: 1, elevation: 2, gap: 14, padding: spacing.lg, shadowColor: colors.ink, shadowOpacity: 0.06, shadowRadius: 12, shadowOffset: { width: 0, height: 5 } }, summaryTop: { alignItems: "flex-start", flexDirection: "row", justifyContent: "space-between" }, summaryBadge: { alignItems: "center", backgroundColor: colors.financeSoft, borderRadius: 14, flexDirection: "row", gap: 5, maxWidth: 130, paddingHorizontal: 9, paddingVertical: 7 }, summaryBadgeText: { color: colors.finance, fontSize: 10, fontWeight: "900" }, eyebrow: { color: colors.textMuted, fontSize: 9, fontWeight: "800", letterSpacing: 0.6 }, total: { color: colors.primary, fontSize: 24, fontWeight: "900", marginTop: 2 }, metricGrid: { gap: 8 }, metric: { alignItems: "center", borderTopColor: colors.border, borderTopWidth: StyleSheet.hairlineWidth, flexDirection: "row", justifyContent: "space-between", paddingTop: 8 }, metricLabel: { color: colors.textMuted, fontSize: 11 }, metricValue: { fontSize: 12, fontWeight: "900" }, list: { gap: spacing.sm, paddingBottom: 8 }, detailAction: { backgroundColor: colors.primarySoft, borderColor: colors.primary, borderRadius: 16, borderWidth: 1, gap: 4, padding: spacing.md }, detailActionTitle: { color: colors.primaryDark, fontSize: 12, fontWeight: "900" }, detailActionHint: { color: colors.textMuted, fontSize: 10 }, pressed: { opacity: 0.76 }, category: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 16, borderWidth: 1, gap: spacing.sm, padding: spacing.md }, categoryTitle: { color: colors.text, fontSize: 13, fontWeight: "900" }, categoryValue: { color: colors.textMuted, fontSize: 11 }, categoryMeta: { color: colors.textMuted, fontSize: 10 }, track: { backgroundColor: "#E9EDF4", borderRadius: 5, height: 7, overflow: "hidden" }, progress: { backgroundColor: colors.primary, borderRadius: 5, height: 7 } });
