import { useQuery } from "@tanstack/react-query";
import { AlertTriangle, Bell, HardHat, MapPinned } from "lucide-react-native";
import { Text, View } from "react-native";

import { useAuth } from "../src/auth";
import { BottomNav, EmptyState, ErrorState, Header, LoadingState, Screen } from "../src/components/Screen";
import { getBusinessPortalSummary } from "../src/lib/api";
import { money } from "../src/lib/format";
import { displayStatus } from "../src/lib/read";
import { colors } from "../src/theme";

export default function BusinessPortal() {
  const { role } = useAuth();
  const query = useQuery({ queryKey: ["business-portal"], queryFn: getBusinessPortalSummary, enabled: role === "PENGUSAHA", refetchOnMount: "always" });
  if (role !== "PENGUSAHA") return null;
  if (query.isLoading && !query.data) return <><Header role={role} title="Iuran Usaha" subtitle="Kewajiban dan informasi tertaut" /><Screen withBottomNav={false}><LoadingState /></Screen></>;
  if (query.isError || !query.data) return <><Header role={role} title="Iuran Usaha" subtitle="Kewajiban dan informasi tertaut" /><Screen><ErrorState message="Data iuran usaha belum dapat dimuat." error={query.error} onRetry={() => query.refetch()} /></Screen><BottomNav current="business-portal" role={role} /></>;
  const data = query.data as Record<string, unknown>; const dues = (data.dues ?? {}) as Record<string, unknown>; const units = Array.isArray(data.units) ? data.units as Array<Record<string, unknown>> : []; const blocks = Array.isArray(data.blocks) ? data.blocks as Array<Record<string, unknown>> : []; const information = Array.isArray(data.information) ? data.information as Array<Record<string, unknown>> : [];
  return <><Header role={role} title="Iuran Usaha" subtitle="Kewajiban dan informasi tertaut" /><Screen refreshing={query.isRefetching} onRefresh={() => query.refetch()}><View style={styles.guide}><Text style={styles.title}>Cara menggunakan</Text><Text style={styles.meta}>1. Periksa sisa tagihan dan unit terkait.</Text><Text style={styles.meta}>2. Setorkan iuran sesuai jumlah yang tampil.</Text><Text style={styles.meta}>3. Tunggu konfirmasi Bendahara; status akan diperbarui otomatis.</Text></View><View style={styles.card}><Text style={styles.label}>SISA TAGIHAN</Text><Text style={styles.total}>{money(Number(dues.remainingTotal ?? 0))}</Text><Text style={styles.meta}>Kewajiban {money(Number(dues.obligationTotal ?? 0))} · Diterima {money(Number(dues.receivedTotal ?? 0))}</Text></View><View style={styles.card}><Text style={styles.title}>Unit dan blok terkait</Text><View style={styles.metricRow}><MapPinned color={colors.primary} size={18} /><Text style={styles.meta}>{blocks.length} blok</Text><HardHat color={colors.warning} size={18} /><Text style={styles.meta}>{units.length} unit</Text></View></View><Text style={styles.title}>Pemberitahuan</Text>{information.length ? information.slice(0, 10).map((item, index) => <View key={String(item.id ?? index)} style={styles.notice}><Bell color={colors.primary} size={18} /><View style={styles.noticeCopy}><Text style={styles.noticeTitle}>{displayStatus(String(item.category ?? "Informasi"))} · {displayStatus(String(item.priority ?? "LOW"))}</Text><Text style={styles.meta}>{String(item.description ?? "Pemberitahuan baru")}</Text></View></View>) : <EmptyState message="Belum ada pemberitahuan terkait usaha Anda." />}<View style={styles.reminder}><AlertTriangle color={colors.warning} size={18} /><Text style={styles.meta}>Jika terdapat tunggakan, lakukan penyetoran dan tunggu konfirmasi Bendahara.</Text></View></Screen><BottomNav current="business-portal" role={role} /></>;
}

const styles = { guide: { backgroundColor: colors.primarySoft, borderColor: colors.border, borderRadius: 14, borderWidth: 1, gap: 4, padding: 12 }, card: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 16, borderWidth: 1, gap: 8, padding: 16 }, label: { color: colors.textMuted, fontSize: 11, fontWeight: "800" as const }, total: { color: colors.primary, fontSize: 28, fontWeight: "900" as const }, title: { color: colors.text, fontSize: 16, fontWeight: "900" as const }, meta: { color: colors.textMuted, flex: 1, fontSize: 12, lineHeight: 18 }, metricRow: { alignItems: "center" as const, flexDirection: "row" as const, gap: 8 }, notice: { alignItems: "flex-start" as const, backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 14, borderWidth: 1, flexDirection: "row" as const, gap: 10, padding: 12 }, noticeCopy: { flex: 1, gap: 3 }, noticeTitle: { color: colors.text, fontSize: 12, fontWeight: "900" as const }, reminder: { alignItems: "center" as const, backgroundColor: colors.warningSoft, borderRadius: 12, flexDirection: "row" as const, gap: 8, padding: 12 } };
