import { useQuery } from "@tanstack/react-query";
import { HardHat, Search } from "lucide-react-native";
import { useMemo, useState } from "react";
import { useRouter } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { useAuth } from "../src/auth";
import { BottomNav, ErrorState, Header, LoadingState, Screen } from "../src/components/Screen";
import { InteractiveTabs, RowCard, SectionTitle } from "../src/components/PimpinanPrimitives";
import { SelectField } from "../src/components/NativeForm";
import { getBlocks, getExcavators } from "../src/lib/api";
import { text } from "../src/lib/read";
import { colors, spacing } from "../src/theme";

export default function Excavators() {
  const { role, session } = useAuth(); const router = useRouter(); const [search, setSearch] = useState(""); const [operatorName, setOperatorName] = useState(""); const [blockId, setBlockId] = useState(""); const [statusTab, setStatusTab] = useState(0); const status = statusTab === 1 ? "ACTIVE" : statusTab === 2 ? "INACTIVE" : statusTab === 3 ? "EXITED" : ""; const filters = useMemo(() => ({ ...(search ? { search } : {}), ...(operatorName ? { operatorName } : {}), ...(blockId ? { blockId } : {}), ...(status ? { status } : {}) }), [blockId, operatorName, search, status]); const query = useQuery({ queryKey: ["excavators", filters], queryFn: () => getExcavators(filters), enabled: Boolean(role) }); const summary = useQuery({ queryKey: ["excavators", "summary"], queryFn: () => getExcavators(), enabled: Boolean(role) }); const blocks = useQuery({ queryKey: ["blocks", "excavator-filter"], queryFn: () => getBlocks(), enabled: Boolean(role) });
  if (!role) return null;
  const canManage = session?.permissions.includes("EXCAVATOR_MANAGE");
  const allUnits = summary.data?.excavators ?? []; const activeCount = allUnits.filter((item) => text(item, "status") === "ACTIVE").length;
  return <><Header role={role} title="Excavator per Unit" subtitle="Armada yang beroperasi di blok" /><Screen scroll={false}><InteractiveTabs active={statusTab} items={[`Semua (${allUnits.length})`, `Aktif (${activeCount})`, "Tidak Aktif", "Keluar"]} onChange={setStatusTab} /><View style={styles.search}><Search color={colors.textMuted} size={17} /><TextInput onChangeText={setSearch} placeholder="Cari unit atau merek" placeholderTextColor={colors.textMuted} style={styles.input} value={search} /></View><TextInput onChangeText={setOperatorName} placeholder="Filter operator" placeholderTextColor={colors.textMuted} style={styles.operator} value={operatorName} /><SelectField label="Blok" value={blockId} options={[{ label: "Semua blok", value: "" }, ...(blocks.data?.blocks ?? []).map((block) => ({ label: `${block.code} · ${block.name}`, value: block.id }))]} onChange={setBlockId} /><SectionTitle action={`${query.data?.excavators.length ?? 0} unit`}>Daftar Excavator</SectionTitle>{query.isLoading ? <LoadingState /> : query.isError ? <ErrorState message="Data excavator tidak dapat dimuat." onRetry={() => query.refetch()} /> : <FlatList contentContainerStyle={styles.list} data={query.data?.excavators ?? []} keyExtractor={(item) => text(item, "id")} onRefresh={() => query.refetch()} refreshing={query.isRefetching} renderItem={({ item }) => <RowCard onPress={() => router.push(`/excavator/${text(item, "id")}`)} icon={<HardHat color={colors.warning} size={24} />} meta={`Masuk: ${text(item, "currentEntryDate")} · ${text(item, "currentBlockCode", "Belum ditempatkan")}`} status={text(item, "status")} title={text(item, "unitCode")} subtitle={`${text(item, "brand")} ${text(item, "model")} · Operator: ${text(item, "operatorName")}`} tone={text(item, "status") === "ACTIVE" ? "green" : "gray"} />} ListFooterComponent={canManage ? <Pressable onPress={() => router.push("/excavator/new")} style={styles.add}><Text style={styles.addText}>+ Tambah Excavator</Text></Pressable> : null} />}</Screen><BottomNav current="excavators" role={role} /></>;
}
const styles = StyleSheet.create({ search: { alignItems: "center", backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 10, borderWidth: 1, flexDirection: "row", gap: 8, paddingHorizontal: 12 }, input: { color: colors.text, flex: 1, height: 44, fontSize: 12 }, operator: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 10, borderWidth: 1, color: colors.text, height: 42, paddingHorizontal: 12 }, list: { gap: spacing.sm, paddingTop: spacing.sm, paddingBottom: 90 }, add: { alignItems: "center", backgroundColor: colors.primary, borderRadius: 10, marginTop: spacing.sm, padding: 14 }, addText: { color: "#FFFFFF", fontSize: 12, fontWeight: "900" } });
