import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { AppAlert as Alert } from "../src/lib/feedback";

import { useAuth } from "../src/auth";
import { BottomNav, EmptyState, ErrorState, Header, LoadingState, Screen } from "../src/components/Screen";
import { SelectField, SubmitButton, TextInputField } from "../src/components/NativeForm";
import { createFinanceCategory, getFinanceCategories, updateFinanceCategory } from "../src/lib/api";
import { text } from "../src/lib/read";
import { colors, spacing } from "../src/theme";
import { financeCategoryFormSchema } from "../src/form-schemas";

export default function FinanceCategories() {
  const { role, session } = useAuth(); const client = useQueryClient(); const [editingId, setEditingId] = useState(""); const [name, setName] = useState(""); const [transactionType, setTransactionType] = useState("CASH_OUT"); const [sortOrder, setSortOrder] = useState("0"); const [saving, setSaving] = useState(false); const [errors, setErrors] = useState<Record<string, string>>({});
  const query = useQuery({ queryKey: ["finance-categories", "all"], queryFn: () => getFinanceCategories({ includeInactive: "true" }), enabled: Boolean(role) });
  if (!role) return null;
  const canManage = session?.permissions.includes("FINANCE_CATEGORY_MANAGE") ?? false;
  function reset() { setEditingId(""); setName(""); setTransactionType("CASH_OUT"); setSortOrder("0"); setErrors({}); }
  async function save() { const parsed = financeCategoryFormSchema.safeParse({ name, transactionType, sortOrder }); const nextErrors: Record<string, string> = {}; if (!parsed.success) parsed.error.issues.forEach((issue) => { const key = String(issue.path[0] ?? "form"); if (!nextErrors[key]) nextErrors[key] = issue.message; }); setErrors(nextErrors); if (!parsed.success) return Alert.alert("Periksa data kategori", parsed.error.issues[0]?.message ?? "Lengkapi nama, jenis, dan urutan."); setSaving(true); try { if (editingId) await updateFinanceCategory({ id: editingId, ...parsed.data, isActive: true }); else await createFinanceCategory(parsed.data); reset(); await client.invalidateQueries({ queryKey: ["finance-categories"] }); } catch (error) { Alert.alert("Tidak dapat menyimpan", error instanceof Error ? error.message : "Periksa data dan koneksi lalu coba lagi."); } finally { setSaving(false); } }
  async function deactivate(item: Record<string, unknown>) { if (saving) return; setSaving(true); try { await updateFinanceCategory({ id: text(item, "id"), name: text(item, "name"), transactionType: text(item, "transactionType"), sortOrder: Number(item.sortOrder ?? 0), isActive: !Boolean(item.isActive) }); await client.invalidateQueries({ queryKey: ["finance-categories"] }); } catch (error) { Alert.alert("Tidak dapat memperbarui", error instanceof Error ? error.message : "Coba lagi."); } finally { setSaving(false); } }
  function edit(item: Record<string, unknown>) { setEditingId(text(item, "id")); setName(text(item, "name")); setTransactionType(text(item, "transactionType", "CASH_OUT")); setSortOrder(String(item.sortOrder ?? 0)); }
  return <><Header role={role} title="Kategori Keuangan" subtitle="Kelola klasifikasi pemasukan dan pengeluaran" /><Screen>{canManage ? <View style={styles.form}><TextInputField label="Nama kategori" required error={errors.name} value={name} onChange={(value) => { setName(value); setErrors((current) => ({ ...current, name: "" })); }} placeholder="Contoh: Operasional" /><SelectField label="Jenis" required value={transactionType} onChange={setTransactionType} options={[{ label: "Pemasukan", value: "CASH_IN" }, { label: "Pengeluaran", value: "CASH_OUT" }]} /><TextInputField label="Urutan" required error={errors.sortOrder} value={sortOrder} onChange={(value) => { setSortOrder(value); setErrors((current) => ({ ...current, sortOrder: "" })); }} keyboardType="numeric" placeholder="0 sampai 10.000" /><SubmitButton label={editingId ? "Simpan Perubahan" : "Tambah Kategori"} loading={saving} onPress={() => void save()} />{editingId ? <Pressable onPress={reset}><Text style={styles.cancel}>Batal ubah</Text></Pressable> : null}</View> : null}{query.isLoading ? <LoadingState /> : query.isError ? <ErrorState message="Kategori tidak dapat dimuat." onRetry={() => query.refetch()} /> : query.data?.categories.length ? query.data.categories.map((item) => <Pressable key={text(item, "id")} onPress={() => canManage && edit(item)} style={styles.item}><View><Text style={styles.name}>{text(item, "name")}</Text><Text style={styles.meta}>{text(item, "transactionType")} · Urutan {text(item, "sortOrder", "0")}</Text></View>{canManage ? <Pressable onPress={() => void deactivate(item)}><Text style={Boolean(item.isActive) ? styles.deactivate : styles.activate}>{Boolean(item.isActive) ? "Nonaktifkan" : "Aktifkan"}</Text></Pressable> : null}</Pressable>) : <EmptyState message="Belum ada kategori keuangan." />}</Screen><BottomNav current="finance" role={role} /></>;
}
const styles = StyleSheet.create({ form: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 13, borderWidth: 1, gap: spacing.sm, padding: spacing.md }, input: { borderColor: colors.border, borderRadius: 10, borderWidth: 1, color: colors.text, minHeight: 44, paddingHorizontal: 12 }, cancel: { color: colors.textMuted, fontSize: 11, textAlign: "center" }, item: { alignItems: "center", backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 12, borderWidth: 1, flexDirection: "row", justifyContent: "space-between", padding: spacing.md }, name: { color: colors.text, fontSize: 13, fontWeight: "900" }, meta: { color: colors.textMuted, fontSize: 10, marginTop: 3 }, deactivate: { color: colors.danger, fontSize: 10, fontWeight: "900" }, activate: { color: colors.success, fontSize: 10, fontWeight: "900" } });
