import { useQuery } from "@tanstack/react-query";
import { ReceiptText, Search, WalletCards } from "lucide-react-native";
import { useRouter } from "expo-router";
import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import { useAuth } from "../src/auth";
import { BottomNav, EmptyState, ErrorState, Header, LoadingState, Screen } from "../src/components/Screen";
import { useDateRange } from "../src/date-range-provider";
import { ActionButton, InteractiveTabs, RowCard, SectionTitle } from "../src/components/PimpinanPrimitives";
import { getBlocks, getDuePaymentsFiltered, getDuesFiltered, getFinanceSummary, getTransactionsFiltered } from "../src/lib/api";
import { money } from "../src/lib/format";
import { numberValue, text } from "../src/lib/read";
import { colors, spacing } from "../src/theme";

type DueStatus = "" | "UNPAID" | "PARTIAL" | "PAID";

export default function Finance() {
  const { role, session } = useAuth(); const router = useRouter(); const { range } = useDateRange(); const periodKey = range.dateFrom.slice(0, 7); const [tab, setTab] = useState(0); const [query, setQuery] = useState(""); const [blockId, setBlockId] = useState(""); const [dueStatus, setDueStatus] = useState<DueStatus>(""); const bendahara = role === "BENDAHARA";
  const isPaymentTab = !bendahara && tab === 2; const isArrearsTab = !bendahara && tab === 3; const isTransactionTab = bendahara && tab >= 2; const dueType = tab === 1 ? "ROAD_ENTRY" : "MONTHLY"; const transactionType = bendahara ? tab === 2 ? "CASH_IN" : "CASH_OUT" : "";
  const dueFilters = { periodKey, dueType, ...(dueStatus ? { status: dueStatus } : {}), ...(blockId ? { blockId } : {}), ...(query.trim() ? { query: query.trim() } : {}), ...(isArrearsTab ? { overdueOnly: "true" } : {}) };
  const duesQuery = useQuery({ queryKey: ["dues", dueFilters], queryFn: () => getDuesFiltered(dueFilters), enabled: Boolean(role && !isTransactionTab && !isPaymentTab) });
  const paymentQuery = useQuery({ queryKey: ["due-payments", periodKey, blockId, query], queryFn: () => getDuePaymentsFiltered({ periodKey, ...(blockId ? { blockId } : {}), ...(query.trim() ? { query: query.trim() } : {}) }), enabled: Boolean(role && isPaymentTab) });
  const transactionsQuery = useQuery({ queryKey: ["transactions", periodKey, transactionType, query], queryFn: () => getTransactionsFiltered({ periodKey, ...(transactionType ? { transactionType } : {}), ...(query.trim() ? { query: query.trim() } : {}) }), enabled: Boolean(role && isTransactionTab) });
  const summaryQuery = useQuery({ queryKey: ["finance-summary"], queryFn: getFinanceSummary, enabled: Boolean(role) }); const blocksQuery = useQuery({ queryKey: ["blocks", "finance-filter"], queryFn: () => getBlocks(), enabled: Boolean(role) });
  if (!role) return null;
  const rows = duesQuery.data?.dues ?? []; const payments = paymentQuery.data?.payments ?? []; const transactions = transactionsQuery.data?.transactions ?? []; const totals = rows.reduce<{ due: number; paid: number }>((acc, row) => ({ due: acc.due + numberValue(row, "amountDue"), paid: acc.paid + numberValue(row, "amountPaid") }), { due: 0, paid: 0 }); const summary = summaryQuery.data?.summary;
  const loading = isTransactionTab ? transactionsQuery.isLoading : isPaymentTab ? paymentQuery.isLoading : duesQuery.isLoading; const failed = isTransactionTab ? transactionsQuery.isError : isPaymentTab ? paymentQuery.isError : duesQuery.isError; const tabs = bendahara ? ["Iuran Bulanan", "Iuran Jalan", "Transaksi Masuk", "Transaksi Keluar"] : ["Iuran Bulanan", "Iuran Jalan", "Pembayaran", "Tunggakan"];
  return <><Header role={role} title="Keuangan – Iuran" subtitle="Iuran, pembayaran, dan arus kas" /><Screen><InteractiveTabs active={tab} items={tabs} onChange={(index) => { setTab(index); setQuery(""); setDueStatus(""); }} />{summary ? <View style={styles.balance}><WalletCards color={colors.finance} size={18} /><View><Text style={styles.balanceLabel}>SALDO KAS TERVERIFIKASI</Text><Text style={styles.balanceValue}>{money(numberValue(summary, "cashBalance"))}</Text></View></View> : null}<View style={styles.searchRow}><Search color={colors.textMuted} size={17} /><TextInput value={query} onChangeText={setQuery} placeholder={isTransactionTab ? "Cari kode atau uraian transaksi" : isPaymentTab ? "Cari pembayaran" : "Cari pembayar atau referensi"} style={styles.search} /></View>{!isTransactionTab && !isPaymentTab ? <><BlockFilter blocks={blocksQuery.data?.blocks ?? []} active={blockId} onChange={setBlockId} />{!isArrearsTab ? <FilterTabs active={dueStatus} onChange={setDueStatus} /> : null}</> : null}{failed ? <ErrorState message="Data keuangan tidak dapat dimuat." onRetry={() => { void duesQuery.refetch(); void paymentQuery.refetch(); void transactionsQuery.refetch(); }} /> : loading ? <LoadingState /> : isTransactionTab ? <TransactionList rows={transactions} onOpen={(id) => router.push(`/transaction/${id}`)} /> : isPaymentTab ? <PaymentList rows={payments} onOpen={(id) => router.push(`/due/${id}`)} /> : rows.length ? <><View style={styles.summary}><SectionTitle>{isArrearsTab ? "Tunggakan lewat jatuh tempo" : `Ringkasan ${periodKey}`}</SectionTitle><Metric label="Kewajiban" value={money(totals.due)} color={colors.primary} /><Metric label="Diterima" value={money(totals.paid)} color={colors.success} /><Metric label="Tunggakan" value={money(totals.due - totals.paid)} color={colors.danger} /></View><SectionTitle action={`${rows.length} data`}>Daftar iuran</SectionTitle><ScrollView contentContainerStyle={styles.list}>{rows.map((item) => <RowCard key={text(item, "id")} onPress={() => router.push(`/due/${text(item, "id")}`)} icon={<ReceiptText color={colors.primary} size={22} />} meta={text(item, "dueDate")} status={text(item, "status")} title={text(item, "payerName")} subtitle={`${money(numberValue(item, "amountDue"))} · ${text(item, "dueType")}`} tone={text(item, "status") === "PAID" ? "green" : "orange"} />)}</ScrollView></> : <EmptyState message={isArrearsTab ? "Tidak ada tunggakan lewat jatuh tempo." : "Tidak ada iuran pada filter ini."} />}{bendahara && tab === 0 ? <ActionButton onPress={() => router.push("/due/new")}>Buat Iuran Bulanan</ActionButton> : null}{bendahara && tab >= 2 ? <ActionButton onPress={() => router.push("/transaction/new")}>Catat Transaksi</ActionButton> : null}{session?.permissions.includes("FINANCE_CATEGORY_MANAGE") ? <Pressable onPress={() => router.push("/finance-categories")}><Text style={styles.categories}>Kelola kategori keuangan</Text></Pressable> : null}</Screen><BottomNav current="finance" role={role} /></>;
}
function FilterTabs({ active, onChange }: { active: DueStatus; onChange: (value: DueStatus) => void }) { const items: { label: string; value: DueStatus }[] = [{ label: "Semua", value: "" }, { label: "Belum Lunas", value: "UNPAID" }, { label: "Sebagian", value: "PARTIAL" }, { label: "Lunas", value: "PAID" }]; return <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filterTabs}>{items.map((item) => <Pressable key={item.label} onPress={() => onChange(item.value)} style={[styles.filter, active === item.value && styles.filterActive]}><Text style={[styles.filterText, active === item.value && styles.filterTextActive]}>{item.label}</Text></Pressable>)}</ScrollView>; }
function BlockFilter({ blocks, active, onChange }: { blocks: Array<{ id: string; code: string }>; active: string; onChange: (id: string) => void }) { return <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filterTabs}>{[{ id: "", code: "Semua Blok" }, ...blocks].map((block) => <Pressable key={block.id || "all"} onPress={() => onChange(block.id)} style={[styles.filter, active === block.id && styles.filterActive]}><Text style={[styles.filterText, active === block.id && styles.filterTextActive]}>{block.code}</Text></Pressable>)}</ScrollView>; }
function TransactionList({ rows, onOpen }: { rows: Array<Record<string, unknown>>; onOpen: (id: string) => void }) { return <><SectionTitle action={`${rows.length} transaksi`}>Arus Kas</SectionTitle><ScrollView contentContainerStyle={styles.list}>{rows.map((item) => <RowCard key={text(item, "id")} onPress={() => onOpen(text(item, "id"))} icon={<ReceiptText color={text(item, "transactionType") === "CASH_IN" ? colors.success : colors.primary} size={22} />} meta={text(item, "transactionAt")} status={text(item, "status")} title={text(item, "description", text(item, "transactionType", "Transaksi keuangan"))} subtitle={money(numberValue(item, "amount"))} tone={text(item, "status") === "REVERSED" ? "gray" : text(item, "transactionType") === "CASH_IN" ? "green" : "blue"} />)}</ScrollView></>; }
function PaymentList({ rows, onOpen }: { rows: Array<Record<string, unknown>>; onOpen: (id: string) => void }) { return <><SectionTitle action={`${rows.length} pembayaran`}>Daftar Pembayaran</SectionTitle><ScrollView contentContainerStyle={styles.list}>{rows.map((item) => { const due = item.due as Record<string, unknown> | undefined; return <RowCard key={text(item, "id")} onPress={() => due && onOpen(text(due, "id"))} icon={<ReceiptText color={colors.success} size={22} />} meta={text(item, "paymentDate")} status={text(item, "cashStatus", "SAH")} title={text(item, "payerName")} subtitle={`${money(numberValue(item, "amount"))} · ${text(due, "referenceKey")}`} tone="green" />; })}</ScrollView></>; }
function Metric({ label, value, color }: { label: string; value: string; color: string }) { return <View style={styles.metric}><Text style={styles.metricLabel}>{label}</Text><Text style={[styles.metricValue, { color }]}>{value}</Text></View>; }
const styles = StyleSheet.create({ period: { alignItems: "center", backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 10, borderWidth: 1, flexDirection: "row", justifyContent: "space-between", paddingHorizontal: spacing.md }, periodLabel: { color: colors.textMuted, fontSize: 10, fontWeight: "800" }, periodInput: { color: colors.text, fontSize: 12, fontWeight: "800", minWidth: 78, paddingVertical: 10, textAlign: "right" }, balance: { alignItems: "center", backgroundColor: "#EDF8F0", borderColor: "#BCE0C4", borderRadius: 12, borderWidth: 1, flexDirection: "row", gap: 10, padding: spacing.md }, balanceLabel: { color: colors.textMuted, fontSize: 9, fontWeight: "900" }, balanceValue: { color: colors.finance, fontSize: 16, fontWeight: "900", marginTop: 2 }, searchRow: { alignItems: "center", backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 10, borderWidth: 1, flexDirection: "row", gap: 8, paddingHorizontal: 11 }, search: { color: colors.text, flex: 1, fontSize: 12, paddingVertical: 11 }, filterTabs: { gap: 7 }, filter: { borderColor: colors.border, borderRadius: 16, borderWidth: 1, paddingHorizontal: 11, paddingVertical: 7 }, filterActive: { backgroundColor: "#EAF1FF", borderColor: colors.primary }, filterText: { color: colors.textMuted, fontSize: 10, fontWeight: "800" }, filterTextActive: { color: colors.primary }, summary: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 14, borderWidth: 1, gap: 9, padding: spacing.md }, metric: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, metricLabel: { color: colors.textMuted, fontSize: 11 }, metricValue: { fontSize: 12, fontWeight: "800" }, categories: { color: colors.primary, fontSize: 12, fontWeight: "900", textAlign: "center" }, list: { gap: spacing.sm, paddingBottom: 8 } });
