import { useQuery } from "@tanstack/react-query";
import { SlidersHorizontal, TrendingUp } from "lucide-react-native";
import { useRouter } from "expo-router";
import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { TextInput } from "../src/components/ui/TextInput";

import { useAuth } from "../src/auth";
import { BottomNav, EmptyState, ErrorState, Header, LoadingState, Screen } from "../src/components/Screen";
import { useDateRange } from "../src/date-range-provider";
import { SelectField } from "../src/components/NativeForm";
import { ActionButton, InteractiveTabs, RowCard, SectionTitle } from "../src/components/PimpinanPrimitives";
import { getBudget, getBudgetCategories, getBudgetsFiltered, getRealizationsFiltered } from "../src/lib/api";
import { money } from "../src/lib/format";
import { numberValue, text } from "../src/lib/read";
import { colors, spacing } from "../src/theme";

type Group = Record<string, unknown> & { items?: Array<Record<string, unknown>> };
const workflowStatuses = ["", "DRAFT", "SUBMITTED", "VERIFIED", "SAH", "REVISION_REQUIRED", "REJECTED", "REVERSED"];
const workflowLabels = ["Semua", "Draft", "Diajukan", "Verifikasi", "Sah", "Revisi", "Ditolak", "Dibalikkan"];

function tone(status: string): "green" | "red" | "orange" | "blue" | "gray" { if (status === "SAH") return "green"; if (status === "REJECTED") return "red"; if (status === "REVERSED" || status === "CANCELLED") return "gray"; if (status === "VERIFIED") return "blue"; return "orange"; }

export default function Realizations() {
  const { role, session } = useAuth(); const router = useRouter(); const { range } = useDateRange(); const periodKey = range.dateFrom.slice(0, 7); const [section, setSection] = useState(0); const [statusIndex, setStatusIndex] = useState(0); const [query, setQuery] = useState(""); const [filtersOpen, setFiltersOpen] = useState(false); const [categoryId, setCategoryId] = useState("");
  const categories = useQuery({ queryKey: ["budget-categories", "realization-filter"], queryFn: () => getBudgetCategories(), enabled: Boolean(role) });
  const list = useQuery({ queryKey: ["realizations", periodKey, workflowStatuses[statusIndex], query, categoryId], queryFn: () => getRealizationsFiltered({ periodKey, status: workflowStatuses[statusIndex], query: query.trim(), categoryId }), enabled: Boolean(role && section === 0) });
  const budgets = useQuery({ queryKey: ["budgets", "realization-category", periodKey], queryFn: () => getBudgetsFiltered({ periodKey }), enabled: Boolean(role && section === 1) });
  const budgetId = text(budgets.data?.budgets?.[0], "id"); const budget = useQuery({ queryKey: ["budget", "realization-category", budgetId], queryFn: () => getBudget(budgetId), enabled: Boolean(role && section === 1 && budgetId) });
  if (!role) return null;
  const canCreate = session?.permissions.includes("REALIZATION_CREATE") ?? false; const rows = list.data?.realizations ?? []; const statusCounts = list.data?.statusCounts ?? {}; const categoryOptions = [{ label: "Semua kategori", value: "" }, ...(categories.data?.categories ?? []).map((item) => ({ label: text(item, "name"), value: text(item, "id") }))]; const detail = budget.data as { summary?: Record<string, unknown>; groups?: Group[] } | undefined;
  return <><Header role={role} title="Realisasi & Laporan" subtitle="Serapan, bukti, dan persetujuan penggunaan dana" /><Screen><InteractiveTabs active={section} items={["Realisasi", "Per Kategori", "Laporan"]} onChange={(index) => index === 2 ? router.push("/reports") : setSection(index)} />{section === 0 ? <><InteractiveTabs active={statusIndex} items={workflowLabels.map((label, index) => `${label}${workflowStatuses[index] ? ` (${statusCounts[workflowStatuses[index]] ?? 0})` : ""}`)} onChange={setStatusIndex} /><View style={styles.searchRow}><TextInput value={query} onChangeText={setQuery} placeholder="Cari kegiatan, bukti, atau item" placeholderTextColor={colors.textMuted} style={styles.search} /><Pressable onPress={() => setFiltersOpen((value) => !value)} style={[styles.filter, filtersOpen && styles.filterActive]}><SlidersHorizontal color={filtersOpen ? "#FFFFFF" : colors.primary} size={17} /></Pressable></View>{filtersOpen ? <View style={styles.filters}><SelectField label="Kategori anggaran" value={categoryId} options={categoryOptions} onChange={setCategoryId} /></View> : null}{list.isLoading ? <LoadingState /> : list.isError ? <ErrorState message="Realisasi tidak dapat dimuat." onRetry={() => list.refetch()} /> : rows.length ? <ScrollView contentContainerStyle={styles.list}>{rows.map((row) => { const status = text(row, "status"); return <RowCard key={text(row, "id")} onPress={() => router.push(`/realization/${text(row, "id")}`)} icon={<TrendingUp color={colors.success} size={21} />} title={text(row, "activity", text(row, "description", "Realisasi"))} subtitle={`${text(row, "budgetItemName")} · ${text(row, "realizationDate", text(row, "createdAt"))}`} meta={money(numberValue(row, "requestedAmount"))} status={status} tone={tone(status)} />; })}</ScrollView> : <EmptyState message="Belum ada realisasi untuk filter ini." />}{canCreate ? <ActionButton onPress={() => router.push("/realization/new")}>Buat Realisasi Baru</ActionButton> : null}</> : <CategorySummary summary={detail?.summary ?? {}} groups={detail?.groups ?? []} loading={budgets.isLoading || budget.isLoading} error={budgets.isError || budget.isError} onRetry={() => { void budgets.refetch(); void budget.refetch(); }} onOpen={(itemId) => router.push(`/realization/new?budgetItemId=${itemId}`)} />}</Screen><BottomNav current="realizations" role={role} /></>;
}

function CategorySummary({ summary, groups, loading, error, onRetry, onOpen }: { summary: Record<string, unknown>; groups: Group[]; loading: boolean; error: boolean; onRetry: () => void; onOpen: (id: string) => void }) { if (loading) return <LoadingState />; if (error) return <ErrorState message="Ringkasan kategori tidak dapat dimuat." onRetry={onRetry} />; if (!groups.length) return <EmptyState message="Belum ada alokasi anggaran pada periode ini." />; return <><View style={styles.summary}><Metric label="Total realisasi" value={money(numberValue(summary, "approvedRealization"))} color={colors.primary} /><Metric label="Serapan" value={`${numberValue(summary, "absorptionPercentage").toFixed(2)}%`} color={colors.success} /><Metric label="Sisa alokasi" value={money(numberValue(summary, "remainingAllocation"))} color={colors.warning} /></View><SectionTitle>Realisasi per Kategori</SectionTitle><ScrollView contentContainerStyle={styles.list}>{groups.map((group) => { const items = group.items ?? []; const allocated = items.reduce((sum, item) => sum + numberValue(item, "allocatedAmount"), 0); const realized = items.reduce((sum, item) => sum + numberValue(item, "approvedRealization"), 0); const percent = allocated ? Math.round((realized / allocated) * 100) : 0; return <View key={text(group, "id")} style={styles.group}><Text style={styles.groupTitle}>{text(group, "name")}</Text><Text style={styles.value}>{money(realized)} / {money(allocated)}</Text><View style={styles.track}><View style={[styles.progress, { width: `${Math.min(percent, 100)}%` }]} /></View><Text style={styles.meta}>{percent}% terserap</Text>{items.map((item) => <RowCard key={text(item, "id")} onPress={() => onOpen(text(item, "id"))} title={text(item, "name")} subtitle={`Realisasi ${money(numberValue(item, "approvedRealization"))}`} meta={`Sisa ${money(numberValue(item, "allocatedAmount") - numberValue(item, "approvedRealization"))}`} status="Buat realisasi" tone="blue" />)}</View>; })}</ScrollView></>; }
function Metric({ label, value, color }: { label: string; value: string; color: string }) { return <View style={styles.metric}><Text style={styles.label}>{label}</Text><Text style={[styles.metricValue, { color }]}>{value}</Text></View>; }
const styles = StyleSheet.create({ period: { alignItems: "center", backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 10, borderWidth: 1, flexDirection: "row", justifyContent: "space-between", paddingHorizontal: spacing.md }, label: { color: colors.textMuted, fontSize: 10, fontWeight: "800" }, periodInput: { color: colors.text, fontSize: 12, fontWeight: "800", minWidth: 78, paddingVertical: 10, textAlign: "right" }, searchRow: { flexDirection: "row", gap: spacing.sm }, search: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 10, borderWidth: 1, color: colors.text, flex: 1, fontSize: 12, paddingHorizontal: 12, paddingVertical: 11 }, filter: { alignItems: "center", borderColor: colors.primary, borderRadius: 10, borderWidth: 1, justifyContent: "center", width: 44 }, filterActive: { backgroundColor: colors.primary }, filters: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 12, borderWidth: 1, padding: spacing.md }, summary: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 13, borderWidth: 1, gap: 9, padding: spacing.md }, metric: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, metricValue: { fontSize: 13, fontWeight: "900" }, list: { gap: spacing.sm, paddingBottom: 8 }, group: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 13, borderWidth: 1, gap: 7, padding: spacing.md }, groupTitle: { color: colors.text, fontSize: 13, fontWeight: "900" }, value: { color: colors.text, fontSize: 12, fontWeight: "800" }, meta: { color: colors.textMuted, fontSize: 10 }, track: { backgroundColor: "#E9EDF4", borderRadius: 5, height: 7, overflow: "hidden" }, progress: { backgroundColor: colors.success, borderRadius: 5, height: 7 } });
