import { useQuery } from "@tanstack/react-query";
import * as FileSystem from "expo-file-system/legacy";
import * as Sharing from "expo-sharing";
import { FileBarChart, FileSpreadsheet, FileText, LockKeyhole, ReceiptText } from "lucide-react-native";
import { useState } from "react";
import { StyleSheet, Text, TextInput, View } from "react-native";

import { useAuth } from "../src/auth";
import { BottomNav, ErrorState, Header, LoadingState, Screen } from "../src/components/Screen";
import { ActionButton, RowCard, SectionTitle } from "../src/components/PimpinanPrimitives";
import { apiBaseUrl, getReport, getToken } from "../src/lib/api";
import { money } from "../src/lib/format";
import { numberValue, text } from "../src/lib/read";
import { colors, spacing } from "../src/theme";

type Section = "finance" | "dues" | "blocks" | "realization" | "information";

export default function Reports() {
  const { role } = useAuth(); const [exporting, setExporting] = useState(false); const [periodKey, setPeriodKey] = useState(new Date().toISOString().slice(0, 7)); const [selected, setSelected] = useState<Section>("finance"); const query = useQuery({ queryKey: ["report", periodKey], queryFn: () => getReport(periodKey), enabled: Boolean(role) }); const report = query.data?.report ?? {}; const financial = (report.financial ?? {}) as Record<string, unknown>; const budget = (report.budget ?? {}) as Record<string, unknown>; const operational = (report.operational ?? {}) as Record<string, unknown>;
  async function exportReport(format: "pdf" | "xlsx") { setExporting(true); try { const token = await getToken(); const uri = `${FileSystem.documentDirectory}satgas-${text(report, "periodKey", "laporan")}.${format}`; const result = await FileSystem.downloadAsync(`${apiBaseUrl()}/api/mobile/reports/export?format=${format}&period=${encodeURIComponent(text(report, "periodKey", ""))}`, uri, { headers: token ? { Authorization: `Bearer ${token}` } : {} }); if (await Sharing.isAvailableAsync()) await Sharing.shareAsync(result.uri); } finally { setExporting(false); } }
  if (!role) return null;
  return <><Header role={role} title="Realisasi & Laporan" subtitle="Ringkasan bulanan siap ekspor" /><Screen><View style={styles.period}><Text style={styles.periodLabel}>PILIH PERIODE</Text><TextInput value={periodKey} onChangeText={setPeriodKey} style={styles.periodInput} /></View>{query.isLoading ? <LoadingState /> : query.isError ? <ErrorState message="Laporan tidak dapat dimuat." onRetry={() => query.refetch()} /> : <><SectionTitle>Jenis Laporan</SectionTitle><RowCard onPress={() => setSelected("finance")} icon={<FileBarChart color={colors.success} size={22} />} title="Laporan Keuangan Bulanan" subtitle={`Pemasukan ${money(numberValue(financial, "income"))} · Pengeluaran ${money(numberValue(financial, "expenses"))}`} status={selected === "finance" ? "Terbuka" : undefined} /><RowCard onPress={() => setSelected("dues")} icon={<ReceiptText color="#18A891" size={22} />} title="Laporan Iuran" subtitle={`Kewajiban ${money(numberValue(financial, "duesObligation"))} · Diterima ${money(numberValue(financial, "paymentsReceived"))}`} status={selected === "dues" ? "Terbuka" : undefined} /><RowCard onPress={() => setSelected("blocks")} icon={<FileText color={colors.primary} size={22} />} title="Laporan Blok" subtitle={`${numberValue(operational, "inspections")} pemeriksaan · ${numberValue(operational, "excavatorMovements")} pergerakan`} status={selected === "blocks" ? "Terbuka" : undefined} /><RowCard onPress={() => setSelected("realization")} icon={<FileSpreadsheet color={colors.warning} size={22} />} title="Laporan Realisasi" subtitle={`Realisasi ${money(numberValue(budget, "realization"))} · Serapan ${numberValue(budget, "absorptionPercentage").toFixed(2)}%`} status={selected === "realization" ? "Terbuka" : undefined} /><RowCard onPress={() => setSelected("information")} icon={<LockKeyhole color="#8B4BD8" size={22} />} title="Laporan Informasi" subtitle={`${numberValue(operational, "totalInformation")} informasi · ${numberValue(operational, "openInformation")} terbuka`} status={selected === "information" ? "Terbuka" : undefined} /><ReportDetail section={selected} financial={financial} budget={budget} operational={operational} /><ActionButton onPress={() => void exportReport("pdf")}>{exporting ? "Menyiapkan laporan…" : "Export PDF"}</ActionButton><ActionButton onPress={() => void exportReport("xlsx")}>Export Excel</ActionButton></>}</Screen><BottomNav current="reports" role={role} /></>;
}
function ReportDetail({ section, financial, budget, operational }: { section: Section; financial: Record<string, unknown>; budget: Record<string, unknown>; operational: Record<string, unknown> }) { const rows = section === "finance" ? [["Saldo awal", money(numberValue(financial, "openingBalance"))], ["Pemasukan", money(numberValue(financial, "income"))], ["Pengeluaran", money(numberValue(financial, "expenses"))], ["Saldo akhir", money(numberValue(financial, "closingBalance"))]] : section === "dues" ? [["Kewajiban", money(numberValue(financial, "duesObligation"))], ["Pembayaran diterima", money(numberValue(financial, "paymentsReceived"))], ["Tunggakan", money(numberValue(financial, "receivables"))]] : section === "realization" ? [["Total alokasi", money(numberValue(budget, "allocation"))], ["Realisasi sah", money(numberValue(budget, "realization"))], ["Sisa alokasi", money(numberValue(budget, "remainingAllocation"))], ["Serapan", `${numberValue(budget, "absorptionPercentage").toFixed(2)}%`]] : section === "blocks" ? [["Pemeriksaan", String(numberValue(operational, "inspections"))], ["Pergerakan excavator", String(numberValue(operational, "excavatorMovements"))]] : [["Informasi", String(numberValue(operational, "totalInformation"))], ["Keluhan", String(numberValue(operational, "complaints"))], ["Insiden", String(numberValue(operational, "incidents"))], ["Masih terbuka", String(numberValue(operational, "openInformation"))]]; return <View style={styles.detail}><Text style={styles.detailTitle}>Rincian Laporan</Text>{rows.map(([label, value]) => <View key={label} style={styles.detailRow}><Text style={styles.detailLabel}>{label}</Text><Text style={styles.detailValue}>{value}</Text></View>)}</View>; }
const styles = StyleSheet.create({ period: { alignItems: "center", backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 10, borderWidth: 1, flexDirection: "row", justifyContent: "space-between", paddingHorizontal: spacing.md }, periodLabel: { color: colors.textMuted, fontSize: 10, fontWeight: "700" }, periodInput: { color: colors.text, fontSize: 12, fontWeight: "800", minWidth: 78, paddingVertical: 10, textAlign: "right" }, detail: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 13, borderWidth: 1, gap: 9, padding: spacing.md }, detailTitle: { color: colors.text, fontSize: 14, fontWeight: "900" }, detailRow: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, detailLabel: { color: colors.textMuted, fontSize: 11 }, detailValue: { color: colors.text, fontSize: 12, fontWeight: "900" } });
