export const PERMISSIONS = {
  USER_READ: "USER_READ",
  USER_MANAGE: "USER_MANAGE",
  BLOCK_READ: "BLOCK_READ",
  BLOCK_CREATE: "BLOCK_CREATE",
  BLOCK_UPDATE: "BLOCK_UPDATE",
  EXCAVATOR_READ: "EXCAVATOR_READ",
  EXCAVATOR_MANAGE: "EXCAVATOR_MANAGE",
  INSPECTION_READ: "INSPECTION_READ",
  INSPECTION_CREATE: "INSPECTION_CREATE",
  DAILY_INFO_READ: "DAILY_INFO_READ",
  DAILY_INFO_CREATE: "DAILY_INFO_CREATE",
  DAILY_INFO_UPDATE: "DAILY_INFO_UPDATE",
  DUES_READ: "DUES_READ",
  DUES_MANAGE: "DUES_MANAGE",
  PAYMENT_CREATE: "PAYMENT_CREATE",
  FINANCE_READ: "FINANCE_READ",
  FINANCE_CREATE: "FINANCE_CREATE",
  FINANCE_APPROVE: "FINANCE_APPROVE",
  BUDGET_READ: "BUDGET_READ",
  BUDGET_CREATE: "BUDGET_CREATE",
  BUDGET_VERIFY: "BUDGET_VERIFY",
  BUDGET_APPROVE: "BUDGET_APPROVE",
  REALIZATION_READ: "REALIZATION_READ",
  REALIZATION_CREATE: "REALIZATION_CREATE",
  REALIZATION_VERIFY: "REALIZATION_VERIFY",
  REALIZATION_APPROVE: "REALIZATION_APPROVE",
  REPORT_READ: "REPORT_READ",
  REPORT_EXPORT: "REPORT_EXPORT",
  AUDIT_READ: "AUDIT_READ",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLES = {
  PIMPINAN: "PIMPINAN",
  BENDAHARA: "BENDAHARA",
  PETUGAS_LAPANGAN: "PETUGAS_LAPANGAN",
} as const;

export type RoleName = (typeof ROLES)[keyof typeof ROLES];

export const ROLE_PERMISSIONS: Record<RoleName, readonly Permission[]> = {
  [ROLES.PIMPINAN]: Object.values(PERMISSIONS),
  [ROLES.BENDAHARA]: [
    PERMISSIONS.BLOCK_READ,
    PERMISSIONS.EXCAVATOR_READ,
    PERMISSIONS.INSPECTION_READ,
    PERMISSIONS.DAILY_INFO_READ,
    PERMISSIONS.DUES_READ,
    PERMISSIONS.DUES_MANAGE,
    PERMISSIONS.PAYMENT_CREATE,
    PERMISSIONS.FINANCE_READ,
    PERMISSIONS.FINANCE_CREATE,
    PERMISSIONS.BUDGET_READ,
    PERMISSIONS.BUDGET_CREATE,
    PERMISSIONS.REALIZATION_READ,
    PERMISSIONS.REALIZATION_CREATE,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.REPORT_EXPORT,
  ],
  [ROLES.PETUGAS_LAPANGAN]: [
    PERMISSIONS.BLOCK_READ,
    PERMISSIONS.EXCAVATOR_READ,
    PERMISSIONS.INSPECTION_READ,
    PERMISSIONS.INSPECTION_CREATE,
    PERMISSIONS.DAILY_INFO_READ,
    PERMISSIONS.DAILY_INFO_CREATE,
    PERMISSIONS.DAILY_INFO_UPDATE,
  ],
};
