import { useQuery } from "@tanstack/react-query";
import { useLocalSearchParams, useRouter } from "expo-router";
import { Linking, Pressable, StyleSheet, Text, View } from "react-native";

import { useAuth } from "../../src/auth";
import { BottomNav, ErrorState, Header, LoadingState, Screen } from "../../src/components/Screen";
import { RowCard, StatusPill } from "../../src/components/PimpinanPrimitives";
import { getInspection, getInspectionPhotoDownloadUrl } from "../../src/lib/api";
import { text } from "../../src/lib/read";
import { colors, spacing } from "../../src/theme";

export default function InspectionDetail() {
  const { id } = useLocalSearchParams<{ id: string }>(); const router = useRouter(); const { role } = useAuth(); const query = useQuery({ queryKey: ["inspection", id], queryFn: () => getInspection(id), enabled: Boolean(role && id) });
  if (!role) return null;
  if (query.isLoading) return <><Header role={role} title="Detail Pemeriksaan" /><Screen><LoadingState /></Screen></>;
  if (query.isError || !query.data) return <><Header role={role} title="Detail Pemeriksaan" /><Screen><ErrorState message="Detail pemeriksaan tidak dapat dimuat." onRetry={() => query.refetch()} /></Screen></>;
  const item = query.data.item;
  const isDraft = text(item, "status") === "DRAFT";
  async function openPhoto(photo: Record<string, unknown>) { try { const result = await getInspectionPhotoDownloadUrl({ inspectionId: id, storageKey: text(photo, "storageKey") }) as { downloadUrl: string }; await Linking.openURL(result.downloadUrl); } catch { /* A safe error response is already returned by the API; keep the detail screen usable. */ } }
  return <><Header role={role} title="Detail Pemeriksaan" subtitle="Data lapangan dan bukti" /><Screen><View style={styles.hero}><Text style={styles.heading}>{text(item, "condition")}</Text><StatusPill tone={isDraft ? "orange" : "green"}>{isDraft ? "DRAFT" : "TERKIRIM"}</StatusPill><Text style={styles.light}>{text(item, "inspectedAt")}</Text></View>{isDraft ? <Pressable onPress={() => router.push({ pathname: "/inspection/new", params: { draftId: id } })} style={styles.resume}><Text style={styles.resumeText}>Lanjutkan Draft</Text></Pressable> : null}<Detail label="Kondisi operasional" value={`Jalan: ${text(item, "roadCondition", "-")} · Lingkungan: ${text(item, "environmentCondition", "-")} · Aktivitas: ${text(item, "activityCondition", "-")}`} /><Detail label="Sumber daya" value={`${text(item, "excavatorCount", "0")} excavator · ${text(item, "workerCount", "0")} pekerja`} /><Detail label="Temuan" value={text(item, "findings", "Tidak ada temuan")} /><Detail label="Catatan" value={text(item, "notes", "Tidak ada catatan")} /><Detail label="Lokasi GPS" value={`${text(item, "latitude")}, ${text(item, "longitude")}`} /><Detail label="Akurasi GPS" value={text(item, "gpsAccuracy")} /><View style={styles.section}><Text style={styles.sectionTitle}>Foto Pemeriksaan</Text>{query.data.photos.length ? query.data.photos.map((photo) => <Pressable key={text(photo, "id")} onPress={() => void openPhoto(photo)}><RowCard title={text(photo, "originalName", "Foto lapangan")} subtitle={text(photo, "contentType")} meta={`${text(photo, "capturedAt")} · Buka foto`} /></Pressable>) : <Text style={styles.empty}>Tidak ada foto pada pemeriksaan ini.</Text>}</View><View style={styles.section}><Text style={styles.sectionTitle}>Riwayat Pemeriksaan</Text>{query.data.events.length ? query.data.events.map((event) => <Detail key={text(event, "id")} label={text(event, "action").replaceAll("_", " ")} value={text(event, "createdAt")} />) : <Text style={styles.empty}>Belum ada riwayat.</Text>}</View></Screen><BottomNav current="inspections" role={role} /></>;
}
function Detail({ label, value }: { label: string; value: string }) { return <View style={styles.card}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>; }
const styles = StyleSheet.create({ hero: { backgroundColor: colors.primaryDark, borderRadius: 15, gap: 7, padding: spacing.lg }, heading: { color: "#FFFFFF", fontSize: 19, fontWeight: "900" }, light: { color: "#DCE7FF", fontSize: 11 }, resume: { alignItems: "center", borderColor: colors.primary, borderRadius: 10, borderWidth: 1, padding: 12 }, resumeText: { color: colors.primary, fontSize: 12, fontWeight: "900" }, card: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 12, borderWidth: 1, gap: 5, padding: spacing.md }, label: { color: colors.textMuted, fontSize: 10, fontWeight: "800" }, value: { color: colors.text, fontSize: 12 }, section: { gap: spacing.sm }, sectionTitle: { color: colors.text, fontSize: 14, fontWeight: "900" }, empty: { color: colors.textMuted, fontSize: 11 } });
