import { useQuery } from "@tanstack/react-query";
import type * as ImagePicker from "expo-image-picker";
import { useRouter } from "expo-router";
import { useState } from "react";
import { Pressable, StyleSheet, Text } from "react-native";
import { AppAlert as Alert } from "../../src/lib/feedback";

import { useAuth } from "../../src/auth";
import { Header, Screen } from "../../src/components/Screen";
import { DatePicker, SelectField, SubmitButton, TextInputField } from "../../src/components/NativeForm";
import { addFundRequestAttachment, createFundRequest, createFundRequestAttachmentUploadUrl, getBlocks, getBudgetCategories, getBudgets } from "../../src/lib/api";
import { text } from "../../src/lib/read";
import { colors } from "../../src/theme";
import { fundRequestFormSchema } from "../../src/form-schemas";
import { pickImagesFromCameraOrLibrary } from "../../src/lib/media";

export default function NewFundRequest() {
  const { role, session } = useAuth(); const router = useRouter();
  const [periodId, setPeriodId] = useState(""); const [categoryId, setCategoryId] = useState(""); const [subcategoryId, setSubcategoryId] = useState(""); const [blockId, setBlockId] = useState(""); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [amount, setAmount] = useState(""); const [requestedAt, setRequestedAt] = useState(new Date().toISOString().slice(0, 10)); const [attachment, setAttachment] = useState<ImagePicker.ImagePickerAsset | null>(null); const [saving, setSaving] = useState(false); const [errors, setErrors] = useState<Record<string, string>>({});
  const budgets = useQuery({ queryKey: ["budgets", "fund-request-form"], queryFn: getBudgets, enabled: Boolean(role) });
  const categories = useQuery({ queryKey: ["budget-categories", "fund-request-form"], queryFn: () => getBudgetCategories(), enabled: Boolean(role) });
  const blocks = useQuery({ queryKey: ["blocks", "fund-request-form"], queryFn: () => getBlocks(), enabled: Boolean(role) });
  if (!role) return null;
  const canCreate = session?.permissions.includes("FUND_REQUEST_CREATE") ?? false;
  const periods = (budgets.data?.budgets ?? []).filter((item) => text(item, "status") === "APPROVED");
  const selectedCategory = (categories.data?.categories ?? []).find((item) => text(item, "id") === categoryId);
  const subcategories = Array.isArray(selectedCategory?.subcategories) ? selectedCategory.subcategories as Array<Record<string, unknown>> : [];
  async function chooseAttachment() { const selected = await pickImagesFromCameraOrLibrary({ title: "Supporting evidence", cameraPermissionMessage: "Allow camera access to take supporting evidence.", libraryPermissionMessage: "Allow photo-library access to choose supporting evidence." }); setAttachment(selected[0] ?? null); }
  async function uploadAttachment(fundRequestId: string) { if (!attachment) return; const size = attachment.fileSize ?? 0; if (!size) throw new Error("Ukuran lampiran tidak tersedia."); if (size > 10 * 1024 * 1024) throw new Error("Lampiran pengajuan maksimal 10 MB."); const contentType = attachment.mimeType ?? "image/jpeg"; const upload = await createFundRequestAttachmentUploadUrl({ fundRequestId, contentType, size, originalName: attachment.fileName ?? `pengajuan-${Date.now()}.jpg` }); const response = await fetch(upload.uploadUrl, { method: "PUT", headers: { "Content-Type": contentType }, body: await (await fetch(attachment.uri)).blob() }); if (!response.ok) throw new Error("Unggah lampiran pengajuan gagal."); await addFundRequestAttachment({ fundRequestId, storageKey: upload.key, contentType, sizeBytes: size, caption: "Supporting evidence" }); }
  async function save() { if (!canCreate) return; const parsed = fundRequestFormSchema.safeParse({ budgetPeriodId: periodId, budgetCategoryId: categoryId, budgetSubcategoryId: subcategoryId, blockId, title, description, amount, requestedAt }); const nextErrors: Record<string, string> = {}; if (!parsed.success) parsed.error.issues.forEach((issue) => { const key = String(issue.path[0] ?? "form"); if (!nextErrors[key]) nextErrors[key] = issue.message; }); setErrors(nextErrors); if (!parsed.success) return; setSaving(true); try { const created = await createFundRequest(parsed.data); await uploadAttachment(created.id); Alert.alert("Saved", "Fund request was saved as a draft.", [{ text: "Open request", onPress: () => router.replace(`/fund-request/${created.id}`) }]); } catch (error) { Alert.alert("Unable to save", error instanceof Error ? error.message : "Check the request fields and connection."); } finally { setSaving(false); } }
  return <><Header role={role} title="New Fund Request" subtitle="Create a draft before submitting it" /><Screen><Text style={styles.heading}>Request Details</Text>{!canCreate ? <Text style={styles.hint}>You do not have permission to create a fund request.</Text> : null}{!periods.length && !budgets.isLoading ? <Text style={styles.hint}>An approved budget period is required before a fund request can be created.</Text> : null}<SelectField label="Approved budget period" required error={errors.periodId} value={periodId} options={periods.map((item) => ({ label: text(item, "periodKey"), value: text(item, "id") }))} onChange={(value) => { setPeriodId(value); setErrors((current) => ({ ...current, periodId: "" })); }} /><SelectField label="Budget category" required error={errors.categoryId} value={categoryId} options={(categories.data?.categories ?? []).map((item) => ({ label: text(item, "name"), value: text(item, "id") }))} onChange={(value) => { setCategoryId(value); setSubcategoryId(""); setErrors((current) => ({ ...current, categoryId: "" })); }} />{subcategories.length ? <SelectField label="Subcategory (optional)" value={subcategoryId} options={[{ label: "No subcategory", value: "" }, ...subcategories.map((item) => ({ label: text(item, "name"), value: text(item, "id") }))]} onChange={setSubcategoryId} /> : null}<SelectField label="Related block (optional)" value={blockId} options={[{ label: "No block", value: "" }, ...(blocks.data?.blocks ?? []).map((item) => ({ label: `${text(item, "code")} · ${text(item, "name")}`, value: text(item, "id") }))]} onChange={setBlockId} /><TextInputField label="Title" required error={errors.title} value={title} onChange={(value) => { setTitle(value); setErrors((current) => ({ ...current, title: "" })); }} placeholder="Short activity title" /><TextInputField label="Activity description" required error={errors.description} value={description} onChange={(value) => { setDescription(value); setErrors((current) => ({ ...current, description: "" })); }} multiline placeholder="Explain what the funds will be used for" /><TextInputField label="Requested amount" required error={errors.amount} value={amount} onChange={(value) => { setAmount(value); setErrors((current) => ({ ...current, amount: "" })); }} keyboardType="numeric" placeholder="Enter whole amount" /><DatePicker label="Request date" value={requestedAt} onChange={(value) => { setRequestedAt(value); setErrors((current) => ({ ...current, requestedAt: "" })); }} error={errors.requestedAt} /><Pressable onPress={() => void chooseAttachment()} style={styles.secondary}><Text style={styles.secondaryText}>{attachment ? "Supporting photo selected" : "Add supporting photo (optional)"}</Text></Pressable><SubmitButton label="Save Draft" loading={saving || !canCreate || !periods.length} onPress={() => void save()} /></Screen></>;
}
const styles = StyleSheet.create({ heading: { color: colors.text, fontSize: 16, fontWeight: "900" }, hint: { color: colors.warning, fontSize: 12, lineHeight: 18 }, secondary: { alignItems: "center", borderColor: colors.primary, borderRadius: 10, borderWidth: 1, padding: 12 }, secondaryText: { color: colors.primary, fontSize: 12, fontWeight: "900" } });
