import { useQuery } from "@tanstack/react-query";
import { Stack, useLocalSearchParams, useRouter } from "expo-router";
import { HardHat, MapPin, UserRound } from "lucide-react-native";
import { useEffect, useState } from "react";
import { Image, Linking, Pressable, StyleSheet, Text, View } from "react-native";
import { AppAlert as Alert } from "../../src/lib/feedback";

import { useAuth } from "../../src/auth";
import { BottomNav, ErrorState, Header, LoadingState, Screen } from "../../src/components/Screen";
import { InteractiveTabs, RowCard, SectionTitle, StatusPill } from "../../src/components/PimpinanPrimitives";
import { BackLink } from "../../src/components/MobilePrimitives";
import { addBlockPhoto, archiveBlock, createBlockPhotoUploadUrl, getBlockDetails, getBlockPhotoDownloadUrl } from "../../src/lib/api";
import { optimizeImage, pickImagesFromCameraOrLibrary, uploadOptimizedImage } from "../../src/lib/media";
import { showActionError } from "../../src/lib/feedback";
import { displayStatus, text } from "../../src/lib/read";
import type { BlockWorkerAssignment } from "../../src/types";
import { colors, spacing } from "../../src/theme";

export default function BlockDetail() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const router = useRouter();
  const { role, session } = useAuth();
  const [tab, setTab] = useState(0); const [uploading, setUploading] = useState(false);
  const query = useQuery({ queryKey: ["block", id], queryFn: () => getBlockDetails(id), enabled: Boolean(role && id) });
  if (!role) return null;
  if (query.isLoading) return <><Header role={role} title="Detail Blok" subtitle="Memuat detail blok" /><Screen><LoadingState /></Screen></>;
  if (query.isError || !query.data) return <><Header role={role} title="Detail Blok" /><Screen><ErrorState message="Detail blok tidak dapat dimuat." onRetry={() => query.refetch()} /></Screen></>;
  const { item, excavators, inspections, dailyInformation, workers, tasks, photos, history } = query.data;
  const canEdit = session?.permissions.includes("BLOCK_UPDATE");
  const canArchive = session?.permissions.includes("BLOCK_ARCHIVE") ?? false;
  async function toggleArchive() { if (uploading) return; setUploading(true); try { await archiveBlock({ id, archived: !item.archivedAt, reason: item.archivedAt ? "Dipulihkan melalui aplikasi mobile" : "Diarsipkan melalui aplikasi mobile" }); await query.refetch(); } catch (error) { Alert.alert("Tidak dapat mengubah arsip", error instanceof Error ? error.message : "Coba lagi."); } finally { setUploading(false); } }
  return <><Stack.Screen options={{ headerShown: false }} /><Header role={role} title={`Detail ${item.code}`} subtitle="Informasi blok dan operasional" /><Screen><BackLink label="Kembali ke monitoring" onPress={() => router.back()} /><View style={styles.hero}><View><Text style={styles.code}>{item.code}</Text><Text style={styles.name}>{item.name}</Text></View><StatusPill tone={item.status === "ACTIVE" ? "green" : item.status === "STOPPED" ? "red" : "gray"}>{item.status === "ACTIVE" ? "Aktif" : item.status === "STOPPED" ? "Berhenti" : "Belum beroperasi"}</StatusPill></View>{item.archivedAt ? <Text style={styles.archived}>Blok diarsipkan</Text> : null}{canEdit ? <Pressable onPress={() => router.push(`/block/edit/${id}`)} style={styles.edit}><Text style={styles.editText}>Ubah Blok / Ubah Status</Text></Pressable> : null}{canArchive ? <Pressable onPress={() => void toggleArchive()} style={styles.archive}><Text style={styles.archiveText}>{item.archivedAt ? "Pulihkan Blok" : "Arsipkan Blok"}</Text></Pressable> : null}<InteractiveTabs active={tab} items={["Ringkasan", "Alat Berat", "Pekerja", "Tugas", "Pemeriksaan", "Informasi", "Dokumentasi", "Riwayat"]} onChange={setTab} />{tab === 0 ? <Summary item={item} excavators={excavators.length} inspections={inspections.length} history={history.length} /> : tab === 1 ? <ExcavatorSection excavators={excavators} onOpen={(excavatorId) => router.push(`/excavator/${excavatorId}`)} /> : tab === 2 ? <WorkerSection workers={workers} onOpen={(workerId) => router.push(`/worker/${workerId}`)} /> : tab === 3 ? <TaskSection tasks={tasks} onOpen={(taskId) => router.push(`/task/${taskId}`)} /> : tab === 4 ? <InspectionSection inspections={inspections} /> : tab === 5 ? <InformationSection items={dailyInformation} onOpen={(informationId) => router.push(`/information/${informationId}`)} /> : tab === 6 ? <PhotoSection blockId={id} photos={photos} canEdit={Boolean(canEdit)} onUploaded={() => query.refetch()} /> : <HistorySection history={history} />}</Screen><BottomNav current="monitoring" role={role} /></>;
}

function ExcavatorSection({ excavators, onOpen }: { excavators: Array<Record<string, unknown>>; onOpen: (id: string) => void }) { return <View style={styles.section}><SectionTitle action={`${excavators.length} unit aktif`}>Alat Berat per Unit</SectionTitle>{excavators.length ? excavators.map((excavator) => <RowCard key={text(excavator, "id")} onPress={() => onOpen(text(excavator, "id"))} icon={<HardHat color={colors.warning} size={23} />} title={text(excavator, "unitCode")} subtitle={`${text(excavator, "brand")} ${text(excavator, "model")}`} meta={`Operator: ${text(excavator, "operatorName")} · Masuk: ${text(excavator, "currentEntryDate")}`} status="Aktif" tone="green" />) : <Text style={styles.empty}>Belum ada alat berat pada blok ini.</Text>}</View>; }
function InspectionSection({ inspections }: { inspections: Array<Record<string, unknown>> }) { return <View style={styles.section}><SectionTitle action={`${inspections.length} pemeriksaan`}>Pemeriksaan Blok</SectionTitle>{inspections.length ? inspections.map((inspection) => <View key={text(inspection, "id")} style={styles.history}><Text style={styles.historyAction}>{text(inspection, "condition", "Kondisi tidak tersedia")}</Text><Text style={styles.detail}>Tanggal: {text(inspection, "inspectedAt", "Belum tersedia")}</Text><Text style={styles.detail}>Temuan: {text(inspection, "findings", "Tidak ada temuan")}</Text></View>) : <Text style={styles.empty}>Belum ada pemeriksaan pada blok ini.</Text>}</View>; }
function WorkerSection({ workers, onOpen }: { workers: BlockWorkerAssignment[]; onOpen: (id: string) => void }) { return <View style={styles.section}><SectionTitle action={`${workers.length} penempatan`}>Pekerja</SectionTitle>{workers.length ? workers.map((entry) => <RowCard key={text(entry.assignment, "id")} onPress={() => onOpen(text(entry.worker, "id"))} title={text(entry.worker, "fullName")} subtitle={text(entry.worker, "position", "Pekerja lapangan")} meta={`${text(entry.assignment, "startedAt")} — ${text(entry.assignment, "endedAt", "Aktif")}`} status={text(entry.worker, "status")} tone={text(entry.worker, "status") === "ACTIVE" ? "green" : "gray"} />) : <Text style={styles.empty}>Belum ada pekerja pada blok ini.</Text>}</View>; }
function TaskSection({ tasks, onOpen }: { tasks: Array<Record<string, unknown>>; onOpen: (id: string) => void }) { return <View style={styles.section}><SectionTitle action={`${tasks.length} tugas`}>Tugas Lapangan</SectionTitle>{tasks.length ? tasks.map((task) => <RowCard key={text(task, "id")} onPress={() => onOpen(text(task, "id"))} title={text(task, "title")} subtitle={`Prioritas ${displayStatus(text(task, "priority"))}`} meta={text(task, "dueDate", "Tanpa tenggat")} status={text(task, "status")} tone={text(task, "status") === "DONE" ? "green" : text(task, "status") === "CANCELLED" ? "red" : "orange"} />) : <Text style={styles.empty}>Belum ada tugas pada blok ini.</Text>}</View>; }
function InformationSection({ items, onOpen }: { items: Array<Record<string, unknown>>; onOpen: (id: string) => void }) { return <View style={styles.section}><SectionTitle action={`${items.length} informasi`}>Informasi Harian</SectionTitle>{items.length ? items.map((item) => <RowCard key={text(item, "id")} onPress={() => onOpen(text(item, "id"))} title={text(item, "description")} subtitle={`${displayStatus(text(item, "category"))} · ${displayStatus(text(item, "priority"))}`} meta={text(item, "reportedAt")} status={text(item, "status")} tone={text(item, "priority") === "URGENT" ? "red" : "orange"} />) : <Text style={styles.empty}>Belum ada informasi untuk blok ini.</Text>}</View>; }
function PhotoSection({ blockId, photos, canEdit, onUploaded }: { blockId: string; photos: Array<Record<string, unknown>>; canEdit: boolean; onUploaded: () => void }) {
  const [urls, setUrls] = useState<Record<string, string>>({}); const [uploading, setUploading] = useState(false);
  useEffect(() => { void Promise.all(photos.map(async (photo) => { const key = text(photo, "storageKey"); const result = await getBlockPhotoDownloadUrl({ blockId, storageKey: key }); return [key, result.downloadUrl] as const; })).then((entries) => setUrls(Object.fromEntries(entries))).catch(() => setUrls({})); }, [blockId, photos]);
  async function addPhoto() { if (uploading) return; const selected = await pickImagesFromCameraOrLibrary({ title: "Dokumentasi blok", cameraPermissionMessage: "Izinkan kamera untuk menambah dokumentasi blok.", libraryPermissionMessage: "Izinkan akses galeri untuk menambah dokumentasi blok." }); if (!selected[0]) return; setUploading(true); try { const image = await optimizeImage(selected[0], `blok-${Date.now()}`); const upload = await createBlockPhotoUploadUrl({ blockId, contentType: image.contentType, sizeBytes: image.sizeBytes, originalName: image.name }); await uploadOptimizedImage(upload.uploadUrl, image); await addBlockPhoto({ blockId, storageKey: upload.key, contentType: image.contentType, sizeBytes: image.sizeBytes, caption: "Dokumentasi blok" }); onUploaded(); } catch (error) { Alert.alert("Tidak dapat mengunggah foto", error instanceof Error ? error.message : "Coba lagi."); } finally { setUploading(false); } }
  return <View style={styles.section}><SectionTitle action={`${photos.length} foto`}>Dokumentasi Blok</SectionTitle>{photos.length ? photos.map((photo) => { const key = text(photo, "storageKey"); const url = urls[key]; const content = <>{url ? <Image alt="Dokumentasi blok" source={{ uri: url }} style={styles.photo} /> : null}<Text style={styles.historyAction}>{text(photo, "caption", "Dokumentasi blok")}</Text><Text style={styles.detail}>{text(photo, "contentType")} · {text(photo, "createdAt")}</Text></>; return url ? <Pressable key={text(photo, "id")} onPress={() => Linking.openURL(url).catch((error) => showActionError(error, "Foto dokumentasi tidak dapat dibuka."))} style={styles.history}>{content}</Pressable> : <View key={text(photo, "id")} style={styles.history}>{content}<Text style={styles.detail}>Foto sedang diproses. Coba lagi sebentar.</Text></View>; }) : <Text style={styles.empty}>Belum ada dokumentasi blok.</Text>}{canEdit ? <Pressable disabled={uploading} onPress={() => void addPhoto()} style={styles.edit}><Text style={styles.editText}>{uploading ? "Mengunggah foto…" : "Tambah Foto Dokumentasi"}</Text></Pressable> : null}</View>;
}
function HistorySection({ history }: { history: Array<Record<string, unknown>> }) { return <View style={styles.section}><SectionTitle action={`${history.length} perubahan`}>Riwayat Blok</SectionTitle>{history.length ? history.map((entry) => <View key={text(entry, "id")} style={styles.history}><Text style={styles.historyAction}>{text(entry, "action", "Perubahan")}</Text><Text style={styles.detail}>{text(entry, "createdAt", "Tanggal tidak tersedia")}</Text></View>) : <Text style={styles.empty}>Belum ada riwayat blok.</Text>}</View>; }

function Summary({ item, excavators, inspections, history }: { item: { operationalCondition: string; workerCount: number; managerName: string | null; fieldPicName: string | null; locationPicName: string | null; latitude: string; longitude: string; priority?: string; areaHectares?: string | null }; excavators: number; inspections: number; history: number }) {
  return <><View style={styles.info}><Text style={styles.label}>Kondisi operasional</Text><Text style={styles.detail}>{item.operationalCondition}</Text></View><View style={styles.info}><Text style={styles.label}>Pengelola</Text><Text style={styles.detail}>{item.managerName ?? "Belum ditentukan"}</Text><Text style={styles.detail}>Prioritas: {displayStatus(item.priority ?? "NORMAL")} · Luas: {item.areaHectares ?? "Belum diisi"} ha</Text></View><View style={styles.info}><Text style={styles.label}>Jumlah pekerja</Text><Text style={styles.detail}>{item.workerCount} orang</Text></View><View style={styles.info}><Text style={styles.label}>Lokasi (GPS)</Text><View style={styles.location}><MapPin color={colors.primary} size={16} /><Text style={styles.detail}>{item.latitude}, {item.longitude}</Text></View></View><View style={styles.section}><SectionTitle>Ringkasan Aktivitas</SectionTitle><View style={styles.stats}><Stat label="Alat Berat" value={excavators} /><Stat label="Pemeriksaan" value={inspections} /><Stat label="Riwayat" value={history} /></View></View><View style={styles.section}><SectionTitle>PIC Lapangan</SectionTitle><View style={styles.info}><View style={styles.location}><UserRound color={colors.primary} size={16} /><Text style={styles.detail}>{item.fieldPicName ?? "PIC lapangan belum ditentukan"}</Text></View><Text style={styles.detail}>PIC lokasi: {item.locationPicName ?? "Belum ditentukan"}</Text></View></View></>;
}

function Stat({ label, value }: { label: string; value: number }) { return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.label}>{label}</Text></View>; }
const styles = StyleSheet.create({ back: { color: colors.primary, fontSize: 12, fontWeight: "700" }, hero: { alignItems: "center", backgroundColor: colors.primaryDark, borderRadius: 18, flexDirection: "row", justifyContent: "space-between", padding: spacing.lg }, edit: { alignItems: "center", borderColor: colors.primary, borderRadius: 9, borderWidth: 1, padding: 11 }, editText: { color: colors.primary, fontSize: 11, fontWeight: "900" }, archive: { alignItems: "center", borderColor: colors.danger, borderRadius: 9, borderWidth: 1, padding: 11 }, archiveText: { color: colors.danger, fontSize: 11, fontWeight: "900" }, archived: { color: colors.warning, fontSize: 11, fontWeight: "900" }, code: { color: "#DCE7FF", fontSize: 12, fontWeight: "800", letterSpacing: 1 }, name: { color: "#fff", fontSize: 21, fontWeight: "800", marginTop: 8 }, info: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 13, borderWidth: 1, padding: spacing.md }, label: { color: colors.textMuted, fontSize: 10, fontWeight: "700" }, detail: { color: colors.text, fontSize: 13, marginTop: 5 }, section: { gap: spacing.sm }, stats: { flexDirection: "row", gap: spacing.sm }, stat: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 12, borderWidth: 1, flex: 1, padding: spacing.sm }, statValue: { color: colors.primary, fontSize: 18, fontWeight: "800" }, location: { alignItems: "center", flexDirection: "row", gap: 7 }, history: { backgroundColor: colors.surface, borderColor: colors.border, borderLeftColor: colors.primary, borderLeftWidth: 3, borderRadius: 10, borderWidth: 1, padding: spacing.md }, historyAction: { color: colors.text, fontSize: 12, fontWeight: "800" }, photo: { borderRadius: 8, height: 150, marginBottom: spacing.sm, width: "100%" }, empty: { color: colors.textMuted, padding: spacing.lg, textAlign: "center" } });
