import { ChevronRight, Plus } from "lucide-react-native";
import { Pressable, StyleSheet, Text, View } from "react-native";
import type { ReactNode } from "react";

import { colors, spacing } from "../theme";

export function Tabs({ items, active = 0 }: { items: string[]; active?: number }) { return <View style={styles.tabs}>{items.map((item, index) => <View key={item} style={[styles.tab, index === active && styles.activeTab]}><Text style={[styles.tabText, index === active && styles.activeTabText]}>{item}</Text></View>)}</View>; }
export function InteractiveTabs({ items, active, onChange }: { items: string[]; active: number; onChange: (index: number) => void }) { return <View style={styles.tabs}>{items.map((item, index) => <Pressable key={item} onPress={() => onChange(index)} style={[styles.tab, index === active && styles.activeTab]}><Text style={[styles.tabText, index === active && styles.activeTabText]}>{item}</Text></Pressable>)}</View>; }
export function StatusPill({ children, tone = "green" }: { children: ReactNode; tone?: "green" | "red" | "orange" | "blue" | "gray" }) { return <Text style={[styles.pill, styles[`pill_${tone}`]]}>{children}</Text>; }
export function ActionButton({ children, onPress }: { children: ReactNode; onPress?: () => void }) { return <Pressable onPress={onPress} style={({ pressed }) => [styles.action, pressed && { opacity: 0.8 }]}><Plus color="#FFFFFF" size={16} /><Text style={styles.actionText}>{children}</Text></Pressable>; }
export function RowCard({ title, subtitle, meta, status, tone = "green", icon, thumbnail, onPress }: { title: string; subtitle?: string; meta?: string; status?: string; tone?: "green" | "red" | "orange" | "blue" | "gray"; icon?: ReactNode; thumbnail?: ReactNode; onPress?: () => void }) { return <Pressable onPress={onPress} style={styles.rowCard}><View style={styles.rowIcon}>{thumbnail ?? icon}</View><View style={styles.rowCopy}><Text style={styles.rowTitle}>{title}</Text>{subtitle ? <Text style={styles.rowSubtitle}>{subtitle}</Text> : null}{meta ? <Text style={styles.rowMeta}>{meta}</Text> : null}</View>{status ? <StatusPill tone={tone}>{status}</StatusPill> : null}<ChevronRight color="#98A2B3" size={16} /></Pressable>; }
export function SectionTitle({ children, action }: { children: ReactNode; action?: string }) { return <View style={styles.section}><Text style={styles.sectionTitle}>{children}</Text>{action ? <Text style={styles.sectionAction}>{action}</Text> : null}</View>; }
const styles = StyleSheet.create({ tabs: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 8, borderWidth: 1, flexDirection: "row", padding: 3 }, tab: { alignItems: "center", flex: 1, justifyContent: "center", minHeight: 48, paddingHorizontal: 5, paddingVertical: 8 }, activeTab: { backgroundColor: colors.primary, borderRadius: 6 }, tabText: { color: colors.textMuted, fontSize: 9, fontWeight: "700", lineHeight: 13, textAlign: "center" }, activeTabText: { color: "#FFFFFF" }, pill: { borderRadius: 8, fontSize: 9, fontWeight: "800", overflow: "hidden", paddingHorizontal: 7, paddingVertical: 4 }, pill_green: { backgroundColor: "#E7F7EC", color: colors.success }, pill_red: { backgroundColor: "#FFE8E7", color: colors.danger }, pill_orange: { backgroundColor: "#FFF1D9", color: colors.warning }, pill_blue: { backgroundColor: "#E9F1FF", color: colors.primary }, pill_gray: { backgroundColor: "#EEF1F5", color: colors.textMuted }, action: { alignItems: "center", backgroundColor: colors.primary, borderRadius: 9, flexDirection: "row", gap: 7, justifyContent: "center", padding: 13 }, actionText: { color: "#FFFFFF", fontSize: 12, fontWeight: "800" }, rowCard: { alignItems: "center", backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 13, borderWidth: 1, flexDirection: "row", gap: spacing.sm, padding: spacing.sm }, rowIcon: { alignItems: "center", backgroundColor: "#F0F4FB", borderRadius: 9, height: 46, justifyContent: "center", width: 52 }, rowCopy: { flex: 1 }, rowTitle: { color: colors.text, fontSize: 11, fontWeight: "800" }, rowSubtitle: { color: colors.textMuted, fontSize: 10, marginTop: 4 }, rowMeta: { color: colors.textMuted, fontSize: 9, marginTop: 4 }, section: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, sectionTitle: { color: colors.text, fontSize: 14, fontWeight: "800" }, sectionAction: { color: colors.primary, fontSize: 10, fontWeight: "800" } });
