import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native";
import type { ReactNode } from "react";
import { useRouter } from "expo-router";
import { useQuery } from "@tanstack/react-query";
import { Bell, CircleUserRound, ClipboardCheck, FileText, Home, MapPinned, Search, TrendingUp, WalletCards } from "lucide-react-native";
import { SafeAreaView } from "react-native-safe-area-context";

import { useAuth } from "../auth";
import { getNotifications } from "../lib/api";
import { useOfflineSync } from "../offline/provider";
import { DateRangePicker } from "./DateRangePicker";
import { colors, roleTheme, spacing, type Role } from "../theme";

export function Screen({ children, refreshing, onRefresh, scroll = true }: { children: ReactNode; refreshing?: boolean; onRefresh?: () => void; scroll?: boolean }) {
  const sync = useOfflineSync();
  const notice = !sync.isOnline ? "Offline — perubahan baru akan dikirim saat koneksi kembali." : sync.summary.FAILED ? `${sync.summary.FAILED} data gagal dikirim. Ketuk untuk mencoba lagi.` : sync.summary.PENDING || sync.summary.SYNCING ? `${sync.summary.PENDING + sync.summary.SYNCING} data menunggu sinkronisasi.` : null;
  const banner = notice ? <Pressable disabled={sync.isSyncing} onPress={() => void sync.syncNow(true)} style={[styles.syncBanner, sync.summary.FAILED ? styles.syncBannerFailed : null]}><Text style={styles.syncBannerText}>{sync.isSyncing ? "Menyinkronkan data…" : notice}</Text></Pressable> : null;
  const content = scroll ? <ScrollView contentContainerStyle={styles.content} refreshControl={onRefresh ? <RefreshControl onRefresh={onRefresh} refreshing={Boolean(refreshing)} tintColor={colors.primary} /> : undefined}><DateRangePicker />{banner}{children}</ScrollView> : <View style={styles.content}><DateRangePicker />{banner}{children}</View>;
  return <SafeAreaView edges={["bottom"]} style={styles.safe}>{content}</SafeAreaView>;
}

export function Header({ role, title, subtitle }: { role: Role; title: string; subtitle?: string }) {
  const { session } = useAuth();
  const router = useRouter();
  const notifications = useQuery({ queryKey: ["notifications", "unread-count"], queryFn: () => getNotifications({ unreadOnly: true, pageSize: 1 }) });
  const theme = roleTheme[role];
  return <><SafeAreaView edges={["top"]} style={[styles.headerSafe, { backgroundColor: theme.header }]}><View style={styles.header}><View style={styles.headerSide}><View style={styles.headerCopy}><Text numberOfLines={1} style={styles.headerEyebrow}>SATGAS DESA SEJOLI</Text><Text numberOfLines={1} style={styles.headerTitle}>{theme.label}</Text><Text numberOfLines={1} style={styles.headerSubtitle}>{subtitle ?? "Akses operasional berbasis peran"}</Text></View></View><View style={styles.headerActions}><Pressable accessibilityLabel="Open notifications" accessibilityRole="button" onPress={() => router.push("/notifications")} hitSlop={10} style={styles.bell}><Bell color="#FFFFFF" size={19} />{notifications.data?.total ? <View style={styles.notificationBadge}><Text style={styles.notificationBadgeText}>{notifications.data.total > 9 ? "9+" : notifications.data.total}</Text></View> : null}</Pressable><Pressable accessibilityLabel="Open profile" accessibilityRole="button" onPress={() => router.push("/profile")} hitSlop={10} style={styles.profileButton}><CircleUserRound color="#FFFFFF" size={24} /><Text numberOfLines={1} style={styles.userName}>{session?.user.name}</Text></Pressable></View></View></SafeAreaView><View style={styles.pageBar}><Text style={styles.pageTitle}>{title}</Text></View></>;
}

export function LoadingState() { return <View style={styles.state}><ActivityIndicator color={colors.primary} /><Text style={styles.muted}>Memuat data…</Text></View>; }
export function ErrorState({ message, onRetry }: { message: string; onRetry: () => void }) { return <View style={styles.state}><Text style={styles.errorTitle}>Terjadi masalah</Text><Text style={styles.muted}>{message}</Text><Pressable onPress={onRetry} style={styles.retry}><Text style={styles.retryText}>Coba lagi</Text></Pressable></View>; }
export function EmptyState({ message }: { message: string }) { return <View style={styles.state}><Text style={styles.muted}>{message}</Text></View>; }
export function BottomNav({ role, current }: { role: Role; current: string }) {
  if (role === "PIMPINAN") return <View style={styles.nav}><NavItem icon={Home} label="Dashboard" active={current === "dashboard"} href="/dashboard" /><NavItem icon={MapPinned} label="Monitoring Blok" active={current === "monitoring"} href="/monitoring" /><NavItem icon={WalletCards} label="Keuangan" active={current === "finance"} href="/finance" /><NavItem icon={Search} label="Anggaran" active={current === "budgets"} href="/budgets" /><NavItem icon={FileText} label="Laporan" active={current === "reports" || current === "realizations"} href="/reports" /></View>;
  if (role === "BENDAHARA") return <View style={styles.nav}><NavItem icon={Home} label="Dashboard" active={current === "dashboard"} href="/dashboard" /><NavItem icon={WalletCards} label="Keuangan" active={current === "finance"} href="/finance" /><NavItem icon={Search} label="Anggaran" active={current === "budgets"} href="/budgets" /><NavItem icon={ClipboardCheck} label="Pengajuan" active={current === "proposals"} href="/proposals" /><NavItem icon={TrendingUp} label="Realisasi" active={current === "realizations"} href="/realizations" /><NavItem icon={FileText} label="Laporan" active={current === "reports"} href="/reports" /></View>;
  if (role === "PETUGAS_LAPANGAN") return <View style={styles.nav}><NavItem icon={Home} label="Dashboard" active={current === "dashboard"} href="/dashboard" /><NavItem icon={FileText} label="Pemeriksaan" active={current === "inspections" || current === "monitoring" || current === "map"} href="/monitoring" /><NavItem icon={MapPinned} label="Excavator" active={current === "excavators"} href="/excavators" /><NavItem icon={WalletCards} label="Informasi" active={current === "information"} href="/information" /><NavItem icon={CircleUserRound} label="Profil" active={current === "profile"} href="/profile" /></View>;
  return <View style={styles.nav}><NavItem icon={Home} label="Beranda" active={current === "dashboard"} href="/dashboard" /><NavItem icon={MapPinned} label="Keuangan" active={current === "monitoring"} href="/finance" /><NavItem icon={WalletCards} label="Informasi" active={false} href="/information" /><NavItem icon={Search} label="Laporan" active={false} href="/reports" /><NavItem icon={CircleUserRound} label="Akun" active={false} href="/dashboard" /></View>;
}

function NavItem({ label, active, href, icon: Icon }: { label: string; active: boolean; href: "/dashboard" | "/monitoring" | "/finance" | "/information" | "/reports" | "/budgets" | "/proposals" | "/realizations" | "/inspections" | "/excavators" | "/profile" | "/notifications"; icon: typeof Home }) {
  const router = useRouter();
  return <Pressable onPress={() => router.push(href)} style={styles.navItem}><Icon color={active ? colors.primary : colors.textMuted} size={18} /><Text style={[styles.navLabel, active && styles.navActive]}>{label}</Text></Pressable>;
}

const styles = StyleSheet.create({ safe: { backgroundColor: colors.page, flex: 1 }, content: { gap: spacing.sm, padding: spacing.md, paddingBottom: 90, paddingTop: spacing.sm }, syncBanner: { backgroundColor: "#FFF1C5", borderColor: "#F1C554", borderRadius: 10, borderWidth: 1, padding: 10 }, syncBannerFailed: { backgroundColor: "#FDE8E7", borderColor: "#EA8D89" }, syncBannerText: { color: colors.text, fontSize: 11, fontWeight: "700", lineHeight: 16 }, headerSafe: { width: "100%" }, header: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", paddingHorizontal: spacing.md, paddingVertical: 10 }, headerSide: { alignItems: "center", flex: 1, flexDirection: "row", gap: 10, minWidth: 0 }, headerCopy: { flex: 1, minWidth: 0 }, headerActions: { alignItems: "center", flexDirection: "row", flexShrink: 0, gap: 8, marginLeft: 8 }, bell: { alignItems: "center", height: 44, justifyContent: "center", position: "relative", width: 32 }, profileButton: { alignItems: "center", flexDirection: "row", gap: 4, maxWidth: 84, minHeight: 44 }, notificationBadge: { alignItems: "center", backgroundColor: "#E63630", borderColor: "#FFFFFF", borderRadius: 10, borderWidth: 1, height: 16, justifyContent: "center", minWidth: 16, paddingHorizontal: 3, position: "absolute", right: -4, top: 5 }, notificationBadgeText: { color: "#FFFFFF", fontSize: 8, fontWeight: "900" }, headerEyebrow: { color: "#FFFFFF", fontSize: 10, fontWeight: "800", letterSpacing: 0.4 }, headerTitle: { color: "#FFE34F", fontSize: 10, fontWeight: "900", marginTop: 3 }, headerSubtitle: { color: "#DCE7FF", fontSize: 9, marginTop: 2 }, userName: { color: "#FFFFFF", flexShrink: 1, fontSize: 8, fontWeight: "700", maxWidth: 54 }, pageBar: { backgroundColor: "#FFFFFF", borderBottomColor: colors.border, borderBottomWidth: 1, paddingHorizontal: spacing.md, paddingVertical: 8 }, pageTitle: { color: colors.text, fontSize: 14, fontWeight: "900", textTransform: "uppercase" }, state: { alignItems: "center", gap: spacing.sm, justifyContent: "center", minHeight: 200 }, muted: { color: colors.textMuted, fontSize: 12, textAlign: "center" }, errorTitle: { color: colors.danger, fontSize: 15, fontWeight: "800" }, retry: { backgroundColor: colors.primary, borderRadius: 8, paddingHorizontal: 16, paddingVertical: 10 }, retryText: { color: "#fff", fontSize: 12, fontWeight: "700" }, nav: { backgroundColor: "#FFFFFF", borderColor: colors.border, borderTopWidth: 1, bottom: 0, flexDirection: "row", left: 0, paddingBottom: 10, paddingTop: 8, position: "absolute", right: 0 }, navItem: { alignItems: "center", flex: 1, gap: 3 }, navLabel: { color: colors.textMuted, fontSize: 8, fontWeight: "700", textAlign: "center" }, navActive: { color: colors.primary } });
