import * as DocumentPicker from "expo-document-picker";
import * as ImagePicker from "expo-image-picker";
import { useQuery } from "@tanstack/react-query";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useState } from "react";
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { useAuth } from "../../src/auth";
import { Header, Screen } from "../../src/components/Screen";
import { DatePicker, SelectField, SubmitButton } from "../../src/components/NativeForm";
import { addRealizationEvidence, createRealization, createRealizationEvidenceUploadUrl, getBudgets, getFundRequests } from "../../src/lib/api";
import { text } from "../../src/lib/read";
import { colors, spacing } from "../../src/theme";

type Attachment = { uri: string; name: string; mimeType: string; size: number };

export default function NewRealization() {
  const { role, session } = useAuth(); const router = useRouter(); const params = useLocalSearchParams<{ budgetItemId?: string }>();
  const [budgetItemId, setBudgetItemId] = useState(params.budgetItemId ?? ""); const [fundRequestId, setFundRequestId] = useState(""); const [activity, setActivity] = useState(""); const [realizationDate, setRealizationDate] = useState(new Date().toISOString().slice(0, 10)); const [requestedAmount, setRequestedAmount] = useState(""); const [receiptNumber, setReceiptNumber] = useState(""); const [description, setDescription] = useState(""); const [attachments, setAttachments] = useState<Attachment[]>([]); const [saving, setSaving] = useState(false);
  const budgets = useQuery({ queryKey: ["budgets", "realization-form"], queryFn: getBudgets, enabled: Boolean(role) }); const requests = useQuery({ queryKey: ["fund-requests", "realization-form"], queryFn: () => getFundRequests({ status: "APPROVED", pageSize: "100" }), enabled: Boolean(role) });
  if (!role) return null;
  const canCreate = session?.permissions.includes("REALIZATION_CREATE") ?? false; const items = (budgets.data?.budgets ?? []).flatMap((period) => Array.isArray(period.items) ? period.items as Array<Record<string, unknown>> : []); const requestOptions = [{ label: "No linked fund request", value: "" }, ...(requests.data?.items ?? []).map((row) => { const request = row.request as Record<string, unknown>; return { label: `${text(request, "requestNumber")} · ${text(request, "title")}`, value: text(request, "id") }; })];
  function addAttachment(item: Attachment) { setAttachments((current) => [...current, item].slice(0, 5)); }
  async function choosePhoto(source: "camera" | "library") { const permission = source === "camera" ? await ImagePicker.requestCameraPermissionsAsync() : await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) return Alert.alert("Permission required", "Allow access to add realization evidence."); const result = source === "camera" ? await ImagePicker.launchCameraAsync({ mediaTypes: ["images"], quality: 0.8 }) : await ImagePicker.launchImageLibraryAsync({ mediaTypes: ["images"], allowsMultipleSelection: true, selectionLimit: 5 - attachments.length, quality: 0.8 }); if (!result.canceled) for (const asset of result.assets ?? []) { const size = asset.fileSize ?? 0; if (size) addAttachment({ uri: asset.uri, name: asset.fileName ?? `realisasi-${Date.now()}.jpg`, mimeType: asset.mimeType ?? "image/jpeg", size }); } }
  async function chooseDocument() { const result = await DocumentPicker.getDocumentAsync({ type: ["application/pdf", "image/*"], multiple: true, copyToCacheDirectory: true }); if (result.canceled) return; for (const asset of result.assets ?? []) if (asset.size) addAttachment({ uri: asset.uri, name: asset.name, mimeType: asset.mimeType ?? "application/octet-stream", size: asset.size }); }
  async function uploadAttachments(realizationId: string) { for (const attachment of attachments) { const upload = await createRealizationEvidenceUploadUrl({ realizationId, contentType: attachment.mimeType, size: attachment.size, originalName: attachment.name }); const response = await fetch(upload.uploadUrl, { method: "PUT", headers: { "Content-Type": attachment.mimeType }, body: await (await fetch(attachment.uri)).blob() }); if (!response.ok) throw new Error(`Upload failed for ${attachment.name}.`); await addRealizationEvidence({ realizationId, storageKey: upload.key, contentType: attachment.mimeType, sizeBytes: attachment.size, caption: attachment.name }); } }
  async function save() { if (!canCreate) return; if (!budgetItemId || !activity.trim() || !requestedAmount.trim() || !description.trim()) return Alert.alert("Complete the realization", "Budget item, activity, date, amount, and description are required."); setSaving(true); try { const created = await createRealization({ budgetItemId, fundRequestId: fundRequestId || undefined, activity, realizationDate, requestedAmount: Number(requestedAmount), receiptNumber: receiptNumber || undefined, description }); const id = text(created, "id"); if (id) await uploadAttachments(id); Alert.alert("Saved", "Realization was saved as a draft.", [{ text: "Open realization", onPress: () => router.replace(`/realization/${id}`) }]); } catch (error) { Alert.alert("Unable to save", error instanceof Error ? error.message : "Check the realization data and connection."); } finally { setSaving(false); } }
  return <><Header role={role} title="Buat Realisasi" subtitle="Kegiatan, bukti, dan alokasi dana" /><Screen><Text style={styles.heading}>Detail Realisasi</Text>{!items.length && !budgets.isLoading ? <Text style={styles.hint}>Tidak ada item dari periode anggaran yang disetujui.</Text> : null}<SelectField label="Item anggaran" value={budgetItemId} options={items.map((item) => ({ label: text(item, "name", "Item anggaran"), value: text(item, "id") }))} onChange={setBudgetItemId} /><SelectField label="Pengajuan dana (opsional)" value={fundRequestId} options={requestOptions} onChange={setFundRequestId} /><Field label="Kegiatan" value={activity} onChange={setActivity} /><DatePicker label="Tanggal realisasi" value={realizationDate} onChange={setRealizationDate} /><Field label="Jumlah realisasi" value={requestedAmount} onChange={setRequestedAmount} keyboardType="numeric" /><Field label="Nomor kuitansi (opsional)" value={receiptNumber} onChange={setReceiptNumber} /><Field label="Uraian penggunaan dana" value={description} onChange={setDescription} multiline /><View style={styles.evidence}><Text style={styles.evidenceTitle}>Bukti realisasi</Text><Text style={styles.evidenceHint}>Tambahkan foto, kuitansi, atau PDF. Maksimum lima file.</Text><View style={styles.evidenceActions}><Pressable onPress={() => void choosePhoto("camera")} style={styles.secondary}><Text style={styles.secondaryText}>Kamera</Text></Pressable><Pressable onPress={() => void choosePhoto("library")} style={styles.secondary}><Text style={styles.secondaryText}>Galeri</Text></Pressable><Pressable onPress={() => void chooseDocument()} style={styles.secondary}><Text style={styles.secondaryText}>Dokumen</Text></Pressable></View>{attachments.map((attachment, index) => <Pressable key={`${attachment.uri}-${index}`} onPress={() => setAttachments((current) => current.filter((_, itemIndex) => itemIndex !== index))} style={styles.attachment}><Text style={styles.attachmentText}>{attachment.name}</Text><Text style={styles.remove}>Hapus</Text></Pressable>)}</View><SubmitButton label="Simpan Draft Realisasi" loading={saving || !canCreate || !items.length} onPress={() => void save()} /></Screen></>;
}

function Field({ label, value, onChange, multiline = false, keyboardType = "default" }: { label: string; value: string; onChange: (value: string) => void; multiline?: boolean; keyboardType?: "default" | "numeric" }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={onChange} multiline={multiline} keyboardType={keyboardType} placeholderTextColor={colors.textMuted} style={[styles.input, multiline && styles.area]} /></View>; }
const styles = StyleSheet.create({ heading: { color: colors.text, fontSize: 16, fontWeight: "900" }, hint: { color: colors.warning, fontSize: 12 }, field: { gap: 6 }, label: { color: colors.text, fontSize: 11, fontWeight: "800" }, input: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 10, borderWidth: 1, color: colors.text, minHeight: 44, paddingHorizontal: 12, paddingVertical: 10 }, area: { minHeight: 100, textAlignVertical: "top" }, evidence: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 12, borderWidth: 1, gap: spacing.sm, padding: spacing.md }, evidenceTitle: { color: colors.text, fontSize: 13, fontWeight: "900" }, evidenceHint: { color: colors.textMuted, fontSize: 11 }, evidenceActions: { flexDirection: "row", gap: spacing.sm }, secondary: { alignItems: "center", borderColor: colors.primary, borderRadius: 8, borderWidth: 1, flex: 1, padding: 10 }, secondaryText: { color: colors.primary, fontSize: 10, fontWeight: "900" }, attachment: { alignItems: "center", backgroundColor: "#F4F7FB", borderRadius: 8, flexDirection: "row", justifyContent: "space-between", padding: 10 }, attachmentText: { color: colors.text, flex: 1, fontSize: 11 }, remove: { color: colors.danger, fontSize: 10, fontWeight: "900" } });
