import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useLocalSearchParams } from "expo-router";
import { useState } from "react";
import { Alert, Pressable, StyleSheet, Text, View } from "react-native";
import { TextInput } from "../../src/components/ui/TextInput";

import { useAuth } from "../../src/auth";
import { ErrorState, Header, LoadingState, Screen } from "../../src/components/Screen";
import { DatePicker, ErrorText, SelectField, SubmitButton } from "../../src/components/NativeForm";
import { assignWorkerToBlock, endWorkerBlockAssignment, getBlocks, getFieldWorker, updateFieldWorker } from "../../src/lib/api";
import { text } from "../../src/lib/read";
import { colors, spacing } from "../../src/theme";
import { endAssignmentFormSchema, workerAssignmentFormSchema, workerFormSchema } from "../../src/form-schemas";

export default function WorkerDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { role, session } = useAuth(); const client = useQueryClient(); const query = useQuery({ queryKey: ["field-worker", id], queryFn: () => getFieldWorker(id), enabled: Boolean(role && id) }); const blocks = useQuery({ queryKey: ["blocks", "worker-assignment"], queryFn: () => getBlocks(), enabled: Boolean(role) }); const [saving, setSaving] = useState(false); const [draft, setDraft] = useState<Record<string, string> | null>(null); const [blockId, setBlockId] = useState(""); const [startedAt, setStartedAt] = useState(new Date().toISOString().slice(0, 10));
  if (!role) return null;
  if (query.isLoading) return <><Header role={role} title="Detail Pekerja" /><Screen><LoadingState /></Screen></>;
  if (query.isError || !query.data) return <><Header role={role} title="Detail Pekerja" /><Screen><ErrorState message="Data pekerja tidak dapat dimuat." onRetry={() => query.refetch()} /></Screen></>;
  const values = draft ?? workerValues(query.data.item);
  const canManage = session?.permissions.includes("WORKER_MANAGE") ?? false;
  async function refresh() { await Promise.all([query.refetch(), client.invalidateQueries({ queryKey: ["field-workers"] })]); }
  async function save() { const parsed = workerFormSchema.safeParse(values); if (!parsed.success) return Alert.alert("Periksa data pekerja", parsed.error.issues[0]?.message ?? "Lengkapi data pekerja."); setSaving(true); try { await updateFieldWorker({ id, ...parsed.data }); await refresh(); setDraft(null); } catch (error) { Alert.alert("Tidak dapat menyimpan", error instanceof Error ? error.message : "Periksa koneksi lalu coba lagi."); } finally { setSaving(false); } }
  async function assign() { const parsed = workerAssignmentFormSchema.safeParse({ workerId: id, blockId, startedAt }); if (!parsed.success) return Alert.alert("Periksa penempatan", parsed.error.issues[0]?.message ?? "Pilih blok dan tanggal mulai."); setSaving(true); try { await assignWorkerToBlock(parsed.data); setBlockId(""); await refresh(); } catch (error) { Alert.alert("Tidak dapat menempatkan", error instanceof Error ? error.message : "Coba lagi."); } finally { setSaving(false); } }
  async function end(assignmentId: string) { const parsed = endAssignmentFormSchema.safeParse({ id: assignmentId, endedAt: new Date().toISOString().slice(0, 10) }); if (!parsed.success) return Alert.alert("Tanggal penutupan tidak valid", parsed.error.issues[0]?.message ?? "Gunakan tanggal kalender yang valid."); setSaving(true); try { await endWorkerBlockAssignment(parsed.data); await refresh(); } catch (error) { Alert.alert("Tidak dapat mengakhiri penempatan", error instanceof Error ? error.message : "Coba lagi."); } finally { setSaving(false); } }
  const updateDraft = (key: string, value: string) => setDraft((current) => ({ ...(current ?? values), [key]: value }));
  return <><Header role={role} title="Detail Pekerja" subtitle="Identitas dan riwayat penempatan" /><Screen>{canManage ? <><Field label="Nama lengkap" value={values.fullName} onChange={(value) => updateDraft("fullName", value)} /><Field label="Telepon" value={values.phone} onChange={(value) => updateDraft("phone", value)} /><Field label="Jabatan" value={values.position} onChange={(value) => updateDraft("position", value)} /><SelectField label="Status" value={values.status} onChange={(value) => updateDraft("status", value)} options={[{ label: "Aktif", value: "ACTIVE" }, { label: "Nonaktif", value: "INACTIVE" }]} /><SubmitButton label="Simpan Perubahan" loading={saving} onPress={() => void save()} /></> : <View style={styles.card}><Text style={styles.name}>{text(query.data.item, "fullName")}</Text><Text style={styles.copy}>{text(query.data.item, "position", "Pekerja lapangan")}</Text></View>}<View style={styles.card}><Text style={styles.title}>Riwayat Penempatan</Text>{query.data.assignments.map((assignment) => <View key={text(assignment, "id")} style={styles.assignment}><Text style={styles.copy}>Blok: {text(assignment, "blockId")}</Text><Text style={styles.copy}>{text(assignment, "startedAt")} — {text(assignment, "endedAt", "Aktif")}</Text>{canManage && !text(assignment, "endedAt") ? <Pressable onPress={() => void end(text(assignment, "id"))}><Text style={styles.end}>Akhiri Penempatan</Text></Pressable> : null}</View>)}</View>{canManage ? <View style={styles.card}><Text style={styles.title}>Tempatkan ke Blok</Text><SelectField label="Blok tujuan" value={blockId} onChange={setBlockId} options={(blocks.data?.blocks ?? []).map((block) => ({ label: `${block.code} · ${block.name}`, value: block.id }))} /><DatePicker label="Tanggal mulai" value={startedAt} onChange={setStartedAt} /><SubmitButton label="Simpan Penempatan" loading={saving} onPress={() => void assign()} /></View> : null}</Screen></>;
}

function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <><Text style={styles.label}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={onChange} keyboardType={label === "Telepon" ? "phone-pad" : "default"} style={styles.input} /><ErrorText value={label === "Nama lengkap" && !value.trim() ? "Nama lengkap wajib diisi." : undefined} /></>; }
function workerValues(item: Record<string, unknown>): Record<string, string> { return { fullName: text(item, "fullName"), phone: text(item, "phone"), position: text(item, "position"), status: text(item, "status", "ACTIVE") }; }
const styles = StyleSheet.create({ card: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 13, borderWidth: 1, gap: spacing.sm, padding: spacing.md }, title: { color: colors.text, fontSize: 14, fontWeight: "900" }, name: { color: colors.text, fontSize: 19, fontWeight: "900" }, copy: { color: colors.textMuted, fontSize: 12 }, label: { color: colors.text, fontSize: 11, fontWeight: "800", marginBottom: -spacing.sm }, input: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 10, borderWidth: 1, color: colors.text, minHeight: 44, paddingHorizontal: 12, paddingVertical: 10 }, assignment: { borderTopColor: colors.border, borderTopWidth: 1, gap: 3, paddingTop: spacing.sm }, end: { color: colors.danger, fontSize: 11, fontWeight: "900", marginTop: 3 } });
