import { z } from "zod";

import { isValidCalendarDate } from "./date-validation";

const optionalUuid = z.union([z.string().uuid("Pilih blok yang valid."), z.literal("")]).transform((value) => value || undefined).optional();
const optionalUuidValue = z.union([z.string().uuid("Pilih pilihan yang valid."), z.literal("")]).transform((value) => value || undefined).optional();
const optionalCalendarDate = z.union([z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Gunakan format YYYY-MM-DD.").refine(isValidCalendarDate, "Tanggal tidak valid."), z.literal("")]).transform((value) => value || undefined).optional();
const validCalendarDate = (message: string) => z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Gunakan format YYYY-MM-DD.").refine(isValidCalendarDate, message);

export const loginSchema = z.object({ email: z.string().trim().email("Masukkan email yang valid."), password: z.string().min(1, "Masukkan kata sandi.") });
export const forgotPasswordSchema = z.object({ email: z.string().trim().min(1, "Masukkan email Anda.").email("Masukkan email yang valid.").max(255, "Email maksimal 255 karakter.") });
export const profileSchema = z.object({ name: z.string().trim().min(2, "Nama minimal 2 karakter."), phone: z.string().trim().min(6, "Nomor telepon minimal 6 karakter.").max(30, "Nomor telepon maksimal 30 karakter.").or(z.literal("")), image: z.string().trim().url("Masukkan URL gambar yang valid, termasuk https://.").max(500, "URL gambar maksimal 500 karakter.").or(z.literal("")) });
export const passwordSchema = z.object({ currentPassword: z.string().min(1, "Kata sandi saat ini wajib diisi."), newPassword: z.string().min(8, "Kata sandi baru minimal 8 karakter."), confirmPassword: z.string().min(1, "Konfirmasi kata sandi wajib diisi."), revokeOtherSessions: z.enum(["yes", "no"]) }).refine((value) => value.newPassword === value.confirmPassword, { path: ["confirmPassword"], message: "Konfirmasi kata sandi tidak sama." });

export const businessActorFormSchema = z.object({ actorType: z.enum(["INDIVIDUAL", "COMPANY"], { required_error: "Pilih jenis pelaku usaha." }), name: z.string().trim().min(1, "Nama wajib diisi.").max(160, "Nama maksimal 160 karakter."), representativeName: z.string().max(160, "Nama perwakilan maksimal 160 karakter.").optional(), contact: z.string().max(64, "Kontak maksimal 64 karakter.").optional(), address: z.string().max(5000, "Alamat maksimal 5.000 karakter.").optional(), notes: z.string().max(5000, "Catatan maksimal 5.000 karakter.").optional() });
export const budgetPeriodFormSchema = z.object({ periodKey: z.string().trim().regex(/^\d{4}-(0[1-9]|1[0-2])$/, "Gunakan format YYYY-MM, misalnya 2026-08."), openingBalance: z.coerce.number({ message: "Saldo awal harus berupa angka." }).int("Saldo awal harus bilangan bulat.").min(0, "Saldo awal tidak boleh negatif.").max(Number.MAX_SAFE_INTEGER, "Saldo awal terlalu besar."), estimatedIncome: z.coerce.number({ message: "Pendapatan estimasi harus berupa angka." }).int("Pendapatan estimasi harus bilangan bulat.").min(0, "Pendapatan estimasi tidak boleh negatif.").max(Number.MAX_SAFE_INTEGER, "Pendapatan estimasi terlalu besar.") });
export const dueFormSchema = z.object({ excavatorId: z.string().uuid("Pilih unit alat berat."), payerName: z.string().trim().min(1, "Nama pembayar wajib diisi.").max(160, "Nama pembayar maksimal 160 karakter."), amountDue: z.coerce.number({ message: "Masukkan jumlah dengan angka." }).int("Masukkan bilangan bulat.").refine((value): boolean => value === 10_000_000, "Iuran bulanan ditetapkan Rp10.000.000."), dueDate: validCalendarDate("Tanggal jatuh tempo tidak valid.") });
export const excavatorFormSchema = z.object({ unitCode: z.string().trim().min(1, "Kode unit wajib diisi.").max(64, "Kode unit maksimal 64 karakter."), brand: z.string().trim().min(1, "Merek wajib diisi.").max(100, "Merek maksimal 100 karakter."), model: z.string().trim().min(1, "Model wajib diisi.").max(100, "Model maksimal 100 karakter."), businessActorId: z.string().uuid("Pilih pelaku usaha."), operatorName: z.string().trim().max(160, "Nama operator maksimal 160 karakter.").optional(), currentBlockId: optionalUuid, entryDate: optionalCalendarDate, notes: z.string().trim().max(5000, "Catatan maksimal 5.000 karakter.").optional() }).superRefine((value, context) => { if (value.currentBlockId && !value.entryDate) context.addIssue({ code: "custom", path: ["entryDate"], message: "Isi tanggal masuk jika blok saat ini dipilih." }); if (!value.currentBlockId && value.entryDate) context.addIssue({ code: "custom", path: ["currentBlockId"], message: "Pilih blok jika tanggal masuk diisi." }); });
export const excavatorEditFormSchema = z.object({ unitCode: z.string().trim().min(1, "Kode unit wajib diisi.").max(64, "Kode unit maksimal 64 karakter."), brand: z.string().trim().min(1, "Merek wajib diisi.").max(100, "Merek maksimal 100 karakter."), model: z.string().trim().min(1, "Model wajib diisi.").max(100, "Model maksimal 100 karakter."), operatorName: z.string().trim().max(160, "Nama operator maksimal 160 karakter.").optional() });
export const excavatorMovementFormSchema = z.object({ movementType: z.enum(["ENTRY", "TRANSFER", "EXIT"]), toBlockId: optionalUuidValue, notes: z.string().trim().max(5000, "Catatan pergerakan maksimal 5.000 karakter.").optional() }).superRefine((value, context) => { if (value.movementType !== "EXIT" && !value.toBlockId) context.addIssue({ code: "custom", path: ["toBlockId"], message: "Pilih blok tujuan untuk masuk atau transfer." }); });
export const informationFormSchema = z.object({ blockId: z.string().uuid("Pilih blok yang valid.").optional(), reportedAt: validCalendarDate("Tanggal laporan tidak valid.").optional(), category: z.enum(["ACTIVITY", "COMPLAINT", "INCIDENT", "PROSPECTIVE_MANAGER", "NOTICE"], { required_error: "Pilih jenis informasi." }), priority: z.enum(["LOW", "MEDIUM", "HIGH", "URGENT"], { required_error: "Pilih prioritas informasi." }), description: z.string().trim().min(1, "Deskripsi wajib diisi.").max(10000, "Deskripsi maksimal 10.000 karakter."), documentation: z.string().max(10000, "Catatan dokumentasi maksimal 10.000 karakter.").optional() });
export const informationFollowUpFormSchema = z.object({ note: z.string().trim().min(1, "Catatan tindak lanjut wajib diisi.").max(5000, "Catatan tindak lanjut maksimal 5.000 karakter.") });
export const informationTransitionFormSchema = z.object({ status: z.enum(["NEW", "RECEIVED", "IN_PROGRESS", "COMPLETED", "CLOSED"]), followUp: z.string().trim().min(1, "Catatan tindakan wajib diisi.").max(10000, "Catatan tindakan maksimal 10.000 karakter.") });
export const inspectionFormSchema = z.object({ blockId: z.string().uuid("Pilih blok pemeriksaan."), inspectedAt: validCalendarDate("Tanggal pemeriksaan tidak valid.").optional(), excavatorCount: z.coerce.number({ message: "Jumlah alat berat harus berupa angka." }).int("Jumlah alat berat harus bilangan bulat.").min(0, "Jumlah alat berat tidak boleh negatif.").max(100000, "Jumlah alat berat maksimal 100.000."), workerCount: z.coerce.number({ message: "Jumlah pekerja harus berupa angka." }).int("Jumlah pekerja harus berupa bilangan bulat.").min(0, "Jumlah pekerja tidak boleh negatif.").max(1000000, "Jumlah pekerja maksimal 1.000.000."), condition: z.string().trim().min(1, "Pilih kondisi blok."), conditionRoad: z.string().trim().min(1, "Pilih kondisi jalan."), conditionEnvironment: z.string().trim().min(1, "Pilih kondisi lingkungan."), conditionActivity: z.string().trim().min(1, "Pilih kondisi aktivitas."), findings: z.string().max(10000, "Temuan maksimal 10.000 karakter.").optional(), notes: z.string().max(10000, "Catatan maksimal 10.000 karakter.").optional() });
export const paymentFormSchema = z.object({ payerName: z.string().trim().min(1, "Nama pembayar wajib diisi.").max(160, "Nama pembayar maksimal 160 karakter."), paymentDate: validCalendarDate("Tanggal pembayaran tidak valid."), amount: z.coerce.number({ message: "Masukkan jumlah dengan angka." }).int("Masukkan bilangan bulat.").positive("Jumlah harus lebih dari 0.").max(Number.MAX_SAFE_INTEGER, "Jumlah pembayaran terlalu besar."), method: z.enum(["CASH", "BANK_TRANSFER", "QRIS", "OTHER"], { required_error: "Pilih metode pembayaran." }), notes: z.string().max(5000, "Catatan maksimal 5.000 karakter.").optional() });
export const paymentVerificationFormSchema = z.object({ verificationStatus: z.enum(["CONFIRMED", "DISCREPANCY"]), verifiedAt: validCalendarDate("Tanggal verifikasi tidak valid."), notes: z.string().max(5000, "Catatan maksimal 5.000 karakter.").optional() }).superRefine((values, context) => { if (values.verificationStatus === "DISCREPANCY" && !values.notes?.trim()) context.addIssue({ code: "custom", path: ["notes"], message: "Catatan wajib untuk selisih." }); });
export const transactionFormSchema = z.object({ transactionAt: validCalendarDate("Tanggal transaksi tidak valid."), transactionType: z.enum(["CASH_IN", "CASH_OUT"], { required_error: "Pilih jenis transaksi." }), categoryId: z.string().uuid("Pilih kategori yang valid.").optional(), amount: z.coerce.number({ message: "Masukkan jumlah dengan angka." }).int("Masukkan bilangan bulat.").positive("Jumlah harus lebih dari 0.").max(Number.MAX_SAFE_INTEGER, "Jumlah transaksi terlalu besar."), description: z.string().trim().min(1, "Uraian transaksi wajib diisi.").max(10000, "Uraian transaksi maksimal 10.000 karakter.") });

const wholeNonNegative = (label: string) => z.coerce.number({ message: `${label} harus berupa angka.` }).int(`${label} harus bilangan bulat.`).min(0, `${label} tidak boleh negatif.`).max(Number.MAX_SAFE_INTEGER, `${label} terlalu besar.`);

export const fieldAssignmentFormSchema = z.object({ blockId: z.string().uuid("Pilih blok."), fieldOfficerId: z.string().uuid("Pilih petugas lapangan."), startedAt: validCalendarDate("Tanggal mulai tidak valid.") });
export const endAssignmentFormSchema = z.object({ id: z.string().uuid("Penugasan tidak valid."), endedAt: validCalendarDate("Tanggal selesai tidak valid.") });
export const workerFormSchema = z.object({ fullName: z.string().trim().min(1, "Nama lengkap wajib diisi.").max(160, "Nama lengkap maksimal 160 karakter."), phone: z.string().trim().max(64, "Nomor telepon maksimal 64 karakter.").optional(), position: z.string().trim().max(160, "Jabatan maksimal 160 karakter.").optional(), status: z.enum(["ACTIVE", "INACTIVE"], { required_error: "Pilih status pekerja." }), notes: z.string().trim().max(5000, "Catatan maksimal 5.000 karakter.").optional() });
export const workerAssignmentFormSchema = z.object({ workerId: z.string().uuid("Pekerja tidak valid."), blockId: z.string().uuid("Pilih blok."), startedAt: validCalendarDate("Tanggal mulai tidak valid.") });
export const taskFormSchema = z.object({ blockId: z.string().uuid("Pilih blok tugas."), assignedFieldOfficerId: z.string().uuid("Pilih petugas lapangan."), assignedWorkerId: optionalUuidValue, title: z.string().trim().min(1, "Judul tugas wajib diisi.").max(255, "Judul tugas maksimal 255 karakter."), description: z.string().trim().max(10000, "Deskripsi maksimal 10.000 karakter.").optional(), priority: z.enum(["LOW", "MEDIUM", "HIGH", "URGENT"], { required_error: "Pilih prioritas tugas." }), dueDate: optionalCalendarDate });
export const budgetCategoryFormSchema = z.object({ name: z.string().trim().min(1, "Nama kategori wajib diisi.").max(160, "Nama kategori maksimal 160 karakter."), sortOrder: wholeNonNegative("Urutan").max(10000, "Urutan maksimal 10.000.") });
export const budgetSubcategoryFormSchema = z.object({ categoryId: z.string().uuid("Pilih kategori."), name: z.string().trim().min(1, "Nama subkategori wajib diisi.").max(160, "Nama subkategori maksimal 160 karakter."), sortOrder: wholeNonNegative("Urutan").max(10000, "Urutan maksimal 10.000.") });
export const financeCategoryFormSchema = z.object({ name: z.string().trim().min(1, "Nama kategori wajib diisi.").max(160, "Nama kategori maksimal 160 karakter."), transactionType: z.enum(["CASH_IN", "CASH_OUT"], { required_error: "Pilih jenis transaksi." }), sortOrder: wholeNonNegative("Urutan").max(10000, "Urutan maksimal 10.000.") });
export const fundRequestFormSchema = z.object({ budgetPeriodId: z.string().uuid("Pilih periode anggaran."), budgetCategoryId: z.string().uuid("Pilih kategori anggaran."), budgetSubcategoryId: optionalUuidValue, blockId: optionalUuidValue, title: z.string().trim().min(1, "Judul pengajuan wajib diisi.").max(255, "Judul pengajuan maksimal 255 karakter."), description: z.string().trim().min(1, "Deskripsi kegiatan wajib diisi.").max(10000, "Deskripsi kegiatan maksimal 10.000 karakter."), amount: z.coerce.number({ message: "Jumlah pengajuan harus berupa angka." }).int("Jumlah pengajuan harus bilangan bulat.").positive("Jumlah pengajuan harus lebih dari 0.").max(Number.MAX_SAFE_INTEGER, "Jumlah pengajuan terlalu besar."), requestedAt: validCalendarDate("Tanggal pengajuan tidak valid.") });
export const fundRequestCorrectionFormSchema = fundRequestFormSchema.extend({ reason: z.string().trim().min(1, "Alasan koreksi wajib diisi.").max(5000, "Alasan koreksi maksimal 5.000 karakter.") });
export const realizationFormSchema = z.object({ budgetItemId: z.string().uuid("Pilih item anggaran."), fundRequestId: optionalUuidValue, activity: z.string().trim().min(1, "Kegiatan wajib diisi.").max(255, "Kegiatan maksimal 255 karakter."), realizationDate: validCalendarDate("Tanggal realisasi tidak valid."), requestedAmount: z.coerce.number({ message: "Jumlah realisasi harus berupa angka." }).int("Jumlah realisasi harus bilangan bulat.").positive("Jumlah realisasi harus lebih dari 0.").max(Number.MAX_SAFE_INTEGER, "Jumlah realisasi terlalu besar."), receiptNumber: z.string().trim().max(100, "Nomor kuitansi maksimal 100 karakter.").optional(), description: z.string().trim().min(1, "Uraian penggunaan dana wajib diisi.").max(10000, "Uraian penggunaan dana maksimal 10.000 karakter.") });
export const realizationCorrectionFormSchema = realizationFormSchema.extend({ reason: z.string().trim().min(1, "Alasan koreksi wajib diisi.").max(5000, "Alasan koreksi maksimal 5.000 karakter.") });
export const budgetItemFormSchema = z.object({ groupId: optionalUuidValue, subcategoryId: optionalUuidValue, name: z.string().trim().min(1, "Nama item wajib diisi.").max(255, "Nama item maksimal 255 karakter."), allocatedAmount: wholeNonNegative("Jumlah alokasi"), notes: z.string().trim().max(5000, "Catatan maksimal 5.000 karakter.").optional(), revisionReason: z.string().trim().max(5000, "Alasan revisi maksimal 5.000 karakter.").optional() });
export const budgetCategoryPeriodFormSchema = z.object({ periodId: z.string().uuid("Periode anggaran tidak valid."), categoryId: z.string().uuid("Pilih kategori aktif.") });
export const workflowDecisionFormSchema = z.object({ notes: z.string().trim().max(5000, "Catatan keputusan maksimal 5.000 karakter.").optional() });
export const requiredWorkflowDecisionFormSchema = z.object({ notes: z.string().trim().min(1, "Catatan keputusan wajib diisi.").max(5000, "Catatan keputusan maksimal 5.000 karakter.") });
export const reversalFormSchema = z.object({ reason: z.string().trim().min(1, "Alasan pembalikan wajib diisi.").max(5000, "Alasan pembalikan maksimal 5.000 karakter.") });
export const adminCreateUserFormSchema = z.object({ name: z.string().trim().min(2, "Nama lengkap minimal 2 karakter.").max(160, "Nama lengkap maksimal 160 karakter."), email: z.string().trim().email("Masukkan email yang valid.").max(255, "Email maksimal 255 karakter."), roleId: z.string().trim().min(1, "Peran pengguna wajib dipilih.").max(64, "Peran pengguna tidak valid."), password: z.string().min(8, "Kata sandi minimal 8 karakter.").max(128, "Kata sandi maksimal 128 karakter.") });
export const adminInviteFormSchema = adminCreateUserFormSchema.omit({ password: true });
export const settingsFormSchema = z.object({ organizationName: z.string().trim().min(2, "Nama organisasi wajib diisi minimal 2 karakter.").max(160, "Nama organisasi maksimal 160 karakter."), organizationPhone: z.string().trim().max(30, "Nomor telepon organisasi maksimal 30 karakter."), monthlyDueAmount: wholeNonNegative("Iuran bulanan").positive("Iuran bulanan harus lebih dari 0.").max(999999999, "Iuran bulanan terlalu besar."), roadEntryDueAmount: wholeNonNegative("Iuran jalan").positive("Iuran jalan harus lebih dari 0.").max(999999999, "Iuran jalan terlalu besar."), monthlyDueDay: wholeNonNegative("Tanggal jatuh tempo").min(1, "Tanggal jatuh tempo minimal 1.").max(10, "Tanggal jatuh tempo maksimal 10."), periodKey: z.string().trim().regex(/^\d{4}-(0[1-9]|1[0-2])$/, "Periode aktif harus menggunakan format YYYY-MM.") });

export type LoginValues = z.infer<typeof loginSchema>;
export type ProfileValues = z.infer<typeof profileSchema>;
export type PasswordValues = z.infer<typeof passwordSchema>;
