import Link from "next/link";
import { ArrowRight, Coins } from "lucide-react";

import { PageContainer } from "@/components/app-shell/page-container";
import { ActionForm } from "@/components/shared/action-form";
import { EmptyState } from "@/components/shared/empty-state";
import { MoneyDisplay } from "@/components/shared/money-display";
import { PageHeader } from "@/components/shared/page-header";
import { ResponsiveDataView } from "@/components/shared/responsive-data-view";
import { StatusBadge } from "@/components/shared/status-badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { getBlocks } from "@/src/features/blocks/actions";
import { DUE_AMOUNTS_RUPIAH } from "@/src/features/dues/config";
import { createDueAction, generateMonthlyDuesAction } from "./_actions";
import { getDuesPage, getReceivableReconciliation } from "@/src/features/dues/service";
import { getExcavators } from "@/src/features/excavators/service";
import { hasPermission, requirePermission } from "@/src/lib/permissions/authorize";
import { PERMISSIONS } from "@/src/lib/permissions/constants";

export const dynamic = "force-dynamic";

type DuesPageProps = { searchParams: Promise<{ status?: string; dueType?: string; periodKey?: string }> };
const statuses = ["UNPAID", "PARTIAL", "PAID"] as const;
const types = ["MONTHLY", "ROAD_ENTRY"] as const;

export default async function DuesPage({ searchParams }: DuesPageProps) {
  const params = await searchParams;
  const session = await requirePermission(PERMISSIONS.DUES_READ);
  const canManage = await hasPermission(session.user.id, PERMISSIONS.DUES_MANAGE);
  const status = statuses.includes(params.status as (typeof statuses)[number]) ? params.status as (typeof statuses)[number] : undefined;
  const dueType = types.includes(params.dueType as (typeof types)[number]) ? params.dueType as (typeof types)[number] : undefined;
  const filters = { status, dueType, periodKey: /^\d{4}-(0[1-9]|1[0-2])$/.test(params.periodKey ?? "") ? params.periodKey : undefined };
  const [result, reconciliation, excavators, blocks] = await Promise.all([getDuesPage(filters), getReceivableReconciliation(filters), canManage ? getExcavators() : Promise.resolve([]), canManage ? getBlocks() : Promise.resolve([])]);
  const blockById = new Map(blocks.map((item) => [item.id, `${item.code} · ${item.name}`]));

  return <PageContainer><div className="space-y-8">
    <PageHeader breadcrumbs={[{ label: "Dashboard", href: "/dashboard" }, { label: "Dues & payments" }]} description="Track excavator obligations, receivables, and recorded payments without treating unpaid dues as cash." eyebrow="Finance" title="Dues & payments" actions={<Button asChild><Link href="/dashboard/payments">Payment register</Link></Button>} />
    <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Summary label="Obligation" value={reconciliation.obligationTotal} /><Summary label="Recorded paid" value={reconciliation.recordedPaidTotal} /><Summary label="Receivable" value={reconciliation.receivableTotal} /><Card className="shadow-sm"><CardContent className="p-5"><p className="text-xs uppercase tracking-[0.16em] text-muted-foreground">Reconciliation</p><p className="mt-3"><StatusBadge status={reconciliation.reconciled ? "PAID" : "URGENT"} label={reconciliation.reconciled ? "Reconciled" : "Needs review"} /></p><p className="mt-2 text-xs text-muted-foreground">{reconciliation.counts.total} dues · {reconciliation.counts.unpaid} unpaid</p></CardContent></Card></section>
    <form className="grid gap-3 border-y border-border py-4 sm:grid-cols-2 lg:grid-cols-[180px_180px_180px_auto]" method="get"><select aria-label="Filter status" className="h-10 border-b border-input bg-transparent text-sm" defaultValue={status ?? ""} name="status"><option value="">All statuses</option>{statuses.map((item) => <option key={item}>{item}</option>)}</select><select aria-label="Filter due type" className="h-10 border-b border-input bg-transparent text-sm" defaultValue={dueType ?? ""} name="dueType"><option value="">All due types</option>{types.map((item) => <option key={item}>{item.replaceAll("_", " ")}</option>)}</select><input aria-label="Filter period" className="h-10 border-b border-input bg-transparent text-sm" defaultValue={params.periodKey ?? ""} name="periodKey" placeholder="Period YYYY-MM" /><Button type="submit" variant="outline">Filter</Button></form>
    {canManage ? <section className="grid gap-8 lg:grid-cols-[1fr_360px]"><Card className="shadow-sm"><CardHeader><CardTitle className="font-heading text-xl uppercase tracking-wide">Generate monthly dues</CardTitle></CardHeader><CardContent><ActionForm action={generateMonthlyDuesAction} className="flex flex-col gap-3 sm:flex-row sm:items-end"><label className="flex-1 space-y-2 text-sm"><span className="text-xs uppercase tracking-[0.16em] text-muted-foreground">Period</span><input className="h-10 w-full border-b border-input bg-transparent text-sm" name="periodKey" placeholder="2026-08" required /></label><Button type="submit">Generate dues</Button></ActionForm><p className="mt-3 text-xs text-muted-foreground">Monthly obligations use the configured Rp10.000.000 amount per eligible excavator.</p></CardContent></Card><Card className="shadow-sm"><CardHeader><CardTitle className="font-heading text-xl uppercase tracking-wide">Add manual due</CardTitle></CardHeader><CardContent><ActionForm action={createDueAction} className="space-y-3"><select className="h-10 w-full border-b border-input bg-transparent text-sm" name="excavatorId" required><option value="">Select excavator</option>{excavators.map((item) => <option key={item.id} value={item.id}>{item.unitCode} · {item.operatorName ?? "No operator"}</option>)}</select><select className="h-10 w-full border-b border-input bg-transparent text-sm" defaultValue="MONTHLY" name="dueType"><option value="MONTHLY">Monthly</option><option value="ROAD_ENTRY">Road entry</option></select><input className="h-10 w-full border-b border-input bg-transparent text-sm" name="payerName" placeholder="Payer name" required /><input className="h-10 w-full border-b border-input bg-transparent text-sm" name="referenceKey" placeholder="Reference, e.g. 2026-08" required /><input className="h-10 w-full border-b border-input bg-transparent text-sm" defaultValue={DUE_AMOUNTS_RUPIAH.MONTHLY} name="amountDue" type="number" required /><input className="h-10 w-full border-b border-input bg-transparent text-sm" name="dueDate" type="date" required /><input className="h-10 w-full border-b border-input bg-transparent text-sm" name="sourceMovementId" placeholder="Entry movement ID (road entry only)" /><Button type="submit">Create due</Button></ActionForm></CardContent></Card></section> : null}
    <ResponsiveDataView rows={result.rows} getRowKey={(row) => row.due.id} desktopHeader={<><th className="px-5 py-4">Pembayar</th><th className="px-5 py-4">Jenis</th><th className="px-5 py-4">Blok</th><th className="px-5 py-4">Kewajiban</th><th className="px-5 py-4">Status</th><th className="px-5 py-4 text-right">Aksi</th></>} desktop={(row) => <><td className="px-5 py-5"><p className="font-semibold">{row.due.payerName}</p><p className="mt-1 text-xs text-muted-foreground">{row.excavator.unitCode} · {row.due.referenceKey}</p></td><td className="px-5 py-5"><StatusBadge status={row.due.dueType} /></td><td className="px-5 py-5 text-muted-foreground">{row.excavator.currentBlockId ? blockById.get(row.excavator.currentBlockId) ?? "Blok terkait" : "Belum ditugaskan"}</td><td className="px-5 py-5"><MoneyDisplay value={row.due.amountDue} /><p className="mt-1 text-xs text-muted-foreground">Dibayar <MoneyDisplay value={row.due.amountPaid} /></p></td><td className="px-5 py-5"><StatusBadge status={row.due.status} /></td><td className="px-5 py-5 text-right"><Button asChild size="xs" variant="ghost"><Link href={`/dashboard/dues/${row.due.id}`}>Buka <ArrowRight aria-hidden="true" /></Link></Button></td></>} mobile={(row) => <div className="rounded-xl border border-border bg-card p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{row.due.payerName}</p><p className="mt-1 text-xs text-muted-foreground">{row.excavator.unitCode} · {row.due.referenceKey}</p></div><StatusBadge status={row.due.status} /></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-xs text-muted-foreground">Jenis</dt><dd className="mt-1"><StatusBadge status={row.due.dueType} /></dd></div><div><dt className="text-xs text-muted-foreground">Kewajiban</dt><dd className="mt-1 font-semibold"><MoneyDisplay value={row.due.amountDue} /></dd></div></dl><Button asChild className="mt-4 w-full" variant="outline"><Link href={`/dashboard/dues/${row.due.id}`}>Buka detail</Link></Button></div>} empty={<section className="rounded-xl border border-border bg-card shadow-sm"><EmptyState description="Buat iuran pertama atau ubah filter pencarian." icon={Coins} title="Belum ada iuran" /></section>} />
  </div></PageContainer>;
}

function Summary({ label, value }: { label: string; value: number }) { return <Card className="shadow-sm"><CardContent className="p-5"><p className="text-xs uppercase tracking-[0.16em] text-muted-foreground">{label}</p><p className="mt-3 text-lg font-semibold"><MoneyDisplay value={value} /></p></CardContent></Card>; }
