import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useLocalSearchParams } from "expo-router";
import { useEffect, useState } from "react";
import { Alert, Image, Linking, Pressable, StyleSheet, Text, View } from "react-native";
import { TextInput } from "../../src/components/ui/TextInput";

import { useAuth } from "../../src/auth";
import { BottomNav, ErrorState, Header, LoadingState, Screen } from "../../src/components/Screen";
import { RowCard, StatusPill } from "../../src/components/PimpinanPrimitives";
import { addDailyInformationAttachment, addDailyInformationFollowUp, createDailyInformationAttachmentUploadUrl, getDailyInformationAttachmentDownloadUrl, getInformationItem, transitionDailyInformation } from "../../src/lib/api";
import { optimizeImage, pickImagesFromCameraOrLibrary, uploadOptimizedImage } from "../../src/lib/media";
import { showActionError } from "../../src/lib/feedback";
import { text } from "../../src/lib/read";
import { colors, spacing } from "../../src/theme";
import { informationFollowUpFormSchema, informationTransitionFormSchema } from "../../src/form-schemas";

const transitions: Record<string, string[]> = { NEW: ["RECEIVED"], RECEIVED: ["IN_PROGRESS"], IN_PROGRESS: ["COMPLETED", "CLOSED"] };

export default function InformationDetail() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { role, session } = useAuth(); const client = useQueryClient(); const [note, setNote] = useState(""); const [uploading, setUploading] = useState(false); const [attachmentUrls, setAttachmentUrls] = useState<Record<string, string>>({});
  const query = useQuery({ queryKey: ["information", id], queryFn: () => getInformationItem(id), enabled: Boolean(role && id) });
  useEffect(() => { if (!query.data) return; void Promise.all(query.data.attachments.map(async (entry) => { const storageKey = text(entry, "storageKey"); const result = await getDailyInformationAttachmentDownloadUrl({ id, storageKey }) as { downloadUrl: string }; return [storageKey, result.downloadUrl] as const; })).then((entries) => setAttachmentUrls(Object.fromEntries(entries))).catch(() => setAttachmentUrls({})); }, [id, query.data]);
  if (!role) return null;
  if (query.isLoading) return <><Header role={role} title="Detail Informasi" /><Screen><LoadingState /></Screen></>;
  if (query.isError || !query.data) return <><Header role={role} title="Detail Informasi" /><Screen><ErrorState message="Detail informasi tidak dapat dimuat." onRetry={() => query.refetch()} /></Screen></>;
  const item = query.data.item; const canUpdate = session?.permissions.includes("DAILY_INFO_UPDATE"); const status = text(item, "status");
  const refresh = async () => { await client.invalidateQueries({ queryKey: ["information", id] }); await client.invalidateQueries({ queryKey: ["information"] }); };
  async function followUp() { const parsed = informationFollowUpFormSchema.safeParse({ note }); if (!parsed.success) return Alert.alert("Catatan wajib diisi", parsed.error.issues[0]?.message ?? "Masukkan tindak lanjut sebelum menyimpan."); try { await addDailyInformationFollowUp({ id, ...parsed.data }); setNote(""); await refresh(); } catch (error) { Alert.alert("Tidak dapat menyimpan", error instanceof Error ? error.message : "Coba lagi."); } }
  async function transition(next: string) { const parsed = informationTransitionFormSchema.safeParse({ status: next, followUp: note }); if (!parsed.success) return Alert.alert("Tindak lanjut wajib diisi", parsed.error.issues[0]?.message ?? "Masukkan catatan tindakan sebelum mengubah status."); try { await transitionDailyInformation({ id, ...parsed.data }); setNote(""); await refresh(); } catch (error) { Alert.alert("Tidak dapat memperbarui", error instanceof Error ? error.message : "Coba lagi."); } }
  async function addPhoto() { try { const selected = await pickImagesFromCameraOrLibrary({ title: "Foto informasi", cameraPermissionMessage: "Izinkan kamera untuk menambahkan foto informasi.", libraryPermissionMessage: "Izinkan galeri untuk memilih foto informasi." }); const asset = selected[0]; if (!asset) return; setUploading(true); const image = await optimizeImage(asset, `informasi-${Date.now()}`); const upload = await createDailyInformationAttachmentUploadUrl({ id, contentType: image.contentType, sizeBytes: image.sizeBytes, originalName: image.name }) as { key: string; uploadUrl: string }; await uploadOptimizedImage(upload.uploadUrl, image); await addDailyInformationAttachment({ id, storageKey: upload.key, contentType: image.contentType, sizeBytes: image.sizeBytes }); await refresh(); } catch (error) { Alert.alert("Tidak dapat menambah foto", error instanceof Error ? error.message : "Coba lagi."); } finally { setUploading(false); } }
  return <><Header role={role} title="Detail Informasi" subtitle="Tindak lanjut laporan lapangan" /><Screen><View style={styles.hero}><Text style={styles.category}>{text(item, "category")}</Text><Text style={styles.description}>{text(item, "description")}</Text><StatusPill tone={text(item, "priority") === "URGENT" ? "red" : "orange"}>{status}</StatusPill><Text style={styles.meta}>Prioritas: {text(item, "priority")} · {text(item, "reportedAt")}</Text></View><View style={styles.card}><Text style={styles.label}>Dokumentasi</Text><Text style={styles.value}>{text(item, "documentation", "Tidak ada dokumentasi")}</Text><Text style={styles.label}>Lokasi GPS</Text><Text style={styles.value}>{text(item, "latitude") && text(item, "longitude") ? `${text(item, "latitude")}, ${text(item, "longitude")}` : "Lokasi tidak direkam"}</Text><Text style={styles.label}>Tindak lanjut terakhir</Text><Text style={styles.value}>{text(item, "followUp", "Belum ada tindak lanjut")}</Text></View>{canUpdate ? <View style={styles.card}><Text style={styles.title}>Tindak Lanjut</Text><TextInput value={note} onChangeText={setNote} placeholder="Tambahkan catatan tindak lanjut" multiline style={styles.input} /><Pressable onPress={() => void followUp()} style={styles.primary}><Text style={styles.primaryText}>Simpan Tindak Lanjut</Text></Pressable>{(transitions[status] ?? []).map((next) => <Pressable key={next} onPress={() => void transition(next)} style={styles.secondary}><Text style={styles.secondaryText}>Ubah status ke {next}</Text></Pressable>)}<Pressable disabled={uploading} onPress={() => void addPhoto()} style={styles.secondary}><Text style={styles.secondaryText}>{uploading ? "Mengunggah foto…" : "Tambah Foto Lampiran"}</Text></Pressable></View> : null}<View style={styles.card}><Text style={styles.title}>Riwayat Tindak Lanjut</Text>{query.data.followUps.map((entry) => <RowCard key={text(entry, "id")} title={text(entry, "note")} meta={text(entry, "createdAt")} />)}</View><View style={styles.card}><Text style={styles.title}>Lampiran</Text>{query.data.attachments.map((entry) => { const storageKey = text(entry, "storageKey"); const url = attachmentUrls[storageKey]; const content = <>{url && text(entry, "contentType").startsWith("image/") ? <Image alt="Lampiran informasi" source={{ uri: url }} style={styles.preview} /> : <Text style={styles.attachmentMarker}>FILE</Text>}<Text style={styles.value}>{text(entry, "contentType")} · {text(entry, "sizeBytes")} bytes · {url ? "Buka" : "Menyiapkan"}</Text></>; return url ? <Pressable key={text(entry, "id")} onPress={() => Linking.openURL(url).catch((error) => showActionError(error, "Lampiran tidak dapat dibuka."))} style={styles.attachment}>{content}</Pressable> : <View key={text(entry, "id")} style={styles.attachment}>{content}</View>; })}</View></Screen><BottomNav current="information" role={role} /></>;
}

const styles = StyleSheet.create({ hero: { backgroundColor: colors.primaryDark, borderRadius: 15, gap: 8, padding: spacing.lg }, category: { color: "#DCE7FF", fontSize: 10, fontWeight: "900" }, description: { color: "#FFFFFF", fontSize: 17, fontWeight: "900" }, meta: { color: "#DCE7FF", fontSize: 10 }, card: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 13, borderWidth: 1, gap: spacing.sm, padding: spacing.md }, title: { color: colors.text, fontSize: 14, fontWeight: "900" }, label: { color: colors.textMuted, fontSize: 10, fontWeight: "800" }, value: { color: colors.text, fontSize: 12 }, input: { borderColor: colors.border, borderRadius: 9, borderWidth: 1, color: colors.text, minHeight: 75, padding: 10, textAlignVertical: "top" }, primary: { alignItems: "center", backgroundColor: colors.primary, borderRadius: 9, padding: 12 }, primaryText: { color: "#FFFFFF", fontSize: 11, fontWeight: "900" }, secondary: { alignItems: "center", borderColor: colors.primary, borderRadius: 9, borderWidth: 1, padding: 11 }, secondaryText: { color: colors.primary, fontSize: 11, fontWeight: "900" }, attachment: { alignItems: "center", flexDirection: "row", gap: 9 }, attachmentMarker: { backgroundColor: "#EAF1FF", color: colors.primary, fontSize: 9, fontWeight: "900", padding: 8 }, preview: { borderRadius: 6, height: 42, width: 42 } });
