import { zodResolver } from "@hookform/resolvers/zod";
import { useQuery } from "@tanstack/react-query";
import * as ImagePicker from "expo-image-picker";
import * as Location from "expo-location";
import { useRouter } from "expo-router";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { Alert, Image, Pressable, StyleSheet, Text, View } from "react-native";
import { z } from "zod";

import { useAuth } from "../../src/auth";
import { Header, Screen } from "../../src/components/Screen";
import { DateField, InputField, SelectField, SubmitButton } from "../../src/components/NativeForm";
import { createDailyInformation, createDailyInformationAttachmentUploadUrl, getBlocks } from "../../src/lib/api";
import { colors, spacing } from "../../src/theme";

const schema = z.object({ blockId: z.string().uuid().optional(), reportedAt: z.string().optional(), category: z.enum(["ACTIVITY", "COMPLAINT", "INCIDENT", "PROSPECTIVE_MANAGER", "NOTICE"]), priority: z.enum(["LOW", "MEDIUM", "HIGH", "URGENT"]), description: z.string().trim().min(1).max(10000), documentation: z.string().max(10000).optional() });
type Values = z.infer<typeof schema>;

export default function NewInformation() {
  const { role } = useAuth(); const router = useRouter(); const [saving, setSaving] = useState(false); const [photos, setPhotos] = useState<ImagePicker.ImagePickerAsset[]>([]);
  const blocks = useQuery({ queryKey: ["blocks", "information-form"], queryFn: () => getBlocks(), enabled: Boolean(role) });
  const form = useForm<Values>({ resolver: zodResolver(schema), defaultValues: { category: "ACTIVITY", priority: "MEDIUM", reportedAt: new Date().toISOString().slice(0, 10) } });
  if (!role) return null;
  async function choosePhotos() { const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) return Alert.alert("Izin diperlukan", "Izinkan akses galeri untuk menambahkan dokumentasi."); const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ["images"], allowsMultipleSelection: true, selectionLimit: 5 - photos.length, quality: 0.8 }); if (!result.canceled) setPhotos((current) => [...current, ...(result.assets ?? [])].slice(0, 5)); }
  async function submit(values: Values) { setSaving(true); try { const permission = await Location.requestForegroundPermissionsAsync(); if (permission.status !== "granted") throw new Error("Izin lokasi diperlukan untuk mengirim informasi lapangan."); const location = await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.Balanced }); const id = crypto.randomUUID(); const attachments = await Promise.all(photos.map(async (photo) => { const sizeBytes = photo.fileSize ?? 0; if (!sizeBytes) throw new Error("Ukuran foto tidak tersedia."); const contentType = photo.mimeType ?? "image/jpeg"; const upload = await createDailyInformationAttachmentUploadUrl({ id, contentType, sizeBytes, originalName: photo.fileName ?? `informasi-${Date.now()}.jpg` }) as { key: string; uploadUrl: string }; const response = await fetch(upload.uploadUrl, { method: "PUT", headers: { "Content-Type": contentType }, body: await (await fetch(photo.uri)).blob() }); if (!response.ok) throw new Error("Unggah dokumentasi gagal."); return { storageKey: upload.key, contentType, sizeBytes }; })); await createDailyInformation({ id, ...values, blockId: values.blockId || undefined, reportedAt: values.reportedAt || undefined, latitude: location.coords.latitude, longitude: location.coords.longitude, gpsAccuracy: location.coords.accuracy ?? 0, gpsCapturedAt: new Date().toISOString(), attachments }); Alert.alert("Berhasil", "Informasi harian berhasil dikirim.", [{ text: "OK", onPress: () => router.replace(`/information/${id}`) }]); } catch (error) { Alert.alert("Tidak dapat mengirim", error instanceof Error ? error.message : "Periksa data dan koneksi."); } finally { setSaving(false); } }
  return <><Header role={role} title="Informasi Harian Baru" subtitle="Kirim data lapangan" /><Screen><Text style={styles.heading}>Data Informasi</Text><SelectField label="Blok" value={form.watch("blockId") ?? ""} options={[{ label: "Tanpa blok", value: "" }, ...(blocks.data?.blocks ?? []).map((block) => ({ label: `${block.code} · ${block.name}`, value: block.id }))]} onChange={(value) => form.setValue("blockId", value || undefined, { shouldValidate: true })} /><DateField name="reportedAt" label="Tanggal dan waktu laporan" control={form.control} errors={form.formState.errors} /><SelectField label="Jenis informasi" value={form.watch("category")} options={[{ label: "Kegiatan", value: "ACTIVITY" }, { label: "Keluhan", value: "COMPLAINT" }, { label: "Pemberitahuan", value: "NOTICE" }, { label: "Insiden", value: "INCIDENT" }, { label: "Calon pengelola", value: "PROSPECTIVE_MANAGER" }]} onChange={(value) => form.setValue("category", value as Values["category"], { shouldValidate: true })} /><SelectField label="Prioritas" value={form.watch("priority")} options={[{ label: "Rendah", value: "LOW" }, { label: "Sedang", value: "MEDIUM" }, { label: "Tinggi", value: "HIGH" }, { label: "Mendesak", value: "URGENT" }]} onChange={(value) => form.setValue("priority", value as Values["priority"], { shouldValidate: true })} /><InputField name="description" label="Deskripsi" multiline register={form.register} errors={form.formState.errors} /><InputField name="documentation" label="Catatan dokumentasi" multiline register={form.register} errors={form.formState.errors} /><Pressable onPress={() => void choosePhotos()} style={styles.photoButton}><Text style={styles.photoText}>Tambah Foto ({photos.length}/5)</Text></Pressable>{photos.length ? <View style={styles.photos}>{photos.map((photo) => <Image key={photo.uri} source={{ uri: photo.uri }} style={styles.photo} />)}</View> : null}<Text style={styles.gps}>GPS akan direkam saat data dikirim.</Text><SubmitButton label="Kirim Data" loading={saving} onPress={() => void form.handleSubmit(submit)()} /></Screen></>;
}

const styles = StyleSheet.create({ heading: { color: colors.text, fontSize: 16, fontWeight: "900", marginBottom: spacing.sm }, photoButton: { alignItems: "center", borderColor: colors.primary, borderRadius: 10, borderWidth: 1, padding: 13 }, photoText: { color: colors.primary, fontSize: 12, fontWeight: "900" }, photos: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, photo: { borderRadius: 8, height: 64, width: 64 }, gps: { color: colors.textMuted, fontSize: 10 } });
