import { showActionError } from "../../src/lib/feedback";
import { useQuery } from "@tanstack/react-query";
import { useRouter } from "expo-router";
import { useState } from "react";
import { AppAlert as Alert } from "../../src/lib/feedback";

import { useAuth } from "../../src/auth";
import { Header, Screen } from "../../src/components/Screen";
import { DatePicker, SelectField, SubmitButton, TextInputField } from "../../src/components/NativeForm";
import { FormSection } from "../../src/components/OperationalPrimitives";
import { getBlocks, getFieldOfficers, getFieldWorkers, createFieldTask } from "../../src/lib/api";
import { taskFormSchema } from "../../src/form-schemas";

export default function NewTaskScreen() {
  const { role } = useAuth(); const router = useRouter(); const [saving, setSaving] = useState(false); const [blockId, setBlockId] = useState(""); const [officerId, setOfficerId] = useState(""); const [workerId, setWorkerId] = useState(""); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [priority, setPriority] = useState("MEDIUM"); const [dueDate, setDueDate] = useState(""); const [errors, setErrors] = useState<Record<string, string>>({});
  const blocks = useQuery({ queryKey: ["blocks", "task-form"], queryFn: () => getBlocks(), enabled: Boolean(role) }); const officers = useQuery({ queryKey: ["field-officers"], queryFn: getFieldOfficers, enabled: Boolean(role) }); const workers = useQuery({ queryKey: ["field-workers", "task-form"], queryFn: () => getFieldWorkers({ status: "ACTIVE" }), enabled: Boolean(role) });
  if (!role) return null;
  async function save() { const parsed = taskFormSchema.safeParse({ blockId, assignedFieldOfficerId: officerId, assignedWorkerId: workerId, title, description, priority, dueDate }); const nextErrors: Record<string, string> = {}; if (!parsed.success) parsed.error.issues.forEach((issue) => { const key = String(issue.path[0] ?? "form"); if (!nextErrors[key]) nextErrors[key] = issue.message; }); setErrors(nextErrors); if (!parsed.success) return; setSaving(true); try { await createFieldTask(parsed.data); Alert.alert("Tugas dibuat", "Tugas lapangan telah diberikan.", [{ text: "OK", onPress: () => router.back() }]); } catch (error) { showActionError(error, "Periksa data dan koneksi lalu coba lagi."); } finally { setSaving(false); } }
  return <><Header role={role} title="Tugas Lapangan Baru" subtitle="Tetapkan pekerjaan dan penanggung jawab" /><Screen><FormSection title="Tujuan tugas" optional={false}><SelectField label="Blok" required error={errors.blockId} value={blockId} onChange={(value) => { setBlockId(value); setErrors((current) => ({ ...current, blockId: "" })); }} options={(blocks.data?.blocks ?? []).map((item) => ({ label: `${item.code} · ${item.name}`, value: item.id }))} /><SelectField label="Petugas lapangan" required error={errors.officerId} value={officerId} onChange={(value) => { setOfficerId(value); setErrors((current) => ({ ...current, officerId: "" })); }} options={(officers.data?.officers ?? []).map((item) => ({ label: item.name, value: item.id }))} /><TextInputField label="Judul tugas" required error={errors.title} value={title} onChange={(value) => { setTitle(value); setErrors((current) => ({ ...current, title: "" })); }} placeholder="Contoh: Periksa akses jalan" /><SelectField label="Prioritas" required value={priority} onChange={setPriority} options={[{ label: "Rendah", value: "LOW" }, { label: "Sedang", value: "MEDIUM" }, { label: "Tinggi", value: "HIGH" }, { label: "Mendesak", value: "URGENT" }]} /></FormSection><FormSection title="Rincian tambahan" description="Tambahkan konteks jika diperlukan."><SelectField label="Pekerja" value={workerId} onChange={setWorkerId} options={[{ label: "Tanpa pekerja khusus", value: "" }, ...(workers.data?.items ?? []).map((item) => ({ label: String(item.fullName), value: String(item.id) }))]} /><TextInputField label="Deskripsi" error={errors.description} value={description} onChange={(value) => { setDescription(value); setErrors((current) => ({ ...current, description: "" })); }} multiline placeholder="Jelaskan pekerjaan (opsional)" /><DatePicker label="Tenggat" value={dueDate} onChange={setDueDate} /></FormSection><SubmitButton label="Simpan Tugas" loading={saving} onPress={() => void save()} /></Screen></>;
}
