import Link from "next/link";
import { Plus } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/shared/empty-state";
import { MoneyDisplay } from "@/components/shared/money-display";
import { MOBILE_SURFACE } from "@/src/lib/ui/mobile-tokens";

type FinanceEntry = { id: string; code: string; description: string; amount: number; direction: "in" | "out"; status: string };
type BudgetEntry = { id: string; periodKey: string; totalAllocation: number; availableFunds: number; absorptionPercentage: number; status: string };
type RealizationEntry = { id: string; description: string; amount: number; status: string; groupName: string };

function statusTone(status: string): string {
  if (["SAH", "DITERIMA", "LUNAS"].includes(status)) return MOBILE_SURFACE.statusSuccess;
  if (["DIAJUKAN", "DIVERIFIKASI", "VERIFIED"].includes(status)) return MOBILE_SURFACE.statusInfo;
  if (["REJECTED", "TUNGGAKAN"].includes(status)) return MOBILE_SURFACE.statusDanger;
  return MOBILE_SURFACE.statusWarning;
}

export function MobileFinanceScreen({ cashBalance, cashIn, cashOut, transactionCount, entries }: { cashBalance: number; cashIn: number; cashOut: number; transactionCount: number; entries: FinanceEntry[] }) {
  return <section className="space-y-3 md:hidden"><div className="flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#26704c]">Dashboard Keuangan</p><h2 className="mt-1 text-base font-extrabold text-[#143f2d]">Ringkasan Bulan Ini</h2></div><span className="text-[9px] text-[#728076]">Data aktual</span></div><div className="grid grid-cols-2 gap-2.5"><FinanceMetric label="Saldo Kas Aktual" value={cashBalance} detail="Saldo saat ini" /><FinanceMetric label="Uang Masuk" value={cashIn} detail="Penerimaan tercatat" /><FinanceMetric danger label="Uang Keluar" value={cashOut} detail="Pengeluaran tercatat" /><div className="rounded-xl border border-[#dcebe2] bg-white p-3 shadow-sm"><p className="text-[9px] font-semibold text-[#6c7b71]">Transaksi</p><p className="mt-1 text-xl font-extrabold text-[#143f2d]">{transactionCount}</p><p className="mt-1 text-[9px] text-[#7a877e]">Tercatat</p></div></div><div className="overflow-hidden rounded-xl border border-[#dcebe2] bg-white shadow-sm"><div className="flex items-center justify-between border-b border-[#edf2ee] px-3 py-3"><p className="text-xs font-bold text-[#143f2d]">Daftar Transaksi</p><Link className="text-[9px] font-bold text-[#26704c]" href="/dashboard/finance/transactions">Lihat Semua →</Link></div>{entries.length ? entries.map((entry) => <Link className="flex items-center justify-between gap-3 border-b border-[#edf2ee] px-3 py-3 last:border-0" href={`/dashboard/finance/transactions/${entry.id}`} key={entry.id}><div className="min-w-0"><p className="text-[10px] font-bold text-[#223a2c]">{entry.code}</p><p className="mt-0.5 truncate text-[9px] text-[#78847b]">{entry.description}</p></div><div className="text-right"><p className={`text-[10px] font-bold ${entry.direction === "in" ? "text-[#177444]" : "text-[#cf554b]"}`}>{entry.direction === "in" ? "+" : "-"}<MoneyDisplay value={entry.amount} /></p><Badge className={`border-0 px-1.5 py-0.5 text-[8px] ${statusTone(entry.status)}`} variant="outline">{entry.status}</Badge></div></Link>) : <EmptyState description="Transaksi kas akan muncul setelah dicatat dan diproses." title="Belum ada transaksi" />}</div></section>;
}

function FinanceMetric({ danger, detail, label, value }: { danger?: boolean; detail: string; label: string; value: number }) {
  return <div className={`${MOBILE_SURFACE.cardFinancePadded} ${danger ? "border-[#f0e2d4]" : ""}`}><p className="text-[9px] font-semibold text-[#6c7b71]">{label}</p><p className={`mt-1 text-sm font-extrabold ${danger ? "text-[#cf554b]" : "text-[#177444]"}`}><MoneyDisplay value={value} /></p><p className="mt-1 text-[9px] text-[#7a877e]">{detail}</p></div>;
}

export function MobileBudgetScreen({ item, canCreate, categories }: { item: BudgetEntry | null; canCreate: boolean; categories: Array<{ name: string; amount: number }> }) {
  if (!item) return <section className="rounded-2xl border border-[#dcebe2] bg-white md:hidden"><EmptyState description="Buat periode anggaran untuk mulai menyusun alokasi." title="Belum ada anggaran" action={canCreate ? <Button asChild className="bg-[#16834a] text-xs"><Link href="/dashboard/budgets">Buat periode</Link></Button> : undefined} /></section>;
  const budget = item;
  const unallocated = Math.max(0, budget.availableFunds - budget.totalAllocation);
  return <section className="space-y-3 md:hidden"><div className="flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#26704c]">Anggaran / Alokasi</p><h2 className="mt-1 text-base font-extrabold text-[#143f2d]">Periode Berjalan</h2></div><span className="text-[9px] text-[#728076]">Periode: {budget.periodKey}</span></div><div className="grid grid-cols-2 gap-2.5"><div className="col-span-2 rounded-xl border border-[#dcebe2] bg-white p-3 shadow-sm"><p className="text-[9px] font-semibold text-[#6c7b71]">Total Alokasi</p><p className="mt-1 text-base font-extrabold text-[#177444]"><MoneyDisplay value={budget.totalAllocation} /></p></div><FinanceMetric label="Sudah Dialokasikan" value={budget.totalAllocation} detail="Rincian anggaran" /><FinanceMetric danger label="Sisa Belum Dialokasikan" value={unallocated} detail="Perlu dialokasikan" /></div><div className="rounded-xl border border-[#dcebe2] bg-white p-3 shadow-sm"><div className="flex items-center justify-between"><p className="text-xs font-bold text-[#143f2d]">Rincian Per Kategori</p><Badge className={`border-0 px-1.5 py-0.5 text-[8px] ${statusTone(budget.status)}`} variant="outline">{budget.status}</Badge></div>{categories.length ? categories.map((category) => <BudgetBar amount={new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(category.amount)} key={category.name} label={category.name} percentage={budget.totalAllocation > 0 ? (category.amount / budget.totalAllocation) * 100 : 0} />) : <p className="py-6 text-center text-[10px] text-[#7a877e]">Belum ada rincian kategori.</p>}</div>{canCreate ? <Button asChild className="h-10 w-full rounded-lg bg-[#16834a] text-xs font-bold"><Link href={item ? `/dashboard/budgets/${item.id}` : "/dashboard/budgets"}><Plus className="size-4" /> Buat Alokasi Anggaran</Link></Button> : null}</section>;
}

function BudgetBar({ amount, label, percentage }: { amount: string; label: string; percentage: number }) {
  return <div className="mt-4"><div className="flex items-end justify-between gap-2 text-[9px] text-[#53655a]"><span className="max-w-[72%] font-semibold leading-relaxed">{label}<small className="block text-[#78847b]">{amount}</small></span><strong>{percentage.toFixed(2).replace(".", ",")}%</strong></div><div className="mt-1 h-1.5 rounded-full bg-[#e4eae5]"><div className="h-full rounded-full bg-[#1454c4]" style={{ width: `${Math.min(100, percentage)}%` }} /></div></div>;
}

export function MobileRealizationScreen({ canCreate, entries }: { canCreate: boolean; entries: RealizationEntry[] }) {
  return <section className="space-y-3 md:hidden"><div className="flex items-center gap-5 border-b border-[#dcebe2] pb-2 text-[10px] font-semibold text-[#728076]"><Link className="border-b-2 border-[#16834a] pb-2 text-[#16834a]" href="/dashboard/realizations">Semua</Link><Link href="/dashboard/realizations?status=DRAFT">Draft</Link><Link href="/dashboard/realizations?status=SUBMITTED">Diajukan</Link><Link href="/dashboard/realizations?status=VERIFIED">Diverifikasi</Link><Link href="/dashboard/realizations?status=SAH">Sah</Link></div>{entries.length ? <div className="space-y-2.5">{entries.map((entry) => <Link className="block rounded-xl border border-[#dcebe2] bg-white p-3 shadow-sm" href={`/dashboard/realizations/${entry.id}`} key={entry.id}><div className="flex items-start justify-between gap-2"><div><p className="text-[10px] font-bold text-[#143f2d]">{entry.id.slice(0, 8)}</p><p className="mt-1 text-[10px] font-semibold text-[#263959]">{entry.description}</p></div><Badge className={`border-0 px-1.5 py-0.5 text-[8px] ${statusTone(entry.status)}`} variant="outline">{entry.status}</Badge></div><div className="mt-3 flex items-end justify-between text-[9px] text-[#728076]"><span>{entry.groupName}</span><strong className="text-[10px] text-[#143f2d]"><MoneyDisplay value={entry.amount} /></strong></div></Link>)}</div> : <div className="rounded-2xl border border-[#dcebe2] bg-white"><EmptyState description="Pengajuan penggunaan dana akan muncul setelah dibuat." title="Belum ada pengajuan" /></div>}{canCreate ? <Button asChild className="h-10 w-full rounded-lg bg-[#1454c4] text-xs font-bold"><Link href="/dashboard/realizations/new"><Plus className="size-4" /> Buat Pengajuan Baru</Link></Button> : null}</section>;
}
