export const FUND_REQUEST_STATUSES = ["DRAFT", "SUBMITTED", "VERIFIED", "APPROVED", "REVISION_REQUIRED", "REJECTED", "CANCELLED"] as const;

export const FUND_REQUEST_TRANSITIONS = {
  DRAFT: ["SUBMITTED", "CANCELLED"],
  SUBMITTED: ["VERIFIED", "REVISION_REQUIRED", "REJECTED"],
  VERIFIED: ["APPROVED", "REVISION_REQUIRED", "REJECTED"],
  APPROVED: [],
  REVISION_REQUIRED: ["SUBMITTED", "CANCELLED"],
  REJECTED: [],
  CANCELLED: [],
} as const;
