import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useState } from "react";
import { Alert, Linking, Pressable, StyleSheet, Text, View } from "react-native";
import { TextInput } from "../../src/components/ui/TextInput";

import { useAuth } from "../../src/auth";
import { BottomNav, ErrorState, Header, LoadingState, Screen } from "../../src/components/Screen";
import { RowCard, StatusPill } from "../../src/components/PimpinanPrimitives";
import { getDue, getDuePaymentEvidenceDownloadUrl, reverseDuePayment } from "../../src/lib/api";
import { money } from "../../src/lib/format";
import { numberValue, text } from "../../src/lib/read";
import { colors, spacing } from "../../src/theme";
import { reversalFormSchema } from "../../src/form-schemas";

export default function DueDetail() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { role, session } = useAuth(); const router = useRouter(); const client = useQueryClient(); const [reason, setReason] = useState("");
  const query = useQuery({ queryKey: ["due", id], queryFn: () => getDue(id), enabled: Boolean(role && id) });
  if (!role) return null;
  if (query.isLoading) return <><Header role={role} title="Detail Iuran" /><Screen><LoadingState /></Screen></>;
  if (query.isError || !query.data?.due) return <><Header role={role} title="Detail Iuran" /><Screen><ErrorState message="Detail iuran tidak dapat dimuat." onRetry={() => query.refetch()} /></Screen></>;
  const record = query.data.due as { item?: Record<string, unknown>; payments?: Array<Record<string, unknown>>; verifications?: Array<Record<string, unknown>> }; const due = record.item ?? {}; const canPay = session?.permissions.includes("PAYMENT_CREATE"); const canReverse = session?.permissions.includes("DUES_MANAGE"); const canVerify = session?.permissions.includes("PAYMENT_FIELD_VERIFY");
  async function reverse(paymentId: string) { const parsed = reversalFormSchema.safeParse({ reason }); if (!parsed.success) return Alert.alert("Alasan diperlukan", parsed.error.issues[0]?.message ?? "Masukkan alasan pembatalan pembayaran."); try { await reverseDuePayment({ duePaymentId: paymentId, ...parsed.data, idempotencyKey: crypto.randomUUID() }); setReason(""); await client.invalidateQueries({ queryKey: ["due", id] }); await client.invalidateQueries({ queryKey: ["dues"] }); await client.invalidateQueries({ queryKey: ["transactions"] }); } catch (error) { Alert.alert("Tidak dapat membatalkan", error instanceof Error ? error.message : "Periksa koneksi lalu coba lagi."); } }
  async function openEvidence(paymentId: string) { try { const result = await getDuePaymentEvidenceDownloadUrl({ duePaymentId: paymentId }); await Linking.openURL(result.downloadUrl); } catch (error) { Alert.alert("Bukti tidak dapat dibuka", error instanceof Error ? error.message : "Coba lagi."); } }
  return <><Header role={role} title="Detail Iuran" subtitle={text(due, "referenceKey")} /><Screen><View style={styles.summary}><Text style={styles.label}>SISA TAGIHAN</Text><Text style={styles.amount}>{money(numberValue(due, "remaining"))}</Text><StatusPill tone={text(due, "paymentState") === "PAID" ? "green" : "orange"}>{text(due, "paymentState")}</StatusPill><Text style={styles.value}>{text(due, "payerName")} · {text(due, "dueType")}</Text></View>{canPay && numberValue(due, "remaining") > 0 ? <Pressable onPress={() => router.push(`/payment/${id}`)} style={styles.primary}><Text style={styles.primaryText}>Catat Pembayaran</Text></Pressable> : null}{canReverse && record.payments?.some((payment) => text(payment, "cashStatus") === "SAH") ? <View style={styles.reversal}><TextInput value={reason} onChangeText={setReason} placeholder="Alasan pembatalan pembayaran" multiline style={styles.input} /></View> : null}<View style={styles.section}><Text style={styles.title}>Riwayat Pembayaran</Text>{record.payments?.map((payment) => { const paymentId = text(payment, "id"); const reversible = canReverse && text(payment, "cashStatus") === "SAH"; return <View key={paymentId} style={styles.payment}><RowCard title={money(numberValue(payment, "amount"))} subtitle={`${text(payment, "payerName")} · ${text(payment, "method")}`} meta={text(payment, "paymentDate")} status={reversible ? "Batalkan" : text(payment, "cashStatus")} tone={text(payment, "cashStatus") === "REVERSED" ? "gray" : "green"} onPress={reversible ? () => void reverse(paymentId) : text(payment, "evidenceKey") ? () => void openEvidence(paymentId) : undefined} />{canVerify ? <Pressable onPress={() => router.push({ pathname: "/payment/verify", params: { duePaymentId: paymentId } })}><Text style={styles.verify}>Verifikasi lapangan</Text></Pressable> : null}</View>; })}</View><View style={styles.section}><Text style={styles.title}>Verifikasi Lapangan</Text>{record.verifications?.map((entry) => <RowCard key={text(entry, "due_payment_verification", "id")} title={text(entry, "verificationStatus")} subtitle={text(entry, "notes", "Tanpa catatan")} meta={text(entry, "verifiedAt")} />)}</View></Screen><BottomNav current="finance" role={role} /></>;
}
const styles = StyleSheet.create({ summary: { backgroundColor: colors.primaryDark, borderRadius: 14, gap: 7, padding: spacing.lg }, label: { color: "#DCE7FF", fontSize: 10, fontWeight: "800" }, amount: { color: "#FFFFFF", fontSize: 24, fontWeight: "900" }, value: { color: "#DCE7FF", fontSize: 11 }, primary: { alignItems: "center", backgroundColor: colors.primary, borderRadius: 10, padding: 13 }, primaryText: { color: "#FFFFFF", fontSize: 12, fontWeight: "900" }, reversal: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 12, borderWidth: 1, padding: spacing.md }, input: { borderColor: colors.border, borderRadius: 9, borderWidth: 1, color: colors.text, minHeight: 54, padding: 10, textAlignVertical: "top" }, section: { gap: spacing.sm }, payment: { gap: 4 }, verify: { color: colors.primary, fontSize: 11, fontWeight: "900", paddingLeft: 8 }, title: { color: colors.text, fontSize: 14, fontWeight: "900" } });
